import { readFileSync } from "node:fs";
import { getMessages } from "../lib/messages";
import {
  ANALYZE_RESULT_STORAGE_KEY,
  validateStoredAnalyzeResult,
  type StoredAnalyzeResult,
} from "../lib/competitor-scripts/analyze-result-storage";
import {
  MAX_LANGUAGE_CODE_LENGTH,
  MAX_SEGMENT_TEXT_LENGTH,
  MAX_SEGMENTS,
  MAX_TRANSCRIPT_TEXT_LENGTH,
} from "../lib/competitor-scripts/transcript/normalize";
import type { AnalysisLocale } from "../lib/competitor-scripts/analysis/types";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Analyze Frontend Tests\n");

// Used only when a check must scan for the absence of a word/phrase in
// actual code — explanatory comments in this codebase legitimately
// discuss what a file does NOT do (e.g. "never re-derives the verdict"),
// which would otherwise self-trigger a naive substring/regex check.
function stripComments(source: string): string {
  return source.replace(/\/\/.*$/gm, "");
}

// ── Fixtures ────────────────────────────────────────────────────────────

const SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about it.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  { text: "But there's a catch most people miss.", startMs: 9000, durationMs: 3000 },
  { text: "Once you see it, you can't unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];
const TRANSCRIPT_TEXT = SEGMENTS.map((segment) => segment.text).join(" ");

const VALID_RESULT: StoredAnalyzeResult = {
  v: 1,
  createdAt: 1_700_000_000_000,
  input: {
    videoId: "dQw4w9WgXcQ",
    canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    sourceFormat: "watch",
  },
  transcript: {
    languageCode: "en",
    isAutoGenerated: true,
    segments: SEGMENTS,
    text: TRANSCRIPT_TEXT,
    durationMs: 18000,
  },
  analysis: null,
  analysisError: null,
  isLegacy: false,
};

function makeValidAnalysisCandidate(locale: AnalysisLocale): Record<string, unknown> {
  return {
    schemaVersion: 1,
    locale,
    verdict: "strong",
    scores: { overallScore: 80, hookScore: 80, structureScore: 78, momentumScore: 75 },
    mainTakeaway:
      "This script opens with a concrete cost-based hook and closes with a direct call to action.",
    scoreReasons: [
      { score: "overallScore", driver: "The concrete hook and clear structure combine into a strong script." },
      { score: "hookScore", driver: "The opening names a specific cost immediately." },
      { score: "structureScore", driver: "The script moves cleanly from hook to payoff." },
      { score: "momentumScore", driver: "Pacing stays brisk with no dead stretches." },
    ],
    structure: [
      {
        label: "hook",
        evidence: { excerpt: "Wait, this one mistake is costing you views.", startMs: 0, endMs: 3000 },
        purpose: "Opens with a direct problem-cost claim.",
        analysis: "Grabs attention by naming a concrete cost immediately.",
      },
      {
        label: "payoff",
        evidence: { excerpt: "Try this on your next video.", startMs: 15000, endMs: 18000 },
        purpose: "Wraps with a direct call to action.",
        analysis: "Ends with a clear, actionable invitation.",
      },
    ],
    strengths: [
      {
        title: "Direct cost-based hook",
        evidence: { excerpt: "Wait, this one mistake is costing you views.", startMs: 0, endMs: 3000 },
        whyItWorks: "Naming a specific cost up front creates immediate stakes.",
      },
    ],
    weaknesses: [],
    retentionRisks: [],
    actionableLessons: [
      {
        principle: "Lead with a concrete cost",
        sourceEvidence: { excerpt: "Wait, this one mistake is costing you views.", startMs: 0, endMs: 3000 },
        application: "Open your own script by naming a specific cost of inaction.",
      },
      {
        principle: "Close with a direct next step",
        sourceEvidence: { excerpt: "Try this on your next video.", startMs: 15000, endMs: 18000 },
        application: "End your script with an explicit, simple action.",
      },
    ],
    caution: [],
  };
}

function withAnalysis(
  candidate: unknown,
  analysisError: StoredAnalyzeResult["analysisError"] = null
): StoredAnalyzeResult {
  return { ...VALID_RESULT, analysis: candidate as never, analysisError };
}

// ── validateStoredAnalyzeResult: pure-function, untrusted-input tests ──────

function testValidator() {
  check(
    "a valid, well-formed transcript-only payload (analysis:null, analysisError:null) is accepted, not legacy",
    (() => {
      const result = validateStoredAnalyzeResult(VALID_RESULT);
      return result !== null && result.isLegacy === false && result.analysis === null;
    })()
  );

  check(
    "a valid payload with languageCode/isAutoGenerated/durationMs all null is accepted",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        languageCode: null,
        isAutoGenerated: null,
        durationMs: null,
      },
    }) !== null
  );

  check(
    "a payload with an empty segments array is accepted",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, segments: [] },
    }) !== null
  );

  for (const notAnObject of [null, undefined, "a string", 42, [], true]) {
    check(
      `a non-object top-level value (${JSON.stringify(notAnObject)}) is rejected`,
      validateStoredAnalyzeResult(notAnObject) === null
    );
  }

  check(
    "a wrong storage version is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, v: 2 }) === null
  );

  check(
    "a non-numeric createdAt is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, createdAt: "yesterday" }) ===
      null
  );

  check(
    "a missing input object is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, input: undefined }) ===
      null
  );

  check(
    "a malformed videoId (wrong length/characters) is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: { ...VALID_RESULT.input, videoId: "not-a-real-id!" },
    }) === null
  );

  check(
    "a canonicalUrl that doesn't match videoId is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: {
        ...VALID_RESULT.input,
        canonicalUrl: "https://www.youtube.com/watch?v=differentId1",
      },
    }) === null
  );

  check(
    "a canonicalUrl that isn't a YouTube URL at all is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: {
        ...VALID_RESULT.input,
        canonicalUrl: "https://example.com/not-youtube",
      },
    }) === null
  );

  check(
    "an invalid sourceFormat is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: { ...VALID_RESULT.input, sourceFormat: "embed" },
    }) === null
  );

  check(
    "a missing transcript object is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, transcript: undefined }) ===
      null
  );

  check(
    "segments that are not an array are rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, segments: "not an array" },
    }) === null
  );

  check(
    "a segment missing required fields is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "no startMs here" }],
      },
    }) === null
  );

  check(
    "a segment with a negative startMs is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "bad", startMs: -1, durationMs: null }],
      },
    }) === null
  );

  check(
    "a segment with non-finite startMs (Infinity) is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "bad", startMs: Infinity, durationMs: null }],
      },
    }) === null
  );

  check(
    "a segment with text longer than MAX_SEGMENT_TEXT_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [
          {
            text: "x".repeat(MAX_SEGMENT_TEXT_LENGTH + 1),
            startMs: 0,
            durationMs: null,
          },
        ],
      },
    }) === null
  );

  check(
    "more segments than MAX_SEGMENTS is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: Array.from({ length: MAX_SEGMENTS + 1 }, (_, index) => ({
          text: "x",
          startMs: index,
          durationMs: null,
        })),
      },
    }) === null
  );

  check(
    "transcript text longer than MAX_TRANSCRIPT_TEXT_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        text: "x".repeat(MAX_TRANSCRIPT_TEXT_LENGTH + 1),
      },
    }) === null
  );

  check(
    "a languageCode longer than MAX_LANGUAGE_CODE_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        languageCode: "x".repeat(MAX_LANGUAGE_CODE_LENGTH + 1),
      },
    }) === null
  );

  check(
    "a non-boolean, non-null isAutoGenerated is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, isAutoGenerated: "yes" },
    }) === null
  );

  check(
    "a negative durationMs is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, durationMs: -100 },
    }) === null
  );

  const withExtraField = validateStoredAnalyzeResult({
    ...VALID_RESULT,
    somethingUnexpected: "should be dropped, not trusted",
  } as unknown);
  check(
    "an accepted payload with an unknown extra top-level field is validated by reconstruction — the extra field never survives into the returned object",
    withExtraField !== null &&
      !Object.prototype.hasOwnProperty.call(
        withExtraField,
        "somethingUnexpected"
      )
  );

  check(
    "an accepted payload never carries provider-only fields (apiKey/provider) even if injected",
    (() => {
      const tampered = {
        ...VALID_RESULT,
        transcript: {
          ...VALID_RESULT.transcript,
          apiKey: "sk-should-never-appear",
          provider: "supadata",
        },
      };
      const result = validateStoredAnalyzeResult(tampered);
      return (
        result !== null &&
        !JSON.stringify(result).toLowerCase().includes("apikey") &&
        !JSON.stringify(result).toLowerCase().includes("supadata")
      );
    })()
  );

  // ── Analysis-portion validation (PR10D) ─────────────────────────────

  check(
    "a legacy PR9-era payload (no analysis/analysisError keys at all) is recognized as legacy, analysis stays null",
    (() => {
      const legacyRaw = {
        v: VALID_RESULT.v,
        createdAt: VALID_RESULT.createdAt,
        input: VALID_RESULT.input,
        transcript: VALID_RESULT.transcript,
      };
      const result = validateStoredAnalyzeResult(legacyRaw);
      return (
        result !== null &&
        result.isLegacy === true &&
        result.analysis === null &&
        result.analysisError === null
      );
    })()
  );

  check(
    "a current-shape payload with analysis:null, analysisError:'analysis_unavailable' is accepted, not legacy",
    (() => {
      const result = validateStoredAnalyzeResult(
        withAnalysis(null, "analysis_unavailable")
      );
      return (
        result !== null &&
        result.isLegacy === false &&
        result.analysis === null &&
        result.analysisError === "analysis_unavailable"
      );
    })()
  );

  check(
    "a current-shape payload with analysis:null, analysisError:'transcript_too_long_for_analysis' is accepted",
    (() => {
      const result = validateStoredAnalyzeResult(
        withAnalysis(null, "transcript_too_long_for_analysis")
      );
      return result !== null && result.analysisError === "transcript_too_long_for_analysis";
    })()
  );

  check(
    "an invalid analysisError string is dropped rather than trusted",
    (() => {
      const result = validateStoredAnalyzeResult(
        withAnalysis(null, "not_a_real_code" as never)
      );
      return result !== null && result.analysisError === "analysis_unavailable";
    })()
  );

  check(
    "a genuinely valid analysis object (en) passes real re-validation and is returned",
    (() => {
      const result = validateStoredAnalyzeResult(
        withAnalysis(makeValidAnalysisCandidate("en"))
      );
      return (
        result !== null &&
        result.analysis !== null &&
        result.analysis.verdict === "strong" &&
        result.analysisError === null
      );
    })()
  );

  check(
    "a genuinely valid analysis object (ru) passes real re-validation, evidence excerpt stays original transcript language",
    (() => {
      const result = validateStoredAnalyzeResult(
        withAnalysis(makeValidAnalysisCandidate("ru"))
      );
      return (
        result !== null &&
        result.analysis !== null &&
        result.analysis.locale === "ru" &&
        result.analysis.structure[0].evidence.excerpt ===
          "Wait, this one mistake is costing you views."
      );
    })()
  );

  check(
    "a stored analysis with a mismatched verdict (fails real grounding/consistency validation) is rejected — analysis becomes null, analysisError becomes analysis_invalid_response",
    (() => {
      const tampered = { ...makeValidAnalysisCandidate("en"), verdict: "weak" };
      const result = validateStoredAnalyzeResult(withAnalysis(tampered));
      return (
        result !== null &&
        result.analysis === null &&
        result.analysisError === "analysis_invalid_response"
      );
    })()
  );

  check(
    "a stored analysis with a tampered evidence excerpt not found in the transcript is rejected (real grounding check, not a weaker duplicate)",
    (() => {
      const candidate = makeValidAnalysisCandidate("en") as {
        structure: Array<{ evidence: { excerpt: string } }>;
      };
      candidate.structure[0].evidence.excerpt = "This text is not in the transcript at all.";
      const result = validateStoredAnalyzeResult(withAnalysis(candidate));
      return result !== null && result.analysis === null && result.analysisError === "analysis_invalid_response";
    })()
  );

  check(
    "a tampered 'analysisError: null' paired with broken analysis content never reads as success",
    (() => {
      const tampered = { ...makeValidAnalysisCandidate("en"), verdict: "weak" };
      const result = validateStoredAnalyzeResult(withAnalysis(tampered, null));
      return result !== null && result.analysis === null && result.analysisError === "analysis_invalid_response";
    })()
  );

  check(
    "an inconsistent current-shape payload (analysis:null, analysisError:null, not legacy) degrades safely rather than crashing",
    (() => {
      const raw = {
        v: VALID_RESULT.v,
        createdAt: VALID_RESULT.createdAt,
        input: VALID_RESULT.input,
        transcript: VALID_RESULT.transcript,
        analysis: null,
        analysisError: null,
      };
      const result = validateStoredAnalyzeResult(raw);
      return (
        result !== null &&
        result.isLegacy === false &&
        result.analysis === null &&
        result.analysisError === "analysis_unavailable"
      );
    })()
  );

  check(
    "a non-object analysis value is rejected rather than crashing the validator",
    (() => {
      const result = validateStoredAnalyzeResult(withAnalysis("not an object" as never));
      return result !== null && result.analysis === null;
    })()
  );

  check(
    "a valid transcript remains usable even when the analysis portion is malformed (transcript is never erased for a bad analysis)",
    (() => {
      const tampered = { ...makeValidAnalysisCandidate("en"), verdict: "weak" };
      const result = validateStoredAnalyzeResult(withAnalysis(tampered));
      return (
        result !== null &&
        result.transcript.text === TRANSCRIPT_TEXT &&
        result.input.videoId === VALID_RESULT.input.videoId
      );
    })()
  );
}

// ── sessionStorage round-trip (read/write) with a fake browser storage ────

function testStorageRoundTrip() {
  class FakeSessionStorage {
    private store = new Map<string, string>();
    getItem(key: string): string | null {
      return this.store.has(key) ? this.store.get(key)! : null;
    }
    setItem(key: string, value: string): void {
      this.store.set(key, value);
    }
    removeItem(key: string): void {
      this.store.delete(key);
    }
    clear(): void {
      this.store.clear();
    }
  }

  return (async () => {
    const fakeStorage = new FakeSessionStorage();
    (globalThis as { sessionStorage?: unknown }).sessionStorage = fakeStorage;

    const { readStoredAnalyzeResult, writeStoredAnalyzeResult } =
      await import("../lib/competitor-scripts/analyze-result-storage");

    check(
      "reading with nothing stored returns null, never throws",
      readStoredAnalyzeResult() === null
    );

    fakeStorage.setItem(ANALYZE_RESULT_STORAGE_KEY, "{not valid json");
    check(
      "reading malformed JSON returns null, never throws",
      readStoredAnalyzeResult() === null
    );

    fakeStorage.setItem(
      ANALYZE_RESULT_STORAGE_KEY,
      JSON.stringify({ v: 1, tampered: true })
    );
    check(
      "reading a structurally-invalid-but-valid-JSON value returns null",
      readStoredAnalyzeResult() === null
    );

    // Legacy PR9-shape write (bypassing writeStoredAnalyzeResult, which
    // always writes the current shape) — simulates an old tab's leftover
    // sessionStorage entry from before analysis existed.
    fakeStorage.setItem(
      ANALYZE_RESULT_STORAGE_KEY,
      JSON.stringify({
        v: 1,
        createdAt: Date.now(),
        input: VALID_RESULT.input,
        transcript: VALID_RESULT.transcript,
      })
    );
    const legacyRead = readStoredAnalyzeResult();
    check(
      "a legacy stored payload reads back with isLegacy:true, analysis:null, no crash, video/transcript data intact",
      legacyRead !== null &&
        legacyRead.isLegacy === true &&
        legacyRead.analysis === null &&
        legacyRead.transcript.text === TRANSCRIPT_TEXT
    );

    writeStoredAnalyzeResult({
      input: VALID_RESULT.input,
      transcript: VALID_RESULT.transcript,
      analysis: null,
      analysisError: null,
    });
    const roundTripped = readStoredAnalyzeResult();
    check(
      "a value written by writeStoredAnalyzeResult reads back as valid, not legacy",
      roundTripped !== null &&
        roundTripped.isLegacy === false &&
        roundTripped.input.videoId === VALID_RESULT.input.videoId &&
        roundTripped.transcript.text === VALID_RESULT.transcript.text
    );

    check(
      "writeStoredAnalyzeResult never persists an isLegacy property in the raw sessionStorage JSON — isLegacy is read-time-derived only, never product data",
      (() => {
        const raw = fakeStorage.getItem(ANALYZE_RESULT_STORAGE_KEY);
        if (raw === null) return false;
        const parsed = JSON.parse(raw) as Record<string, unknown>;
        return (
          !("isLegacy" in parsed) &&
          "analysis" in parsed &&
          "analysisError" in parsed &&
          "v" in parsed &&
          "createdAt" in parsed &&
          "input" in parsed &&
          "transcript" in parsed
        );
      })()
    );

    const validAnalysis = makeValidAnalysisCandidate("en");
    writeStoredAnalyzeResult({
      input: VALID_RESULT.input,
      transcript: VALID_RESULT.transcript,
      analysis: validAnalysis as never,
      analysisError: null,
    });
    const withRealAnalysis = readStoredAnalyzeResult();
    check(
      "a written real analysis round-trips through sessionStorage and re-validates on read",
      withRealAnalysis !== null &&
        withRealAnalysis.analysis !== null &&
        withRealAnalysis.analysis.verdict === "strong" &&
        withRealAnalysis.analysisError === null
    );

    writeStoredAnalyzeResult({
      input: VALID_RESULT.input,
      transcript: VALID_RESULT.transcript,
      analysis: null,
      analysisError: "analysis_unavailable",
    });
    const degraded = readStoredAnalyzeResult();
    check(
      "a written degraded (analysisError) result round-trips correctly, transcript still present",
      degraded !== null &&
        degraded.analysis === null &&
        degraded.analysisError === "analysis_unavailable" &&
        degraded.transcript.text === TRANSCRIPT_TEXT
    );

    const otherResult: StoredAnalyzeResult["input"] = {
      videoId: "dQw4w9WgXcR",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcR",
      sourceFormat: "watch",
    };
    writeStoredAnalyzeResult({
      input: otherResult,
      transcript: { ...VALID_RESULT.transcript, text: "A second video." },
      analysis: null,
      analysisError: null,
    });
    const overwritten = readStoredAnalyzeResult();
    check(
      "a new successful write overwrites the previous stored result rather than merging with it",
      overwritten !== null &&
        overwritten.input.videoId === "dQw4w9WgXcR" &&
        overwritten.transcript.text === "A second video."
    );
  })();
}

// ── fresh API response: status/analysis/analysisError cross-field invariants ─
// isValidSuccessPayload is the one gate a fresh, untrusted HTTP response
// must pass before writeStoredAnalyzeResult is ever called — a fresh
// response is exactly as untrusted as sessionStorage, so `status` alone is
// never enough: it must actually agree with analysis/analysisError, or the
// whole payload is rejected outright (never silently normalized into a
// fabricated state).

function testApiResponseValidation() {
  return (async () => {
    const { isValidSuccessPayload } = await import(
      "../app/competitor-scripts/analyze/analyze-input-form"
    );

    const baseInput = VALID_RESULT.input;
    const baseTranscript = {
      languageCode: VALID_RESULT.transcript.languageCode,
      isAutoGenerated: VALID_RESULT.transcript.isAutoGenerated,
      segments: VALID_RESULT.transcript.segments,
      text: VALID_RESULT.transcript.text,
      durationMs: VALID_RESULT.transcript.durationMs,
    };
    const validAnalysis = makeValidAnalysisCandidate("en");

    function payload(overrides: {
      analysis?: unknown;
      analysisError?: unknown;
      status?: unknown;
    }): unknown {
      return {
        ok: true,
        input: baseInput,
        transcript: baseTranscript,
        analysis: overrides.analysis ?? null,
        analysisError: overrides.analysisError ?? null,
        status: overrides.status,
      };
    }

    check(
      "A. status:analysis_ready, analysis:null, analysisError:null → rejected",
      !isValidSuccessPayload(
        payload({ status: "analysis_ready", analysis: null, analysisError: null })
      )
    );

    check(
      "B. status:analysis_ready, valid analysis, analysisError:'analysis_unavailable' → rejected",
      !isValidSuccessPayload(
        payload({
          status: "analysis_ready",
          analysis: validAnalysis,
          analysisError: "analysis_unavailable",
        })
      )
    );

    check(
      "C. status:transcript_ready, valid analysis, analysisError:null → rejected",
      !isValidSuccessPayload(
        payload({
          status: "transcript_ready",
          analysis: validAnalysis,
          analysisError: null,
        })
      )
    );

    check(
      "D. status:transcript_ready, analysis:null, analysisError:null → rejected",
      !isValidSuccessPayload(
        payload({ status: "transcript_ready", analysis: null, analysisError: null })
      )
    );

    check(
      "E. status:analysis_ready, valid analysis, analysisError:null → accepted",
      isValidSuccessPayload(
        payload({
          status: "analysis_ready",
          analysis: validAnalysis,
          analysisError: null,
        })
      )
    );

    check(
      "F. status:transcript_ready, analysis:null, analysisError:'analysis_unavailable' → accepted",
      isValidSuccessPayload(
        payload({
          status: "transcript_ready",
          analysis: null,
          analysisError: "analysis_unavailable",
        })
      )
    );

    check(
      "an unrecognized status value is rejected outright, regardless of otherwise-consistent analysis/analysisError",
      !isValidSuccessPayload(
        payload({
          status: "something_else",
          analysis: validAnalysis,
          analysisError: null,
        })
      )
    );

    check(
      "status:analysis_ready with a non-object analysis is rejected",
      !isValidSuccessPayload(
        payload({ status: "analysis_ready", analysis: "not-an-object", analysisError: null })
      )
    );

    check(
      "status:transcript_ready with an unrecognized analysisError code is rejected",
      !isValidSuccessPayload(
        payload({
          status: "transcript_ready",
          analysis: null,
          analysisError: "not_a_real_code",
        })
      )
    );

    check(
      "the source only ever calls writeStoredAnalyzeResult inside the isValidSuccessPayload(payload) branch — a rejected payload structurally can never reach a write, so no fake analysis state can be persisted",
      (() => {
        const analyzeFormSource = readFileSync(
          "app/competitor-scripts/analyze/analyze-input-form.tsx",
          "utf8"
        );
        return /isValidSuccessPayload\(payload\)\)\s*\{[\s\S]{0,2500}writeStoredAnalyzeResult\(/.test(
          analyzeFormSource
        );
      })()
    );
  })();
}

// ── structural checks: submission flow, storage usage, no leaked internals ─

function testStructural() {
  const analyzeFormSource = readFileSync(
    "app/competitor-scripts/analyze/analyze-input-form.tsx",
    "utf8"
  );
  const storageModuleSource = readFileSync(
    "lib/competitor-scripts/analyze-result-storage.ts",
    "utf8"
  );
  const resultsContentSource = readFileSync(
    "app/competitor-scripts/analyze/results/analyze-results-content.tsx",
    "utf8"
  );
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const compareFormSource = readFileSync(
    "app/competitor-scripts/compare/compare-input-form.tsx",
    "utf8"
  );

  check(
    "on a failed submission, the previously entered URL is never cleared (no setUrl call in the failure branch)",
    !/setError\([^)]*apiErrors[\s\S]{0,200}setUrl\(/.test(analyzeFormSource)
  );

  check(
    "writeStoredAnalyzeResult is only ever called from the validated-success branch, not from the failure branch",
    /isValidSuccessPayload\(payload\)\)\s*\{[\s\S]{0,2500}writeStoredAnalyzeResult\(/.test(
      analyzeFormSource
    )
  );

  check(
    "the storage module never imports the server-only Supadata provider",
    !storageModuleSource.includes("supadata-provider")
  );

  check(
    "the storage module reuses the server transcript normalizer's bounds rather than redefining its own limits",
    storageModuleSource.includes(
      '"@/lib/competitor-scripts/transcript/normalize"'
    ) &&
      storageModuleSource.includes("MAX_SEGMENTS") &&
      storageModuleSource.includes("MAX_SEGMENT_TEXT_LENGTH") &&
      storageModuleSource.includes("MAX_TRANSCRIPT_TEXT_LENGTH")
  );

  check(
    "the storage module reuses the real validateCompetitorScriptAnalysis rather than a weaker duplicate validator",
    storageModuleSource.includes(
      '"@/lib/competitor-scripts/analysis/validate"'
    ) && storageModuleSource.includes("validateCompetitorScriptAnalysis(")
  );

  check(
    "the analyze form also re-validates analysis via the real validator before storing it (not a bare cast)",
    analyzeFormSource.includes("validateCompetitorScriptAnalysis(") &&
      !/as\s+CompetitorScriptAnalysis/.test(analyzeFormSource)
  );

  check(
    "AnalyzeResultsContent starts in a loading state (avoids a server/client hydration mismatch, since sessionStorage is only readable after mount)",
    /useState<ContentState>\(\{\s*status:\s*"loading"\s*\}\)/.test(
      resultsContentSource
    )
  );

  check(
    "AnalyzeResultsContent reads sessionStorage inside a mount-only effect (empty dependency array), not during render",
    /useEffect\(\(\)\s*=>\s*\{[\s\S]{0,500}readStoredAnalyzeResult\(\)[\s\S]{0,300}\},\s*\[\]\)/.test(
      resultsContentSource
    )
  );

  check(
    "the sessionStorage read is deferred via a cleaned-up zero-delay timer (matching the repo's react-hooks/set-state-in-effect-safe convention), not a fake multi-stage delay",
    /window\.setTimeout\([\s\S]{0,300}\},\s*0\)/.test(resultsContentSource) &&
      /window\.clearTimeout\(timer\)/.test(resultsContentSource)
  );

  check(
    "real analysis/score/breakdown/summary components are only rendered in the 'ready' branch — the 'missing' branch renders none of them",
    (() => {
      const missingBranchMatch = resultsContentSource.match(
        /state\.status === "missing"\) \{([\s\S]*?)\n {2}\}/
      );
      if (!missingBranchMatch) return false;
      const missingBranch = missingBranchMatch[1];
      return (
        !missingBranch.includes("<ScoreOverview") &&
        !missingBranch.includes("<MainTakeaway") &&
        !missingBranch.includes("<ScriptBreakdown") &&
        !missingBranch.includes("<ResultsSummary")
      );
    })()
  );

  check(
    "the transcript section renders segment/full text via plain JSX expressions, never through a raw-HTML injection prop",
    /\{data\.text\}/.test(transcriptSectionSource) &&
      !transcriptSectionSource.includes("dangerouslySetInnerHTML")
  );

  check(
    "the new/changed frontend wiring files never import the openai package or call it directly (comments explaining that constraint, e.g. in analyze-result-storage.ts's own header, are fine)",
    ![
      analyzeFormSource,
      storageModuleSource,
      resultsContentSource,
      transcriptSectionSource,
    ].some((source) => /openai/i.test(stripComments(source)))
  );

  check(
    "no Supabase reference exists anywhere in the new/changed frontend wiring files",
    ![
      analyzeFormSource,
      storageModuleSource,
      resultsContentSource,
      transcriptSectionSource,
    ].some((source) => /supabase/i.test(source))
  );

  check(
    "the Compare feature was not touched by this PR's storage/API wiring — it references neither the analyze API route nor the new storage module",
    !compareFormSource.includes("/api/competitor-scripts/analyze") &&
      !compareFormSource.includes("analyze-result-storage")
  );

  const packageJson = readFileSync("package.json", "utf8");
  check(
    "no new dependency was added to package.json for this frontend wiring (no zod/uuid/axios/swr/react-query introduced)",
    !/"zod"|"uuid"|"axios"|"swr"|"react-query"/.test(packageJson)
  );
}

// ── visual-polish round: real video embed, density, progressive disclosure ─

function testVisualPolishRound() {
  const embedSource = readFileSync(
    "app/competitor-scripts/analyze/results/youtube-embed.tsx",
    "utf8"
  );
  const resultsSummarySource = readFileSync(
    "app/competitor-scripts/analyze/results/results-summary.tsx",
    "utf8"
  );
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const analyzeApiRouteSource = readFileSync(
    "app/api/competitor-scripts/analyze/route.ts",
    "utf8"
  );
  const compareFormSource = readFileSync(
    "app/competitor-scripts/compare/compare-input-form.tsx",
    "utf8"
  );
  const enSummary = getMessages("en").competitorScripts.analyzeResults.summary;
  const ruSummary = getMessages("ru").competitorScripts.analyzeResults.summary;
  const enTranscript =
    getMessages("en").competitorScripts.analyzeResults.transcript;
  const ruTranscript =
    getMessages("ru").competitorScripts.analyzeResults.transcript;

  check(
    "the iframe src is built strictly from the videoId prop, never from canonicalUrl or any other field",
    /src=\{`https:\/\/www\.youtube\.com\/embed\/\$\{videoId\}`\}/.test(
      embedSource
    ) && !embedSource.includes("canonicalUrl")
  );

  check(
    "the embed re-validates videoId shape itself (defense in depth) before constructing the URL",
    embedSource.includes("isValidYouTubeVideoId(videoId)")
  );

  check(
    "the embed host and path are a fixed literal (youtube.com/embed/), not derived from any arbitrary/dynamic base",
    /https:\/\/www\.youtube\.com\/embed\//.test(embedSource)
  );

  check(
    "the embed URL carries no query string at all — no autoplay, no mute, no custom params (YouTube's own safe defaults apply)",
    !/embed\/\$\{videoId\}[^`]*\?/.test(embedSource) &&
      !/autoplay|[^a-z]mute[^a-z]/i.test(embedSource)
  );

  check(
    "the embed frame uses a 9:16 aspect ratio",
    /aspectRatio:\s*["']9 \/ 16["']/.test(embedSource)
  );

  check(
    "the embed allows fullscreen and has a meaningful (non-empty, localized) title prop wired through",
    embedSource.includes("allowFullScreen") &&
      embedSource.includes("title={title}") &&
      resultsSummarySource.includes("title={summary.embedTitle}") &&
      enSummary.embedTitle.length > 0 &&
      ruSummary.embedTitle.length > 0
  );

  check(
    "the embed is lazy-loaded",
    /loading="lazy"/.test(embedSource)
  );

  check(
    "ResultsSummary renders the real video via YouTubeEmbed, not a placeholder icon/thumbnail",
    resultsSummarySource.includes("<YouTubeEmbed") &&
      !resultsSummarySource.includes("PlayCircle")
  );

  check(
    "the submitted-video card's duration label reads 'transcript duration', never 'video duration', in both locales",
    /transcript duration/i.test(enSummary.durationLabel) &&
      !/video duration/i.test(enSummary.durationLabel) &&
      /транскрипта/i.test(ruSummary.durationLabel)
  );

  check(
    "the transcript section's duration label also reads 'transcript duration', consistent with the summary card",
    /transcript duration/i.test(enTranscript.durationLabel) &&
      /транскрипта/i.test(ruTranscript.durationLabel)
  );

  check(
    "the summary copy never introduces fabricated engagement/metadata keys (views/likes/comments/channel/subscribers/uploadDate/publishedAt)",
    !/views|likes|comments|channel|subscribers|uploadDate|publishedAt/i.test(
      Object.keys(enSummary).join(" ")
    )
  );

  check(
    "ResultsSummary links out to the real, already-validated canonical URL via a safe target=_blank + rel=noopener noreferrer anchor",
    /href=\{data\.canonicalUrl\}/.test(resultsSummarySource) &&
      resultsSummarySource.includes('target="_blank"') &&
      resultsSummarySource.includes('rel="noopener noreferrer"')
  );

  check(
    "the timestamped segment list is initially limited to a small preview count (5-8) rather than rendering everything at once",
    (() => {
      const match = transcriptSectionSource.match(
        /SEGMENT_PREVIEW_COUNT = (\d+)/
      );
      const count = match ? Number(match[1]) : NaN;
      return count >= 5 && count <= 8;
    })() &&
      transcriptSectionSource.includes(
        "data.segments.slice(0, SEGMENT_PREVIEW_COUNT)"
      )
  );

  check(
    "'Show all segments' expands the list and 'Show fewer' collapses it back, via real toggled state — not two separate static lists",
    /setShowAllSegments\(\(current\)\s*=>\s*!current\)/.test(
      transcriptSectionSource
    ) &&
      transcriptSectionSource.includes(
        "showAllSegments ? copy.showFewerSegments : copy.showAllSegments"
      )
  );

  check(
    "the segment expand/collapse control is a real, keyboard-accessible button with aria-expanded reflecting its state",
    /<button\s+type="button"[\s\S]{0,120}aria-expanded=\{showAllSegments\}/.test(
      transcriptSectionSource
    )
  );

  check(
    "the full transcript text is never gated behind the segment expand/collapse state (only the timestamped list is)",
    !/showAllSegments[\s\S]{0,80}data\.text/.test(transcriptSectionSource)
  );

  check(
    "EN/RU expose matching show-all/show-fewer segment copy, non-empty in both locales",
    enTranscript.showAllSegments.length > 0 &&
      enTranscript.showFewerSegments.length > 0 &&
      ruTranscript.showAllSegments.length > 0 &&
      ruTranscript.showFewerSegments.length > 0
  );

  check(
    "no dangerouslySetInnerHTML was introduced by the visual-polish round (transcript/embed remain plain React text/attributes)",
    !embedSource.includes("dangerouslySetInnerHTML") &&
      !resultsSummarySource.includes("dangerouslySetInnerHTML") &&
      !transcriptSectionSource.includes("dangerouslySetInnerHTML")
  );

  check(
    "the illustrative 'real transcript' / 'from your submitted video' style labeling still exists on the transcript section",
    transcriptSectionSource.includes("{copy.realDataLabel}") &&
      /from your submitted video/i.test(enTranscript.sectionEyebrow)
  );

  check(
    "the analyze API route was not touched by this frontend wiring round — it references none of the results components",
    !analyzeApiRouteSource.includes("youtube-embed") &&
      !analyzeApiRouteSource.includes("results-summary") &&
      !analyzeApiRouteSource.includes("transcript-section") &&
      !analyzeApiRouteSource.includes("score-overview")
  );

  check(
    "Compare still does not reference the YouTube embed or the results feature",
    !compareFormSource.includes("youtube-embed") &&
      !compareFormSource.includes("results-summary") &&
      !compareFormSource.includes("YouTubeEmbed")
  );
}

// ── final polish round: corrected top copy, no fake "Source: Unknown" ────

function testFinalPolishRound() {
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const resultsSummarySource = readFileSync(
    "app/competitor-scripts/analyze/results/results-summary.tsx",
    "utf8"
  );
  const enResults = getMessages("en").competitorScripts.analyzeResults;
  const ruResults = getMessages("ru").competitorScripts.analyzeResults;

  check(
    "the top subtitle no longer claims scores/insights are preview/example data — analysis is real now",
    !/preview|example/i.test(enResults.description)
  );

  check(
    "the generation ('Source') transcript stat is only ever added to the stats array when isAutoGenerated is known — never a hardcoded 'Unknown' fallback entry",
    transcriptSectionSource.includes(
      "...(data.isAutoGenerated !== null"
    ) && !transcriptSectionSource.includes("unknownGenerationLabel")
  );

  check(
    "the transcript stats grid degrades to 3 columns when the generation stat is omitted, instead of leaving a visibly empty 4th slot",
    transcriptSectionSource.includes('stats.length >= 4 ? "sm:grid-cols-4"') &&
      transcriptSectionSource.includes('"sm:grid-cols-3"')
  );

  check(
    "the raw canonical URL is no longer rendered as visible text on the submitted-video card — only the 'Open on YouTube' action link remains, with the URL preserved for accessibility via aria-label",
    !/<p[^>]*>[\s\S]{0,80}canonicalUrl/.test(resultsSummarySource) &&
      resultsSummarySource.includes(
        "aria-label={`${summary.openOnYouTube}: ${data.canonicalUrl}`}"
      )
  );

  check(
    "canonicalUrl itself is still read from the stored result and used (for the link + accessible name) — it was only removed from permanent visible display, never dropped from the data flow",
    resultsSummarySource.includes("data.canonicalUrl")
  );

  check(
    "the metadata column next to the real video is width-capped rather than stretching to fill the whole card (flex-1 removed)",
    resultsSummarySource.includes("max-w-[300px]") &&
      !resultsSummarySource.includes("flex-1")
  );

  check(
    "the 9:16 video column width was not touched by this polish round",
    resultsSummarySource.includes("max-w-[200px] shrink-0 sm:w-[200px]")
  );

  check(
    "the segment expand/collapse control remains a real, keyboard-accessible button with aria-expanded and the same 6-segment preview logic",
    transcriptSectionSource.includes('<button\n              type="button"') &&
      transcriptSectionSource.includes("aria-expanded={showAllSegments}") &&
      transcriptSectionSource.includes("SEGMENT_PREVIEW_COUNT = 6")
  );

  check(
    "EN/RU still expose matching, non-empty top subtitle copy after the rewrite, and it differs between locales",
    enResults.description.length > 0 &&
      ruResults.description.length > 0 &&
      enResults.description !== ruResults.description
  );
}

// ── PR10D: real analysis rendering wiring ──────────────────────────────

function testRealAnalysisRendering() {
  const resultsContentSource = readFileSync(
    "app/competitor-scripts/analyze/results/analyze-results-content.tsx",
    "utf8"
  );
  const scoreOverviewSource = readFileSync(
    "app/competitor-scripts/analyze/results/score-overview.tsx",
    "utf8"
  );
  const whyScoresSource = readFileSync(
    "app/competitor-scripts/analyze/results/why-scores-section.tsx",
    "utf8"
  );
  const mainTakeawaySource = readFileSync(
    "app/competitor-scripts/analyze/results/main-takeaway.tsx",
    "utf8"
  );
  const scriptBreakdownSource = readFileSync(
    "app/competitor-scripts/analyze/results/script-breakdown.tsx",
    "utf8"
  );
  const strengthsSource = readFileSync(
    "app/competitor-scripts/analyze/results/strengths-section.tsx",
    "utf8"
  );
  const weaknessesSource = readFileSync(
    "app/competitor-scripts/analyze/results/weaknesses-section.tsx",
    "utf8"
  );
  const risksSource = readFileSync(
    "app/competitor-scripts/analyze/results/risks-section.tsx",
    "utf8"
  );
  const lessonsSource = readFileSync(
    "app/competitor-scripts/analyze/results/lessons-section.tsx",
    "utf8"
  );
  const cautionSource = readFileSync(
    "app/competitor-scripts/analyze/results/caution-section.tsx",
    "utf8"
  );
  const unavailableSource = readFileSync(
    "app/competitor-scripts/analyze/results/analysis-unavailable-section.tsx",
    "utf8"
  );

  // 1. Score mapping, especially momentumScore -> Retention
  check(
    "ScoreOverview maps Retention to data.momentumScore, never a renamed field",
    scoreOverviewSource.includes("scores.retention") &&
      scoreOverviewSource.includes("data.momentumScore") &&
      !scoreOverviewSource.includes("actualRetention")
  );

  check(
    "ScoreOverview no longer renders any static example score value",
    !/value:\s*\d{1,3},/.test(scoreOverviewSource) &&
      !scoreOverviewSource.includes("example score")
  );

  // 2. Verdict rendered as-is, not re-derived
  check(
    "MainTakeaway renders the real verdict via a lookup table, never re-derives it (no deriveAnalysisVerdict import)",
    mainTakeawaySource.includes("verdictCopy[verdict]") &&
      !stripComments(mainTakeawaySource).includes("deriveAnalysisVerdict")
  );

  check(
    "MainTakeaway renders the real mainTakeaway string, not a static example",
    mainTakeawaySource.includes("{mainTakeaway}") &&
      !mainTakeawaySource.includes("opening earns attention quickly")
  );

  // 3. scoreReasons mapped by `.score` key, not array order
  check(
    "WhyScoresSection maps each scoreReason by its own `.score` field via a lookup table, never by array index/order",
    whyScoresSource.includes("SCORE_LABEL_KEY[reason.score]") &&
      whyScoresSource.includes("reasons.map(") &&
      !whyScoresSource.includes("reasons[0]") &&
      !whyScoresSource.includes("reasons[1]")
  );

  check(
    "the score-label lookup table covers exactly the 4 real score keys, mapping momentumScore to the retention label",
    /overallScore:\s*"overall"/.test(whyScoresSource) &&
      /hookScore:\s*"hook"/.test(whyScoresSource) &&
      /momentumScore:\s*"retention"/.test(whyScoresSource) &&
      /structureScore:\s*"structure"/.test(whyScoresSource)
  );

  // 4. Structure beats: real content, localized labels, verbatim evidence
  check(
    "ScriptBreakdown renders real structure beats and localizes only the beat label, never translating/rewriting the evidence excerpt",
    scriptBreakdownSource.includes("beats.map(") &&
      scriptBreakdownSource.includes("structureCopy.beatLabels[beat.label]") &&
      scriptBreakdownSource.includes("{beat.evidence.excerpt}")
  );

  check(
    "ScriptBreakdown shows a timestamp only when real evidence.startMs is present, never a fabricated one",
    scriptBreakdownSource.includes("beat.evidence.startMs !== null") &&
      scriptBreakdownSource.includes("formatTimestampMs(beat.evidence.startMs)")
  );

  // 5. Strengths/weaknesses/risks/lessons/caution: real data, no hardcoded counts
  check(
    "StrengthsSection renders items.map with no hardcoded count and no static example items array",
    strengthsSource.includes("items.map(") && !/items:\s*\[/.test(strengthsSource)
  );

  check(
    "WeaknessesSection renders a clean empty state when items.length === 0, and severity badges from real data",
    weaknessesSource.includes("items.length === 0") &&
      weaknessesSource.includes("weaknesses.emptyState") &&
      weaknessesSource.includes("severity[item.severity]")
  );

  check(
    "RisksSection renders a clean empty state when items.length === 0, and its rendered JSX never asserts measured viewer retention (comments explaining that constraint are fine)",
    risksSource.includes("items.length === 0") &&
      risksSource.includes("risks.emptyState") &&
      !/\bmeasured\b|\bactual retention\b/i.test(stripComments(risksSource))
  );

  check(
    "LessonsSection renders transferable principle+application text; its rendered JSX never says 'copy this exact script' (comments explaining that constraint are fine)",
    lessonsSource.includes("item.principle") &&
      lessonsSource.includes("item.application") &&
      !/copy this (exact )?script/i.test(stripComments(lessonsSource))
  );

  check(
    "CautionSection renders a clean empty state when items.length === 0, and only shows evidence when non-null",
    cautionSource.includes("items.length === 0") &&
      cautionSource.includes("caution.emptyState") &&
      cautionSource.includes("item.evidence &&")
  );

  // 6. Evidence rendering safety across every section that shows it
  check(
    "no results section uses dangerouslySetInnerHTML anywhere",
    ![
      scriptBreakdownSource,
      strengthsSource,
      weaknessesSource,
      risksSource,
      lessonsSource,
      cautionSource,
      mainTakeawaySource,
      scoreOverviewSource,
      whyScoresSource,
    ].some((source) => source.includes("dangerouslySetInnerHTML"))
  );

  // 7. Degraded/unavailable states
  check(
    "AnalysisUnavailableSection covers all 4 safe reasons, and its rendered JSX/logic never mentions internal implementation details (comments discussing that constraint are fine)",
    unavailableSource.includes("transcript_too_long_for_analysis") &&
      unavailableSource.includes("analysis_invalid_response") &&
      unavailableSource.includes("analysis_unavailable") &&
      unavailableSource.includes('"legacy"') &&
      !/openai|api.?key|json schema|validator/i.test(
        stripComments(unavailableSource)
      )
  );

  check(
    "AnalyzeResultsContent renders AnalysisUnavailableSection instead of real analysis cards whenever analysis is null (degraded or legacy), and video/transcript remain outside that branch",
    resultsContentSource.includes("<AnalysisUnavailableSection") &&
      resultsContentSource.indexOf("<ResultsSummary") <
        resultsContentSource.indexOf("unavailableReason !== null") &&
      resultsContentSource.indexOf("<TranscriptSection") <
        resultsContentSource.indexOf("unavailableReason !== null")
  );

  check(
    "AnalyzeResultsContent derives the unavailable reason from analysis/isLegacy/analysisError, never trusts a separately-stored status string",
    resultsContentSource.includes("resolveUnavailableReason") &&
      resultsContentSource.includes("result.isLegacy") &&
      resultsContentSource.includes("result.analysisError") &&
      !resultsContentSource.includes("result.status")
  );

  check(
    "no static Example Analysis Preview framing remains anywhere in the real results rendering",
    ![
      resultsContentSource,
      scoreOverviewSource,
      whyScoresSource,
      mainTakeawaySource,
      scriptBreakdownSource,
      strengthsSource,
      weaknessesSource,
      risksSource,
      lessonsSource,
      cautionSource,
    ].some((source) => /example analysis preview/i.test(source))
  );

  check(
    "no fake performance metadata (views/likes/comments/watch time/CTR) is introduced anywhere in the new analysis section components",
    ![
      scoreOverviewSource,
      whyScoresSource,
      mainTakeawaySource,
      scriptBreakdownSource,
      strengthsSource,
      weaknessesSource,
      risksSource,
      lessonsSource,
      cautionSource,
    ].some((source) => /\bviews?\b|\blikes?\b|\bwatch time\b|\bCTR\b/i.test(source))
  );
}

// ── PR10D: locale sent to the API, matching current app locale ─────────

function testLocaleSending() {
  const analyzeFormSource = readFileSync(
    "app/competitor-scripts/analyze/analyze-input-form.tsx",
    "utf8"
  );

  check(
    "the form reads the current app locale via the existing useLocale hook, no new locale system introduced",
    analyzeFormSource.includes('from "../../locale-provider"') &&
      analyzeFormSource.includes("useLocale()")
  );

  check(
    "the requested analysis locale is derived from the app locale via a local en/ru-only mapping (never sends an unsupported locale, never a new shared module)",
    analyzeFormSource.includes("toAnalysisLocale(appLocale)") &&
      /function toAnalysisLocale\(locale: string\): AnalysisLocale \{\s*\n\s*return locale === "ru" \? "ru" : "en";/.test(
        analyzeFormSource
      )
  );

  check(
    "the request body sends both url and the requested locale",
    /JSON\.stringify\(\{\s*url:\s*trimmed,\s*locale:\s*requestedLocale\s*\}\)/.test(
      analyzeFormSource
    )
  );

  check(
    "requestedLocale is computed from the app locale before the fetch call is even made — structurally impossible to depend on transcript data, which doesn't exist yet at that point",
    analyzeFormSource.indexOf("toAnalysisLocale(appLocale)") <
      analyzeFormSource.indexOf('fetch("/api/competitor-scripts/analyze"')
  );

  check(
    "toAnalysisLocale's own implementation takes only a locale string, never a transcript or payload argument",
    /function toAnalysisLocale\(locale: string\): AnalysisLocale/.test(
      analyzeFormSource
    )
  );
}

async function main() {
  testValidator();
  await testStorageRoundTrip();
  await testApiResponseValidation();
  testStructural();
  testVisualPolishRound();
  testFinalPolishRound();
  testRealAnalysisRendering();
  testLocaleSending();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log(
      "\nResult: all Competitor Scripts Analyze Frontend tests passed."
    );
  }
}

void main();
