import { readFileSync } from "node:fs";

import type { NormalizedTranscript } from "../lib/competitor-scripts/transcript/types";
import type { AnalysisLocale } from "../lib/competitor-scripts/analysis/types";
import {
  COMPETITOR_ANALYSIS_MAX_OUTPUT_TOKENS,
  COMPETITOR_ANALYSIS_MODEL,
  COMPETITOR_ANALYSIS_REASONING_EFFORT,
  COMPETITOR_ANALYSIS_TIMEOUT_MS,
  runCompetitorScriptAnalysis,
  type CompetitorAnalysisModelCaller,
} from "../lib/competitor-scripts/analysis/provider";
import { buildSystemPrompt } from "../lib/competitor-scripts/analysis/prompt";
import { COMPETITOR_ANALYSIS_JSON_SCHEMA } from "../lib/competitor-scripts/analysis/json-schema";
import {
  MAX_ANALYSIS_TRANSCRIPT_CHARACTERS,
  MAX_CAUTION_ITEMS,
  MAX_MAIN_TAKEAWAY_LENGTH,
  MAX_STRUCTURE_BEATS,
  MIN_CAUTION_ITEMS,
  MIN_STRUCTURE_BEATS,
  REQUIRED_SCORE_REASONS,
} from "../lib/competitor-scripts/analysis/constants";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Analysis Provider Tests\n");

// ── Fixture transcript (same shape as the foundation test fixture) ───────

const SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about it.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  { text: "But there's a catch most people miss.", startMs: 9000, durationMs: 3000 },
  { text: "Once you see it, you can't unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];

const TRANSCRIPT: NormalizedTranscript = {
  videoId: "dQw4w9WgXcQ",
  languageCode: "en",
  isAutoGenerated: true,
  segments: SEGMENTS,
  text: SEGMENTS.map((segment) => segment.text).join(" "),
  durationMs: 18000,
};

function padTranscript(targetLength: number): NormalizedTranscript {
  return { ...TRANSCRIPT, text: TRANSCRIPT.text.padEnd(targetLength, ".") };
}

// ── Valid candidate builders ───────────────────────────────────────────────

function makeValidCandidate(locale: AnalysisLocale): Record<string, unknown> {
  const en = {
    mainTakeaway:
      "This script opens with a concrete cost-based hook and closes with a direct, actionable call to action, giving it a strong overall structure.",
    scoreDrivers: {
      overallScore: "The concrete hook and clear structure combine into a strong overall script.",
      hookScore: "The opening names a specific cost immediately, creating strong stakes.",
      structureScore: "The script moves cleanly from hook to payoff without meandering.",
      momentumScore: "Pacing stays brisk with no dead stretches between beats.",
    },
    beat1Purpose: "Opens with a direct problem-cost claim.",
    beat1Analysis: "Grabs attention by naming a concrete cost immediately.",
    beat2Purpose: "Wraps with a direct call to action.",
    beat2Analysis: "Ends with a clear, actionable invitation to apply the technique.",
    strengthWhyItWorks: "Naming a specific cost up front creates immediate stakes for the viewer.",
    lesson1Application:
      "Open your own script by naming a specific cost of inaction to create immediate stakes.",
    lesson2Application:
      "End your script with an explicit, simple action the viewer can take right away.",
  };

  const ru = {
    mainTakeaway:
      "Сценарий начинается с конкретного крючка о цене бездействия и завершается прямым призывом к действию, что даёт сильную общую структуру.",
    scoreDrivers: {
      overallScore: "Конкретный крючок и чёткая структура вместе дают сильный общий результат.",
      hookScore: "Открытие сразу называет конкретную цену, создавая сильную ставку для зрителя.",
      structureScore: "Сценарий чисто движется от крючка к развязке без отступлений.",
      momentumScore: "Темп остаётся живым без провисаний между блоками.",
    },
    beat1Purpose: "Открывает прямым заявлением о цене проблемы.",
    beat1Analysis: "Захватывает внимание, сразу называя конкретную цену.",
    beat2Purpose: "Завершает прямым призывом к действию.",
    beat2Analysis: "Заканчивается ясным и applicable приглашением применить приём.",
    strengthWhyItWorks: "Называние конкретной цены сразу создаёт немедленную ставку для зрителя.",
    lesson1Application:
      "Открывайте свой сценарий, называя конкретную цену бездействия, чтобы сразу создать ставку.",
    lesson2Application:
      "Завершайте сценарий явным и простым действием, которое зритель может выполнить сразу.",
  };

  const copy = locale === "en" ? en : ru;

  return {
    schemaVersion: 1,
    locale,
    verdict: "strong",
    scores: {
      overallScore: 80,
      hookScore: 80,
      structureScore: 78,
      momentumScore: 75,
    },
    mainTakeaway: copy.mainTakeaway,
    scoreReasons: [
      { score: "overallScore", driver: copy.scoreDrivers.overallScore },
      { score: "hookScore", driver: copy.scoreDrivers.hookScore },
      { score: "structureScore", driver: copy.scoreDrivers.structureScore },
      { score: "momentumScore", driver: copy.scoreDrivers.momentumScore },
    ],
    structure: [
      {
        label: "hook",
        evidence: {
          excerpt: "Wait, this one mistake is costing you views.",
          startMs: 0,
          endMs: 3000,
        },
        purpose: copy.beat1Purpose,
        analysis: copy.beat1Analysis,
      },
      {
        label: "payoff",
        evidence: {
          excerpt: "Try this on your next video.",
          startMs: 15000,
          endMs: 18000,
        },
        purpose: copy.beat2Purpose,
        analysis: copy.beat2Analysis,
      },
    ],
    strengths: [
      {
        title: "Direct cost-based hook",
        evidence: {
          excerpt: "Wait, this one mistake is costing you views.",
          startMs: 0,
          endMs: 3000,
        },
        whyItWorks: copy.strengthWhyItWorks,
      },
    ],
    weaknesses: [],
    retentionRisks: [],
    actionableLessons: [
      {
        principle: "Lead with a concrete cost",
        sourceEvidence: {
          excerpt: "Wait, this one mistake is costing you views.",
          startMs: 0,
          endMs: 3000,
        },
        application: copy.lesson1Application,
      },
      {
        principle: "Close with a direct next step",
        sourceEvidence: {
          excerpt: "Try this on your next video.",
          startMs: 15000,
          endMs: 18000,
        },
        application: copy.lesson2Application,
      },
    ],
    caution: [],
  };
}

function cloneCandidate(locale: AnalysisLocale = "en"): Record<string, unknown> {
  return JSON.parse(JSON.stringify(makeValidCandidate(locale)));
}

// ── Scripted fake model caller (zero real OpenAI calls) ───────────────────

type CallerStep = { kind: "transient" } | { kind: "raw"; raw: string };

function createStepCaller(steps: CallerStep[]): {
  caller: CompetitorAnalysisModelCaller;
  calls: { systemPrompt: string; userPrompt: string }[];
} {
  const calls: { systemPrompt: string; userPrompt: string }[] = [];
  let index = 0;

  const caller: CompetitorAnalysisModelCaller = async ({ systemPrompt, userPrompt }) => {
    calls.push({ systemPrompt, userPrompt });
    const step = steps[index];
    index += 1;

    if (!step) {
      throw new Error("Test caller invoked a third time — this must never happen.");
    }

    if (step.kind === "transient") {
      throw { status: 500 };
    }

    return { raw: step.raw, modelUsed: COMPETITOR_ANALYSIS_MODEL };
  };

  return { caller, calls };
}

function validRaw(locale: AnalysisLocale = "en"): string {
  return JSON.stringify(makeValidCandidate(locale));
}

// ── Tests ────────────────────────────────────────────────────────────────

async function testValidFirstAttempt(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw() }]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check("valid first attempt succeeds with exactly 1 model call", calls.length === 1);
  check("valid first attempt returns ok:true", result.ok === true);
  check(
    "successful output passes the real PR10A validator (verdict derived correctly)",
    result.ok === true && result.analysis.verdict === "strong"
  );
}

async function testTransientThenSuccess(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "raw", raw: validRaw() }]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient failure then success uses exactly 2 calls", calls.length === 2);
  check("transient failure then success returns ok:true", result.ok === true);
}

async function testInvalidThenSuccess(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: "not valid json {{{" },
    { kind: "raw", raw: validRaw() },
  ]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("malformed JSON then success uses exactly 2 calls", calls.length === 2);
  check("malformed JSON then success returns ok:true", result.ok === true);
}

async function testValidatorRejectionThenSuccess(): Promise<void> {
  const bad = cloneCandidate();
  bad.verdict = "weak"; // does not match the deterministically derived verdict ("strong")

  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify(bad) },
    { kind: "raw", raw: validRaw() },
  ]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("validator-rejected output then success uses exactly 2 calls", calls.length === 2);
  check("validator-rejected output then success returns ok:true", result.ok === true);
  check(
    "the retry's user prompt carries one corrective instruction referencing the failure",
    calls[1].userPrompt.includes("IMPORTANT CORRECTION FOR THIS ATTEMPT") &&
      calls[1].userPrompt.includes("invalid_verdict")
  );
}

async function testBothInvalidNeverThirdCall(): Promise<void> {
  const bad = cloneCandidate();
  bad.verdict = "weak";

  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify(bad) },
    { kind: "raw", raw: JSON.stringify(bad) },
  ]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("invalid->invalid uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "invalid->invalid returns the typed analysis_invalid_response failure",
    result.ok === false && result.code === "analysis_invalid_response"
  );
  check(
    "the public failure result carries only { ok, code } — no reason/detail field that could leak the internal validator code or the model's rejected value",
    !result.ok && Object.keys(result).sort().join(",") === "code,ok"
  );
}

async function testTransientThenInvalid(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "transient" },
    { kind: "raw", raw: "still not json" },
  ]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient->invalid uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "transient->invalid returns analysis_invalid_response",
    result.ok === false && result.code === "analysis_invalid_response"
  );
}

async function testInvalidThenTransient(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: "not json" },
    { kind: "transient" },
  ]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("invalid->transient uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "invalid->transient returns analysis_unavailable",
    result.ok === false && result.code === "analysis_unavailable"
  );
}

async function testTransientThenTransient(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "transient" }]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient->transient uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "transient->transient returns the typed analysis_unavailable failure",
    result.ok === false && result.code === "analysis_unavailable"
  );
}

async function testRetryPromptDiscipline(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "raw", raw: validRaw() }]);
  await runCompetitorScriptAnalysis({ transcript: TRANSCRIPT, locale: "en", modelCaller: caller });

  check(
    "system/instruction prompt is byte-identical across attempt 1 and attempt 2",
    calls[0].systemPrompt === calls[1].systemPrompt
  );
  check(
    "buildSystemPrompt() is a pure function of no arguments (identical output every call)",
    buildSystemPrompt() === buildSystemPrompt()
  );

  const { caller: rejectCaller, calls: rejectCalls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify({ ...cloneCandidate(), verdict: "weak" }) },
    { kind: "raw", raw: validRaw() },
  ]);
  await runCompetitorScriptAnalysis({ transcript: TRANSCRIPT, locale: "en", modelCaller: rejectCaller });
  check(
    "on a validator-rejection retry, the base user prompt is unchanged and only a corrective instruction is appended",
    rejectCalls[1].userPrompt.startsWith(rejectCalls[0].userPrompt) &&
      rejectCalls[1].userPrompt.length > rejectCalls[0].userPrompt.length
  );
}

async function testModelAndReasoningConstantsUnchanged(): Promise<void> {
  check("model constant is exactly gpt-5.6-luna", COMPETITOR_ANALYSIS_MODEL === "gpt-5.6-luna");
  check("reasoning effort constant is exactly low", COMPETITOR_ANALYSIS_REASONING_EFFORT === "low");

  const providerSource = readFileSync(
    "lib/competitor-scripts/analysis/provider.ts",
    "utf8"
  );
  check(
    "no fallback model (gpt-5.6-sol / gpt-5.6-terra) is referenced anywhere in provider.ts",
    !providerSource.includes("gpt-5.6-sol") && !providerSource.includes("gpt-5.6-terra")
  );
  check(
    "model is a single fixed module-level constant, not selected per attempt",
    providerSource.includes('COMPETITOR_ANALYSIS_MODEL = "gpt-5.6-luna"')
  );
}

async function testOversizedTranscriptRejectedBeforeAnyModelCall(): Promise<void> {
  const oversized = padTranscript(MAX_ANALYSIS_TRANSCRIPT_CHARACTERS + 1);
  const { caller, calls } = createStepCaller([]);
  const result = await runCompetitorScriptAnalysis({
    transcript: oversized,
    locale: "en",
    modelCaller: caller,
  });

  check("oversized transcript (6001 chars) makes zero model calls", calls.length === 0);

  const isExpectedFailure =
    !result.ok &&
    result.code === "transcript_too_long_for_analysis" &&
    result.maxCharacters === MAX_ANALYSIS_TRANSCRIPT_CHARACTERS &&
    result.actualCharacters === MAX_ANALYSIS_TRANSCRIPT_CHARACTERS + 1;

  check(
    "oversized transcript returns the typed transcript_too_long_for_analysis failure",
    isExpectedFailure
  );
  check(
    "the transcript_too_long_for_analysis result is exactly checkAnalysisTranscriptSize's own AnalysisSizeCheckResult shape (reused, not a competing duplicate)",
    !result.ok && Object.keys(result).sort().join(",") === "actualCharacters,code,maxCharacters,ok"
  );
}

async function testExactlyMaxCharactersAllowedThrough(): Promise<void> {
  const boundary = padTranscript(MAX_ANALYSIS_TRANSCRIPT_CHARACTERS);
  const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw() }]);
  const result = await runCompetitorScriptAnalysis({
    transcript: boundary,
    locale: "en",
    modelCaller: caller,
  });

  check(
    "a transcript of exactly the max character count reaches the model (1 call)",
    calls.length === 1
  );
  check("exactly-max-length transcript can still succeed", result.ok === true);
}

async function testRealValidatorRejections(): Promise<void> {
  const cases: { name: string; patch: (c: Record<string, unknown>) => void; code: string }[] = [
    {
      name: "invalid verdict (mismatched with derived verdict)",
      patch: (c) => {
        c.verdict = "weak";
      },
      code: "invalid_verdict",
    },
    {
      name: "inconsistent scores (overallScore far from component mean)",
      patch: (c) => {
        (c.scores as Record<string, number>).overallScore = 10;
      },
      code: "inconsistent_scores",
    },
    {
      name: "unsupported evidence (excerpt not an exact transcript substring)",
      patch: (c) => {
        (c.structure as Array<Record<string, unknown>>)[0].evidence = {
          excerpt: "This phrase does not appear anywhere in the transcript.",
          startMs: 0,
          endMs: 3000,
        };
      },
      code: "invalid_evidence",
    },
    {
      name: "unsupported numeric claim (a number absent from the transcript and ungrounded by timing)",
      patch: (c) => {
        (c.structure as Array<Record<string, unknown>>)[0].analysis =
          "This beat lasts about 47 seconds of screen time.";
      },
      code: "unsupported_numeric_claim",
    },
    {
      name: "unsupported performance claim (an observed-fact viewer behavior claim)",
      patch: (c) => {
        (c.structure as Array<Record<string, unknown>>)[0].analysis =
          "Viewers actually watched through this entire section.";
      },
      code: "unsupported_performance_claim",
    },
  ];

  for (const testCase of cases) {
    const candidate = cloneCandidate();
    testCase.patch(candidate);
    const raw = JSON.stringify(candidate);

    const { caller, calls } = createStepCaller([
      { kind: "raw", raw },
      { kind: "raw", raw },
    ]);
    const result = await runCompetitorScriptAnalysis({
      transcript: TRANSCRIPT,
      locale: "en",
      modelCaller: caller,
    });

    check(
      `real validator rejects: ${testCase.name} (exactly 2 calls, never a 3rd)`,
      calls.length === 2
    );
    check(
      `real validator rejects: ${testCase.name} (typed analysis_invalid_response)`,
      result.ok === false && result.code === "analysis_invalid_response"
    );
  }
}

async function testTimingDerivedNumericClaimIsGrounded(): Promise<void> {
  const candidate = cloneCandidate();
  (candidate.actionableLessons as Array<Record<string, unknown>>)[0].application =
    "Introduce your key turn by roughly the 3000 millisecond mark to keep pace tight.";

  const { caller, calls } = createStepCaller([{ kind: "raw", raw: JSON.stringify(candidate) }]);
  const result = await runCompetitorScriptAnalysis({
    transcript: TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check(
    "a timing-derived numeric claim (3000ms, a real segment boundary) passes provider validation on the first attempt",
    calls.length === 1 && result.ok === true
  );
}

async function testLocales(): Promise<void> {
  for (const locale of ["en", "ru"] as const) {
    const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw(locale) }]);
    const result = await runCompetitorScriptAnalysis({
      transcript: TRANSCRIPT,
      locale,
      modelCaller: caller,
    });

    check(`locale="${locale}" succeeds`, calls.length === 1 && result.ok === true);
    check(
      `locale="${locale}" keeps EvidenceRef.excerpt in the original transcript language/wording`,
      result.ok === true &&
        result.analysis.structure[0].evidence.excerpt === "Wait, this one mistake is costing you views."
    );
  }
}

async function testPromptContent(): Promise<void> {
  const prompt = buildSystemPrompt();

  check(
    "prompt restricts grounding to the transcript only",
    prompt.includes("the only source of truth")
  );
  check(
    "prompt prohibits unsupported performance-data claims (views/retention/etc.)",
    prompt.includes("actual views") && prompt.includes("actual retention")
  );
  check(
    "prompt prohibits visual/camera-work analysis (text-only transcript)",
    prompt.includes("camera work") && prompt.includes("cannot see the video")
  );
  check(
    "prompt encodes the quote-verbatim rule",
    prompt.includes("quotation marks mean verbatim") &&
      prompt.includes("MUST be copied exactly from the transcript")
  );
  check(
    "prompt forbids forcing a question-based hook",
    prompt.includes("Do not force a question-based hook")
  );
  check(
    "prompt explicitly permits zero weaknesses for a strong script",
    prompt.includes("can have zero weaknesses")
  );
  check(
    "prompt distinguishes actionable lessons (transferable) from copying/rewriting the script",
    prompt.includes("not a copy or rewrite of this script's specific words")
  );
}

async function testSchemaAlignsWithConstants(): Promise<void> {
  const schema = COMPETITOR_ANALYSIS_JSON_SCHEMA as {
    properties: {
      mainTakeaway: { maxLength: number };
      scoreReasons: { minItems: number; maxItems: number };
      structure: { minItems: number; maxItems: number };
      caution: { minItems: number; maxItems: number };
    };
  };

  check(
    "schema mainTakeaway.maxLength matches constants.ts (not a duplicated number)",
    schema.properties.mainTakeaway.maxLength === MAX_MAIN_TAKEAWAY_LENGTH
  );
  check(
    "schema scoreReasons array bounds match constants.ts",
    schema.properties.scoreReasons.minItems === REQUIRED_SCORE_REASONS &&
      schema.properties.scoreReasons.maxItems === REQUIRED_SCORE_REASONS
  );
  check(
    "schema structure array bounds match constants.ts",
    schema.properties.structure.minItems === MIN_STRUCTURE_BEATS &&
      schema.properties.structure.maxItems === MAX_STRUCTURE_BEATS
  );
  check(
    "schema caution array bounds match constants.ts",
    schema.properties.caution.minItems === MIN_CAUTION_ITEMS &&
      schema.properties.caution.maxItems === MAX_CAUTION_ITEMS
  );
}

async function testConfigConstants(): Promise<void> {
  check("timeout constant is exactly 30000ms", COMPETITOR_ANALYSIS_TIMEOUT_MS === 30_000);
  check(
    "max output tokens is the calculated 16000, not the bake-off harness's inherited 6000 nor the original under-audited 8000",
    COMPETITOR_ANALYSIS_MAX_OUTPUT_TOKENS === 16_000 &&
      (COMPETITOR_ANALYSIS_MAX_OUTPUT_TOKENS as number) !== 6_000 &&
      (COMPETITOR_ANALYSIS_MAX_OUTPUT_TOKENS as number) !== 8_000
  );
}

async function testNoUnsafeLogging(): Promise<void> {
  const providerSource = readFileSync("lib/competitor-scripts/analysis/provider.ts", "utf8");

  check(
    "provider.ts introduces no console logging at all (nothing to leak a secret/transcript/raw response through)",
    !providerSource.includes("console.log(") &&
      !providerSource.includes("console.error(") &&
      !providerSource.includes("console.warn(")
  );
  const providerCodeOnly = providerSource
    .split("\n")
    .filter((line) => !line.trim().startsWith("//"))
    .join("\n");
  check(
    "provider.ts never reads process.env directly in actual code (API key stays fully dependency-injected — comments mentioning it are fine)",
    !providerCodeOnly.includes("process.env")
  );
}

async function main() {
  await testValidFirstAttempt();
  await testTransientThenSuccess();
  await testInvalidThenSuccess();
  await testValidatorRejectionThenSuccess();
  await testBothInvalidNeverThirdCall();
  await testTransientThenInvalid();
  await testInvalidThenTransient();
  await testTransientThenTransient();
  await testRetryPromptDiscipline();
  await testModelAndReasoningConstantsUnchanged();
  await testOversizedTranscriptRejectedBeforeAnyModelCall();
  await testExactlyMaxCharactersAllowedThrough();
  await testRealValidatorRejections();
  await testTimingDerivedNumericClaimIsGrounded();
  await testLocales();
  await testPromptContent();
  await testSchemaAlignsWithConstants();
  await testConfigConstants();
  await testNoUnsafeLogging();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log("\nResult: all Competitor Scripts Analysis Provider tests passed.");
  }
}

void main();
