import { readFileSync } from "node:fs";
import type {
  TranscriptError,
  TranscriptErrorCode,
  TranscriptProvider,
  TranscriptProviderResult,
} from "../lib/competitor-scripts/transcript/types";
import type { ComparisonLocale } from "../lib/competitor-scripts/comparison/types";
import type { CompetitorComparisonModelCaller } from "../lib/competitor-scripts/comparison/provider";

let failures = 0;

// Captured before testRoute() mocks console.info/error to observe the
// route's own logging — the check() helper must always print through the
// real console, never through a mock that would swallow FAIL output.
const realConsoleLog = console.log;
const realConsoleError = console.error;

function check(name: string, condition: boolean): void {
  if (condition) {
    realConsoleLog(`✅ PASS — ${name}`);
  } else {
    realConsoleError(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Compare API Tests\n");

const STANDARD_ID = "dQw4w9WgXcQ";
const COMPETITOR_URL = `https://www.youtube.com/watch?v=${STANDARD_ID}`;

function jsonRequest(body: unknown, headers?: Record<string, string>): Request {
  return new Request("http://localhost/api/competitor-scripts/compare", {
    method: "POST",
    headers: { "Content-Type": "application/json", ...headers },
    body: typeof body === "string" ? body : JSON.stringify(body),
  });
}

function stubProvider(
  responder: (videoId: string) => TranscriptProviderResult | Promise<TranscriptProviderResult>
): { provider: TranscriptProvider; calls: string[] } {
  const calls: string[] = [];
  const provider: TranscriptProvider = {
    async getTranscript({ videoId }) {
      calls.push(videoId);
      return responder(videoId);
    },
  };
  return { provider, calls };
}

function throwingProvider(): TranscriptProvider {
  return {
    async getTranscript() {
      throw new Error("simulated unexpected provider failure");
    },
  };
}

function makeTranscriptError(code: TranscriptErrorCode): TranscriptError {
  const table: Record<TranscriptErrorCode, string> = {
    transcript_not_found: "not found",
    transcript_disabled: "disabled",
    transcript_unavailable: "unavailable",
    unsupported_language: "unsupported language",
    video_unavailable: "video unavailable",
    provider_rate_limited: "rate limited",
    provider_timeout: "timeout",
    provider_unavailable: "provider unavailable",
    invalid_provider_response: "invalid response",
  };
  return { code, message: table[code], retryable: false };
}

// ── Compare fixtures ─────────────────────────────────────────────────────
// This file intentionally builds its own self-contained fixture copy
// rather than importing it, matching how
// tests/competitor-scripts-comparison-provider.ts keeps its own fixture
// separate from tests/competitor-scripts-comparison-foundation.ts.

const USER_SCRIPT =
  "Everyone thinks a strong hook needs a shocking claim, but that is the mistake. " +
  "I open with a plain observation instead, then explain why it matters in 3 words. " +
  "Most creators rush straight to the payoff before earning it. " +
  "I reveal the answer almost immediately after the setup.";

const COMPETITOR_SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about hooks.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  {
    text: "I hold the tension for four extra lines before I answer the question.",
    startMs: 9000,
    durationMs: 3000,
  },
  { text: "Once you see it, you cannot unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];

const COMPETITOR_TRANSCRIPT = {
  videoId: STANDARD_ID,
  languageCode: "en",
  isAutoGenerated: true,
  segments: COMPETITOR_SEGMENTS,
  text: COMPETITOR_SEGMENTS.map((segment) => segment.text).join(" "),
  durationMs: 18000,
};

function padUserScript(targetLength: number): string {
  return USER_SCRIPT.padEnd(targetLength, ".");
}

function padCompetitorTranscript(targetLength: number): typeof COMPETITOR_TRANSCRIPT {
  return { ...COMPETITOR_TRANSCRIPT, text: COMPETITOR_TRANSCRIPT.text.padEnd(targetLength, ".") };
}

function stubCompareTranscriptProvider(
  overrides: Partial<{
    text: string;
    segments: typeof COMPETITOR_SEGMENTS;
    durationMs: number | null;
  }> = {}
): { provider: TranscriptProvider; calls: string[] } {
  return stubProvider(() => ({
    ok: true,
    transcript: {
      ...COMPETITOR_TRANSCRIPT,
      segments: overrides.segments ?? COMPETITOR_TRANSCRIPT.segments,
      text: overrides.text ?? COMPETITOR_TRANSCRIPT.text,
      durationMs: overrides.durationMs === undefined ? COMPETITOR_TRANSCRIPT.durationMs : overrides.durationMs,
    },
  }));
}

// ── Valid candidate builder (same shape/values proven in
// tests/competitor-scripts-comparison-provider.ts) ──────────────────────

function makeValidCandidate(
  locale: ComparisonLocale,
  cautionCount: 0 | 1 = 1
): Record<string, unknown> {
  const en = {
    headline: "Their opening names a concrete mistake; yours states the premise more gently.",
    mainTakeaway:
      "Adding one short beat before your answer would give your payoff the same clear landing point their script has.",
    hook: {
      conclusion: "Their hook names the mistake immediately, while yours states the premise more gently.",
      userObservation: "Your opening states the premise as a broad claim.",
      competitorObservation: "Their opening names the specific mistake right away.",
    },
    structure: {
      conclusion: "Both scripts move through a comparable number of story beats.",
      userObservation: "Your structure moves from premise to payoff in a few clear steps.",
      competitorObservation: "Their structure also moves through a short, numbered sequence.",
    },
    momentum: {
      conclusion: "Yours moves into the observation slightly faster after the premise.",
      userObservation: "Your script moves directly into the observation without a detour.",
      competitorObservation: "Their script holds an extra beat before moving forward.",
    },
    payoff: {
      conclusion: "Their payoff lands as a distinct beat, while yours arrives without a clear turn.",
      userObservation: "Your answer arrives immediately, without a signal that it has landed.",
      competitorObservation: "Their payoff is set apart by a short beat that signals the reveal.",
    },
    priority1: {
      problem: "Your payoff arrives without a distinct turn that signals it has landed.",
      competitorPrinciple: "Holding a short beat before answering gives the payoff more weight.",
      howToApply: "Add one short beat before your answer that signals the reveal is about to land.",
    },
    priority2: {
      problem: "Your hook states the premise gently instead of naming a concrete mistake up front.",
      competitorPrinciple:
        "Naming a specific mistake in the opening line gives viewers an immediate reason to keep watching.",
      howToApply: "Rewrite your opening line to name the specific mistake instead of describing the general topic.",
    },
    caution: {
      whatNotToCopy: "Copying their exact opening phrasing",
      reason:
        "Their phrasing fits their channel's established tone; using it word for word elsewhere could read as jarring.",
    },
  };

  const ru = {
    headline: "Их сценарий сразу называет конкретную ошибку; ваш мягче формулирует предпосылку.",
    mainTakeaway:
      "Одна короткая пауза перед ответом дала бы вашей развязке такую же чёткую точку, как в их сценарии.",
    hook: {
      conclusion: "Их крючок сразу называет ошибку, а ваш мягче формулирует предпосылку.",
      userObservation: "Ваше открытие формулирует предпосылку как общее утверждение.",
      competitorObservation: "Их открытие сразу называет конкретную ошибку.",
    },
    structure: {
      conclusion: "Оба сценария проходят через сопоставимое число сюжетных блоков.",
      userObservation: "Ваша структура движется от предпосылки к развязке за несколько чётких шагов.",
      competitorObservation: "Их структура тоже движется через короткую пронумерованную последовательность.",
    },
    momentum: {
      conclusion: "Ваш сценарий немного быстрее переходит к наблюдению после предпосылки.",
      userObservation: "Ваш сценарий сразу переходит к наблюдению без отступлений.",
      competitorObservation: "Их сценарий держит дополнительный такт перед тем как двигаться дальше.",
    },
    payoff: {
      conclusion: "Их развязка выделена отдельным тактом, а ваша приходит без чёткого поворота.",
      userObservation: "Ваш ответ приходит сразу, без сигнала о том, что он состоялся.",
      competitorObservation: "Их развязка выделена коротким тактом, который сигнализирует о развязке.",
    },
    priority1: {
      problem: "Ваша развязка приходит без отдельного поворота, который сигнализирует о том, что она состоялась.",
      competitorPrinciple: "Короткая пауза перед ответом придаёт развязке больше веса.",
      howToApply: "Добавьте один короткий такт перед ответом, который сигнализирует о приближении развязки.",
    },
    priority2: {
      problem: "Ваш крючок мягко формулирует предпосылку вместо того чтобы сразу назвать конкретную ошибку.",
      competitorPrinciple:
        "Называние конкретной ошибки в первой строке сразу даёт зрителю причину продолжать смотреть.",
      howToApply: "Перепишите первую строку так, чтобы назвать конкретную ошибку, а не описывать общую тему.",
    },
    caution: {
      whatNotToCopy: "Копирование их точной фразировки открытия",
      reason:
        "Их фразировка соответствует тону их канала; дословное использование в другом месте может звучать неуместно.",
    },
  };

  const copy = locale === "en" ? en : ru;

  const UE_HOOK = "a strong hook needs a shocking claim";
  const UE_STRUCTURE = "Most creators rush straight to the payoff before earning it.";
  const UE_MOMENTUM = "I open with a plain observation instead";
  const UE_PAYOFF = "I reveal the answer almost immediately after the setup.";

  const CE_HOOK = { excerpt: "Here's what everyone gets wrong about hooks.", startMs: 3000, endMs: 6000 };
  const CE_STRUCTURE = { excerpt: "So here is the fix in 3 steps.", startMs: 6000, endMs: 9000 };
  const CE_MOMENTUM = {
    excerpt: "I hold the tension for four extra lines before I answer the question.",
    startMs: 9000,
    endMs: 12000,
  };
  const CE_PAYOFF = { excerpt: "Once you see it, you cannot unsee it.", startMs: 12000, endMs: 15000 };

  function userEvidence(excerpt: string) {
    return { source: "user", excerpt };
  }

  function competitorEvidence(excerpt: string, startMs: number, endMs: number | null) {
    return { source: "competitor", excerpt, startMs, endMs };
  }

  const cautions =
    cautionCount === 0
      ? []
      : [
          {
            whatNotToCopy: copy.caution.whatNotToCopy,
            reason: copy.caution.reason,
            evidence: {
              competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
              user: null,
            },
          },
        ];

  return {
    schemaVersion: 1,
    locale,
    comparisonSummary: { headline: copy.headline, mainTakeaway: copy.mainTakeaway },
    dimensionFindings: [
      {
        dimension: "hook",
        strongerSide: "competitor",
        gap: "meaningful",
        conclusion: copy.hook.conclusion,
        userObservation: copy.hook.userObservation,
        competitorObservation: copy.hook.competitorObservation,
        evidence: {
          user: userEvidence(UE_HOOK),
          competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
        },
      },
      {
        dimension: "structure",
        strongerSide: "similar",
        gap: null,
        conclusion: copy.structure.conclusion,
        userObservation: copy.structure.userObservation,
        competitorObservation: copy.structure.competitorObservation,
        evidence: {
          user: userEvidence(UE_STRUCTURE),
          competitor: competitorEvidence(CE_STRUCTURE.excerpt, CE_STRUCTURE.startMs, CE_STRUCTURE.endMs),
        },
      },
      {
        dimension: "momentum",
        strongerSide: "user",
        gap: "small",
        conclusion: copy.momentum.conclusion,
        userObservation: copy.momentum.userObservation,
        competitorObservation: copy.momentum.competitorObservation,
        evidence: {
          user: userEvidence(UE_MOMENTUM),
          competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs),
        },
      },
      {
        dimension: "payoff_clarity",
        strongerSide: "competitor",
        gap: "large",
        conclusion: copy.payoff.conclusion,
        userObservation: copy.payoff.userObservation,
        competitorObservation: copy.payoff.competitorObservation,
        evidence: {
          user: userEvidence(UE_PAYOFF),
          competitor: competitorEvidence(CE_PAYOFF.excerpt, CE_PAYOFF.startMs, CE_PAYOFF.endMs),
        },
      },
    ],
    priorities: [
      {
        rank: 1,
        problem: copy.priority1.problem,
        competitorPrinciple: copy.priority1.competitorPrinciple,
        howToApply: copy.priority1.howToApply,
        evidence: {
          user: userEvidence(UE_PAYOFF),
          competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs),
        },
      },
      {
        rank: 2,
        problem: copy.priority2.problem,
        competitorPrinciple: copy.priority2.competitorPrinciple,
        howToApply: copy.priority2.howToApply,
        evidence: {
          user: userEvidence(UE_HOOK),
          competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
        },
      },
    ],
    cautions,
  };
}

function validRaw(locale: ComparisonLocale = "en", cautionCount: 0 | 1 = 1): string {
  return JSON.stringify(makeValidCandidate(locale, cautionCount));
}

// ── Scripted fake model caller (zero real OpenAI calls) ───────────────────
// Each element of `steps` is consumed in order; any call beyond the
// scripted steps is itself a test failure signal (an unscripted extra call
// would mean the route is duplicating the provider's own retry).

type ModelCallerStep = "success" | "transient" | "malformed" | { raw: string };

function makeScriptedModelCaller(
  steps: ModelCallerStep[],
  locale: ComparisonLocale = "en",
  cautionCount: 0 | 1 = 1
): { caller: CompetitorComparisonModelCaller; callCount: () => number } {
  let index = 0;
  const caller: CompetitorComparisonModelCaller = async () => {
    const step = steps[index];
    index += 1;

    if (step === "transient") {
      throw { status: 500 };
    }
    if (step === "malformed") {
      return { raw: "not valid json {{{", modelUsed: "gpt-5.6-luna" };
    }
    if (typeof step === "object" && step !== null) {
      return { raw: step.raw, modelUsed: "gpt-5.6-luna" };
    }
    return { raw: validRaw(locale, cautionCount), modelUsed: "gpt-5.6-luna" };
  };
  return { caller, callCount: () => index };
}

function makeCapturingModelCaller(
  locale: ComparisonLocale = "en"
): {
  caller: CompetitorComparisonModelCaller;
  calls: { systemPrompt: string; userPrompt: string }[];
} {
  const calls: { systemPrompt: string; userPrompt: string }[] = [];
  const caller: CompetitorComparisonModelCaller = async ({ systemPrompt, userPrompt }) => {
    calls.push({ systemPrompt, userPrompt });
    return { raw: validRaw(locale), modelUsed: "gpt-5.6-luna" };
  };
  return { caller, calls };
}

async function withOpenAIApiKey<T>(value: string | undefined, fn: () => Promise<T>): Promise<T> {
  const original = process.env.OPENAI_API_KEY;
  if (value === undefined) {
    delete process.env.OPENAI_API_KEY;
  } else {
    process.env.OPENAI_API_KEY = value;
  }
  try {
    return await fn();
  } finally {
    if (original === undefined) {
      delete process.env.OPENAI_API_KEY;
    } else {
      process.env.OPENAI_API_KEY = original;
    }
  }
}

async function withSupadataApiKey<T>(value: string | undefined, fn: () => Promise<T>): Promise<T> {
  const original = process.env.SUPADATA_API_KEY;
  if (value === undefined) {
    delete process.env.SUPADATA_API_KEY;
  } else {
    process.env.SUPADATA_API_KEY = value;
  }
  try {
    return await fn();
  } finally {
    if (original === undefined) {
      delete process.env.SUPADATA_API_KEY;
    } else {
      process.env.SUPADATA_API_KEY = original;
    }
  }
}

async function testRoute() {
  const { POST, runCompetitorScriptsCompare } = await import(
    "../app/api/competitor-scripts/compare/route"
  );

  const originalFetch = globalThis.fetch;
  let fetchCalled = false;
  globalThis.fetch = ((...args: unknown[]) => {
    fetchCalled = true;
    throw new Error(`unexpected network call: ${JSON.stringify(args)}`);
  }) as typeof fetch;

  const originalConsoleInfo = console.info;
  const originalConsoleError = console.error;
  let infoCalls: unknown[][] = [];
  let errorCalls: unknown[][] = [];
  console.info = (...args: unknown[]) => {
    infoCalls.push(args);
  };
  console.error = (...args: unknown[]) => {
    errorCalls.push(args);
  };

  try {
    // ── Request validation: no provider/network call for any of these ──

    fetchCalled = false;
    infoCalls = [];

    const missingScriptResponse = await POST(jsonRequest({ competitorUrl: COMPETITOR_URL }));
    check("missing userScript returns 400", missingScriptResponse.status === 400);
    const missingScriptBody = await missingScriptResponse.json();
    check(
      "missing userScript has code missing_user_script",
      missingScriptBody.ok === false && missingScriptBody.error.code === "missing_user_script"
    );

    const nonStringScriptResponse = await POST(
      jsonRequest({ userScript: 12345, competitorUrl: COMPETITOR_URL })
    );
    check("non-string userScript returns 400", nonStringScriptResponse.status === 400);
    const nonStringScriptBody = await nonStringScriptResponse.json();
    check(
      "non-string userScript has code user_script_not_string",
      nonStringScriptBody.error.code === "user_script_not_string"
    );

    const whitespaceScriptResponse = await POST(
      jsonRequest({ userScript: "   \n\t  ", competitorUrl: COMPETITOR_URL })
    );
    check("whitespace-only userScript returns 400", whitespaceScriptResponse.status === 400);
    const whitespaceScriptBody = await whitespaceScriptResponse.json();
    check(
      "whitespace-only userScript has code empty_user_script",
      whitespaceScriptBody.error.code === "empty_user_script"
    );

    const missingUrlResponse = await POST(jsonRequest({ userScript: USER_SCRIPT }));
    check("missing competitorUrl returns 400", missingUrlResponse.status === 400);
    const missingUrlBody = await missingUrlResponse.json();
    check("missing competitorUrl has code missing_url", missingUrlBody.error.code === "missing_url");

    const nonStringUrlResponse = await POST(
      jsonRequest({ userScript: USER_SCRIPT, competitorUrl: 12345 })
    );
    check("non-string competitorUrl returns 400", nonStringUrlResponse.status === 400);
    const nonStringUrlBody = await nonStringUrlResponse.json();
    check("non-string competitorUrl has code url_not_string", nonStringUrlBody.error.code === "url_not_string");

    const tooLongUrlResponse = await POST(
      jsonRequest({ userScript: USER_SCRIPT, competitorUrl: "https://youtu.be/" + "A".repeat(3000) })
    );
    check("excessively long competitorUrl returns 400", tooLongUrlResponse.status === 400);
    const tooLongUrlBody = await tooLongUrlResponse.json();
    check("excessively long competitorUrl has code url_too_long", tooLongUrlBody.error.code === "url_too_long");

    const invalidHostResponse = await POST(
      jsonRequest({ userScript: USER_SCRIPT, competitorUrl: "https://vimeo.com/watch?v=" + STANDARD_ID })
    );
    check("non-YouTube domain returns 400 with code unsupported_host", invalidHostResponse.status === 400);
    const invalidHostBody = await invalidHostResponse.json();
    check("non-YouTube domain error code is unsupported_host", invalidHostBody.error.code === "unsupported_host");

    const unsupportedPathResponse = await POST(
      jsonRequest({ userScript: USER_SCRIPT, competitorUrl: "https://www.youtube.com/playlist?list=abc" })
    );
    check("unsupported YouTube path returns 400", unsupportedPathResponse.status === 400);
    const unsupportedPathBody = await unsupportedPathResponse.json();
    check(
      "unsupported YouTube path error code is unsupported_path",
      unsupportedPathBody.error.code === "unsupported_path"
    );

    const malformedJsonResponse = await POST(jsonRequest("{not valid json"));
    check("malformed JSON returns 400", malformedJsonResponse.status === 400);
    const malformedJsonBody = await malformedJsonResponse.json();
    check("malformed JSON error code is invalid_json", malformedJsonBody.error.code === "invalid_json");
    check(
      "malformed JSON never surfaces a raw stack trace",
      !JSON.stringify(malformedJsonBody).toLowerCase().includes("at object")
    );

    const wrongContentTypeResponse = await POST(
      new Request("http://localhost/api/competitor-scripts/compare", {
        method: "POST",
        headers: { "Content-Type": "text/plain" },
        body: JSON.stringify({ userScript: USER_SCRIPT, competitorUrl: COMPETITOR_URL }),
      })
    );
    check("wrong content type is rejected with 415", wrongContentTypeResponse.status === 415);

    const arrayBodyResponse = await POST(jsonRequest([1, 2, 3]));
    check("a JSON array body is rejected as an invalid body shape", arrayBodyResponse.status === 400);

    const oversizedBodyResponse = await POST(
      jsonRequest({ userScript: "A".repeat(20_000), competitorUrl: COMPETITOR_URL })
    );
    check("a request body exceeding the byte limit is rejected with 413", oversizedBodyResponse.status === 413);

    check("no unexpected error was logged during request validation", errorCalls.length === 0);
    check("no provider/network call occurred for any invalid request", fetchCalled === false);

    // ── Unknown/unexpected body fields are silently ignored (matching
    //    Analyze's own convention) ──────────────────────────────────────

    fetchCalled = false;
    const extraFieldsResponse = await POST(
      jsonRequest({
        userScript: USER_SCRIPT,
        competitorUrl: COMPETITOR_URL,
        unexpectedField: "should be ignored",
        nested: { a: 1 },
      })
    );
    check(
      "unexpected extra body fields never cause a 400 — the request proceeds to the transcript stage",
      extraFieldsResponse.status !== 400
    );

    // ── Default (production) composition, no env key configured ────────

    fetchCalled = false;
    infoCalls = [];
    const noKeyResponse = await POST(jsonRequest({ userScript: USER_SCRIPT, competitorUrl: COMPETITOR_URL }));
    check("a valid request with no SUPADATA_API_KEY configured returns 503", noKeyResponse.status === 503);
    const noKeyBody = await noKeyResponse.json();
    check(
      "the missing-config response uses the generic transcript_service_unavailable code",
      noKeyBody.ok === false && noKeyBody.error.code === "transcript_service_unavailable"
    );
    check(
      "the missing-config response never mentions env vars, keys, or Supadata",
      !/env|SUPADATA_API_KEY|api.?key|supadata/i.test(JSON.stringify(noKeyBody))
    );
    check("no provider/network call when no key is configured", fetchCalled === false);
    check(
      "the request-validated log still fires exactly once even though the transcript fetch fails",
      infoCalls.length === 1
    );
    check(
      "the request-validated log never contains the raw submitted competitor URL",
      !JSON.stringify(infoCalls[0]).includes("youtube.com/watch")
    );
    check(
      "the request-validated log never contains the raw submitted user script",
      !JSON.stringify(infoCalls[0]).includes(USER_SCRIPT)
    );

    // ── Environment isolation: SUPADATA_API_KEY missing / empty / whitespace ─

    for (const [label, value] of [
      ["missing", undefined],
      ["empty string", ""],
      ["whitespace-only", "   "],
    ] as const) {
      fetchCalled = false;
      await withSupadataApiKey(value, async () => {
        const response = await POST(jsonRequest({ userScript: USER_SCRIPT, competitorUrl: COMPETITOR_URL }));
        check(`a ${label} SUPADATA_API_KEY causes zero provider calls and a safe 503`, response.status === 503 && !fetchCalled);
      });
    }

    // ── Transcript stage: full TranscriptErrorCode mapping, comparison
    //    model never invoked for any of these ──────────────────────────

    const TRANSCRIPT_ERROR_EXPECTATIONS: Array<{
      code: TranscriptErrorCode;
      status: number;
      publicCode: string;
    }> = [
      { code: "transcript_not_found", status: 404, publicCode: "transcript_not_found" },
      { code: "transcript_disabled", status: 422, publicCode: "transcript_unavailable" },
      { code: "transcript_unavailable", status: 422, publicCode: "transcript_unavailable" },
      { code: "unsupported_language", status: 422, publicCode: "transcript_unavailable" },
      { code: "video_unavailable", status: 404, publicCode: "video_unavailable" },
      { code: "provider_rate_limited", status: 429, publicCode: "transcript_rate_limited" },
      { code: "provider_timeout", status: 504, publicCode: "transcript_timeout" },
      { code: "provider_unavailable", status: 503, publicCode: "transcript_service_unavailable" },
      { code: "invalid_provider_response", status: 502, publicCode: "invalid_transcript_response" },
    ];

    for (const expectation of TRANSCRIPT_ERROR_EXPECTATIONS) {
      const { provider } = stubProvider(() => ({
        ok: false,
        error: makeTranscriptError(expectation.code),
      }));
      const { caller, callCount } = makeScriptedModelCaller(["success"]);

      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        provider,
        caller
      );

      check(
        `transcript error ${expectation.code} maps to status ${expectation.status} with code ${expectation.publicCode}`,
        outcome.status === expectation.status &&
          !outcome.body.ok &&
          outcome.body.error.code === expectation.publicCode
      );
      check(
        `the comparison model is never called when transcript retrieval fails with ${expectation.code}`,
        callCount() === 0
      );
    }

    // An unexpected throw from the transcript provider is treated exactly
    // like an unreachable service.
    {
      const { caller, callCount } = makeScriptedModelCaller(["success"]);
      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        throwingProvider(),
        caller
      );
      check(
        "an unexpected transcript provider throw is mapped to a safe 503 transcript_service_unavailable",
        outcome.status === 503 && !outcome.body.ok && outcome.body.error.code === "transcript_service_unavailable"
      );
      check("the comparison model is never called after an unexpected transcript provider throw", callCount() === 0);
    }

    // The transcript provider is called exactly once, with exactly the
    // resolved videoId.
    {
      const { provider, calls } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"]);
      await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check("the transcript provider is called exactly once", calls.length === 1);
      check("the transcript provider receives exactly the videoId", calls[0] === STANDARD_ID);
    }

    // ── OPENAI_API_KEY isolation: transcript succeeds, comparison never
    //    reachable without a configured/injected model caller ──────────

    for (const [label, value] of [
      ["missing", undefined],
      ["empty string", ""],
      ["whitespace-only", "   "],
    ] as const) {
      const { provider } = stubCompareTranscriptProvider();
      fetchCalled = false;

      await withOpenAIApiKey(value, async () => {
        const outcome = await runCompetitorScriptsCompare(
          USER_SCRIPT,
          STANDARD_ID,
          COMPETITOR_URL,
          "en",
          provider
        );
        check(
          `a ${label} OPENAI_API_KEY causes zero model calls and a safe comparison_unavailable`,
          outcome.status === 503 &&
            !outcome.body.ok &&
            outcome.body.error.code === "comparison_unavailable" &&
            !fetchCalled
        );
        check(
          `the ${label} OPENAI_API_KEY response never mentions env vars or keys`,
          !/OPENAI_API_KEY|api.?key/i.test(JSON.stringify(outcome.body))
        );
      });
    }

    // ── Oversized inputs: canonical size check lives solely in
    //    checkComparisonInputSize (inside runCompetitorScriptComparison) —
    //    no duplicate route-level length check exists. A too-long
    //    userScript is only ever caught AFTER a successful transcript
    //    fetch; the transcript provider is still called once, and the
    //    model is never called. ───────────────────────────────────────

    {
      const { provider, calls } = stubCompareTranscriptProvider();
      const { caller, callCount } = makeScriptedModelCaller(["success"]);
      const oversizedScript = padUserScript(1001);

      const outcome = await runCompetitorScriptsCompare(
        oversizedScript,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        provider,
        caller
      );

      check(
        "a userScript over 1000 characters is rejected with user_script_too_long_for_comparison at 400",
        outcome.status === 400 && !outcome.body.ok && outcome.body.error.code === "user_script_too_long_for_comparison"
      );
      check(
        "the transcript is still fetched once before the oversized-script check runs (no duplicate route-level length check short-circuits it earlier)",
        calls.length === 1
      );
      check("the comparison model is never called for an oversized userScript", callCount() === 0);
    }

    {
      const oversizedTranscript = padCompetitorTranscript(6001);
      const { provider } = stubCompareTranscriptProvider({
        text: oversizedTranscript.text,
        durationMs: oversizedTranscript.durationMs,
      });
      const { caller, callCount } = makeScriptedModelCaller(["success"]);

      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        provider,
        caller
      );

      check(
        "a competitor transcript over 6000 characters is rejected with competitor_transcript_too_long_for_comparison at 422",
        outcome.status === 422 &&
          !outcome.body.ok &&
          outcome.body.error.code === "competitor_transcript_too_long_for_comparison"
      );
      check("the comparison model is never called for an oversized competitor transcript", callCount() === 0);
    }

    // ── Provider outcome mapping: comparison_invalid_response,
    //    comparison_unavailable, recovery-on-retry, and the provider's own
    //    single retry never duplicated by the route ────────────────────

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller, callCount } = makeScriptedModelCaller(["malformed", "malformed", "malformed"]);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check(
        "two consecutive malformed model responses map to comparison_invalid_response at 502",
        outcome.status === 502 && !outcome.body.ok && outcome.body.error.code === "comparison_invalid_response"
      );
      check(
        "exactly 2 model calls occur — the provider's own bounded retry, never a 3rd route-level call",
        callCount() === 2
      );
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller, callCount } = makeScriptedModelCaller(["transient", "transient", "transient"]);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check(
        "two consecutive transient upstream failures map to comparison_unavailable at 503",
        outcome.status === 503 && !outcome.body.ok && outcome.body.error.code === "comparison_unavailable"
      );
      check("exactly 2 model calls occur for a transient-then-transient failure, never a 3rd", callCount() === 2);
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller, callCount } = makeScriptedModelCaller(["malformed", "success"]);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check(
        "a malformed-then-success sequence still succeeds through the route",
        outcome.status === 200 && outcome.body.ok === true
      );
      check("exactly the provider's own 2 calls occur for malformed-then-success", callCount() === 2);
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller, callCount } = makeScriptedModelCaller(["transient", "success"]);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check(
        "a transient-then-success sequence still succeeds through the route",
        outcome.status === 200 && outcome.body.ok === true
      );
      check("exactly the provider's own 2 calls occur for transient-then-success", callCount() === 2);
    }

    // ── Successful comparison: EN, RU, zero cautions, endMs null,
    //    deterministic sourceMeta ───────────────────────────────────────

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"], "en", 1);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);

      check("a valid EN request succeeds with status 200", outcome.status === 200);
      check(
        "the EN success response has the exact expected top-level shape",
        outcome.body.ok === true &&
          typeof outcome.body.comparison === "object" &&
          typeof outcome.body.sourceMeta === "object"
      );
      if (outcome.body.ok) {
        check("the EN comparison locale matches the request", outcome.body.comparison.locale === "en");
        check(
          "sourceMeta.videoId/canonicalUrl are assembled from the resolved URL result",
          outcome.body.sourceMeta.videoId === STANDARD_ID &&
            outcome.body.sourceMeta.canonicalUrl === COMPETITOR_URL
        );
        check(
          "sourceMeta.durationMs matches the transcript's own durationMs",
          outcome.body.sourceMeta.durationMs === COMPETITOR_TRANSCRIPT.durationMs
        );
        check(
          "sourceMeta.userScriptCharacterCount matches the submitted script length",
          outcome.body.sourceMeta.userScriptCharacterCount === USER_SCRIPT.length
        );
        check(
          "the success response never includes the full competitor transcript text anywhere",
          !JSON.stringify(outcome.body).includes(COMPETITOR_TRANSCRIPT.text)
        );
      }
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"], "ru", 1);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "ru", provider, caller);
      check("a valid RU request succeeds with status 200", outcome.status === 200 && outcome.body.ok === true);
      if (outcome.body.ok) {
        check("the RU comparison locale matches the request", outcome.body.comparison.locale === "ru");
      }
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"], "en", 0);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);
      check(
        "zero cautions is accepted as a valid success outcome, not forced/invented",
        outcome.status === 200 && outcome.body.ok === true && outcome.body.comparison.cautions.length === 0
      );
    }

    {
      const candidateWithNullEndMs = makeValidCandidate("en", 1);
      const findings = candidateWithNullEndMs.dimensionFindings as Array<Record<string, unknown>>;
      const hookEvidence = (findings[0].evidence as Record<string, unknown>).competitor as Record<string, unknown>;
      hookEvidence.endMs = null;

      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller([{ raw: JSON.stringify(candidateWithNullEndMs) }]);
      const outcome = await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);

      check(
        "competitor evidence with a null endMs round-trips correctly through validation into the success response",
        outcome.status === 200 &&
          outcome.body.ok === true &&
          outcome.body.comparison.dimensionFindings[0].evidence.competitor.endMs === null
      );
    }

    // ── The provider receives exactly the submitted user script
    //    (untrimmed), the normalized transcript, and the requested locale ─

    {
      const paddedScript = `  ${USER_SCRIPT}  `;
      const { provider } = stubCompareTranscriptProvider();
      const { caller, calls } = makeCapturingModelCaller("en");

      const outcome = await runCompetitorScriptsCompare(
        paddedScript,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        provider,
        caller
      );

      check(
        "the exact (untrimmed) submitted user script is forwarded to the model prompt",
        calls.length === 1 && calls[0].userPrompt.includes(paddedScript)
      );
      check(
        "every competitor transcript segment's text is forwarded to the model prompt",
        COMPETITOR_SEGMENTS.every((segment) => calls[0].userPrompt.includes(segment.text))
      );
      check(
        "the requested locale is forwarded to the model prompt",
        calls[0].userPrompt.includes('"en"') && calls[0].userPrompt.includes("English")
      );
      check(
        "sourceMeta.userScriptCharacterCount reflects the original (untrimmed) submitted length, not the trimmed length",
        outcome.body.ok === true && outcome.body.sourceMeta.userScriptCharacterCount === paddedScript.length
      );
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller, calls } = makeCapturingModelCaller("ru");
      await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "ru", provider, caller);
      check(
        "a Russian locale request is forwarded to the model prompt as Russian",
        calls.length === 1 && calls[0].userPrompt.includes('"ru"') && calls[0].userPrompt.includes("Russian")
      );
    }

    // ── Locale resolution is lazy and behaves identically to Analyze: no
    //    Compare-specific behavior ───────────────────────────────────────

    {
      const invalidLocaleResponse = await POST(
        jsonRequest({ userScript: USER_SCRIPT, competitorUrl: COMPETITOR_URL, locale: "xx" })
      );
      check(
        "an invalid/unsupported locale value never causes a request rejection (falls back silently, proven end-to-end via the no-SUPADATA_API_KEY 503 path)",
        invalidLocaleResponse.status === 503
      );
    }

    {
      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"], "ru");
      let resolverCalls = 0;
      const localeResolver = async () => {
        resolverCalls += 1;
        return "ru" as const;
      };

      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        localeResolver,
        provider,
        caller
      );

      check(
        "when locale is given as a resolver function, it is invoked exactly once after a successful transcript, and its resolved value is used",
        resolverCalls === 1 && outcome.body.ok === true && outcome.body.comparison.locale === "ru"
      );
    }

    {
      let resolverCalls = 0;
      const localeResolver = async () => {
        resolverCalls += 1;
        return "en" as const;
      };

      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        localeResolver,
        throwingProvider()
      );

      check(
        "the locale resolver is never invoked when the transcript stage fails",
        resolverCalls === 0 && outcome.status === 503
      );
    }

    // ── Security/privacy: raw content never appears in logs or public
    //    error/success bodies ────────────────────────────────────────────

    {
      infoCalls = [];
      errorCalls = [];
      const { provider } = stubCompareTranscriptProvider();
      const { caller } = makeScriptedModelCaller(["success"], "en", 1);

      await runCompetitorScriptsCompare(USER_SCRIPT, STANDARD_ID, COMPETITOR_URL, "en", provider, caller);

      const allLogsSerialized = JSON.stringify([...infoCalls, ...errorCalls]);
      check("no log line ever contains the raw user script", !allLogsSerialized.includes(USER_SCRIPT));
      check(
        "no log line ever contains the competitor transcript text",
        !allLogsSerialized.includes(COMPETITOR_TRANSCRIPT.text)
      );
    }

    {
      infoCalls = [];
      errorCalls = [];
      const { provider } = stubCompareTranscriptProvider();
      const malformedRaw = `not valid json — contains "${USER_SCRIPT.slice(0, 20)}" fragment {{{`;
      const { caller } = makeScriptedModelCaller([{ raw: malformedRaw }, { raw: malformedRaw }]);

      const outcome = await runCompetitorScriptsCompare(
        USER_SCRIPT,
        STANDARD_ID,
        COMPETITOR_URL,
        "en",
        provider,
        caller
      );

      check(
        "a comparison_invalid_response body never leaks the internal validator reason or raw model output",
        outcome.status === 502 &&
          !outcome.body.ok &&
          JSON.stringify(outcome.body) ===
            JSON.stringify({
              ok: false,
              error: {
                code: "comparison_invalid_response",
                message: "We couldn't generate a comparison right now. Please try again.",
              },
            })
      );
      const allLogsSerialized = JSON.stringify([...infoCalls, ...errorCalls]);
      check("no log line ever contains the raw malformed model output", !allLogsSerialized.includes("not valid json"));
    }

    // ── Method availability ──────────────────────────────────────────────

    const routeModule: Record<string, unknown> = await import(
      "../app/api/competitor-scripts/compare/route"
    );
    check(
      "the route exports only POST — no GET/PUT/DELETE handler exists",
      typeof routeModule.POST === "function" &&
        routeModule.GET === undefined &&
        routeModule.PUT === undefined &&
        routeModule.DELETE === undefined
    );
  } finally {
    globalThis.fetch = originalFetch;
    console.info = originalConsoleInfo;
    console.error = originalConsoleError;
  }
}

// ── Static source checks: composition boundaries and scope ───────────────

check(
  "the Compare Scripts input form is wired to the new compare API route (frontend wiring PR)",
  readFileSync("app/competitor-scripts/compare/compare-input-form.tsx", "utf8").includes(
    "/api/competitor-scripts/compare"
  )
);

const routeSource = readFileSync("app/api/competitor-scripts/compare/route.ts", "utf8");
const routeCodeOnly = routeSource.replace(/\/\/.*$/gm, "");
check(
  "the compare route never imports the openai package directly — it only composes the merged Compare provider (createOpenAICompetitorComparisonModelCaller/runCompetitorScriptComparison), which owns the real OpenAI call",
  !/from\s+["']openai["']/.test(routeCodeOnly)
);
check("the compare route never calls Supabase", !/supabase|createSupabaseServerClient/i.test(routeSource));
check(
  "the compare route never reads any env var other than SUPADATA_API_KEY or OPENAI_API_KEY",
  (routeSource.match(/process\.env\.[A-Z0-9_]+/g) ?? []).every(
    (match) => match === "process.env.SUPADATA_API_KEY" || match === "process.env.OPENAI_API_KEY"
  )
);

async function main() {
  await testRoute();

  if (failures > 0) {
    process.exitCode = 1;
  } else {
    console.log("\nResult: all Competitor Scripts Compare API tests passed.");
  }
}

void main();
