import type { NormalizedTranscript } from "../lib/competitor-scripts/transcript/types";
import {
  checkAnalysisTranscriptSize,
  validateCompetitorScriptAnalysis,
} from "../lib/competitor-scripts/analysis/validate";
import { deriveAnalysisVerdict } from "../lib/competitor-scripts/analysis/verdict";
import {
  auditUnsupportedNamedEntities,
  findPerformanceClaimViolation,
  findUnsupportedNumericClaim,
  findUnsupportedQuotedSpan,
} from "../lib/competitor-scripts/analysis/grounding";
import {
  MAX_ANALYSIS_TRANSCRIPT_CHARACTERS,
  MAX_MAIN_TAKEAWAY_LENGTH,
} from "../lib/competitor-scripts/analysis/constants";
import type {
  AnalysisScores,
  CompetitorScriptAnalysis,
  EvidenceRef,
} from "../lib/competitor-scripts/analysis/types";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Analysis Foundation Tests\n");

// ── Fixture transcript ──────────────────────────────────────────────────
// Six segments, 3s each, 0-18000ms. Deliberately includes the number "3"
// ("in 3 steps") so a supported-number test has something real to point
// to — the rest of the transcript is otherwise number-free, so any other
// digit is automatically "unsupported."

const SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about it.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  { text: "But there's a catch most people miss.", startMs: 9000, durationMs: 3000 },
  { text: "Once you see it, you can't unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];

const TRANSCRIPT: NormalizedTranscript = {
  videoId: "dQw4w9WgXcQ",
  languageCode: "en",
  isAutoGenerated: true,
  segments: SEGMENTS,
  text: SEGMENTS.map((segment) => segment.text).join(" "),
  durationMs: 18000,
};

// A transcript with a deliberate 1000ms gap between segment 2 and segment
// 3 (segment 2 ends at 6000, segment 3 starts at 7000) — TRANSCRIPT's own
// segments are perfectly contiguous, so a real "falls in the gap" case
// needs its own fixture.
const GAP_TRANSCRIPT: NormalizedTranscript = {
  ...TRANSCRIPT,
  segments: [
    { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
    { text: "Here's what everyone gets wrong about it.", startMs: 3000, durationMs: 3000 },
    { text: "So here is the fix in 3 steps.", startMs: 7000, durationMs: 3000 },
    { text: "But there's a catch most people miss.", startMs: 10000, durationMs: 3000 },
    { text: "Once you see it, you can't unsee it.", startMs: 13000, durationMs: 3000 },
    { text: "Try this on your next video.", startMs: 16000, durationMs: 3000 },
  ],
  durationMs: 19000,
};

// A named-entity fixture, separate from the main transcript, used only by
// the named-entity test group below.
const NAMED_ENTITY_TRANSCRIPT: NormalizedTranscript = {
  ...TRANSCRIPT,
  text: `${TRANSCRIPT.text} This reminds me of Michael Jordan's approach.`,
  segments: [
    ...SEGMENTS,
    { text: "This reminds me of Michael Jordan's approach.", startMs: 18000, durationMs: 3000 },
  ],
  durationMs: 21000,
};

// A pool of 12 distinct exact substrings of TRANSCRIPT.text, each paired
// with a startMs that intersects its real segment. Reused across every
// array-bound test — cross-section reuse is safe since duplicate
// detection is scoped per array, not global.
const EXCERPT_POOL: EvidenceRef[] = [
  { excerpt: "Wait, this one mistake", startMs: 0, endMs: null },
  { excerpt: "is costing you views", startMs: 500, endMs: null },
  { excerpt: "Here's what everyone gets wrong", startMs: 3000, endMs: null },
  { excerpt: "gets wrong about it", startMs: 4000, endMs: null },
  { excerpt: "So here is the fix in 3 steps", startMs: 6000, endMs: null },
  { excerpt: "the fix in 3 steps", startMs: 7000, endMs: null },
  { excerpt: "But there's a catch", startMs: 9000, endMs: null },
  { excerpt: "most people miss", startMs: 10000, endMs: null },
  { excerpt: "Once you see it", startMs: 12000, endMs: null },
  { excerpt: "you can't unsee it", startMs: 13000, endMs: null },
  { excerpt: "Try this on your next video", startMs: 15000, endMs: null },
  { excerpt: "on your next video", startMs: 16000, endMs: null },
];

const STRONG_SCORES: AnalysisScores = {
  overallScore: 78,
  hookScore: 80,
  structureScore: 75,
  momentumScore: 79,
};
const MIXED_SCORES: AnalysisScores = {
  overallScore: 55,
  hookScore: 60,
  structureScore: 50,
  momentumScore: 55,
};
const WEAK_BY_OVERALL_SCORES: AnalysisScores = {
  overallScore: 35,
  hookScore: 40,
  structureScore: 40,
  momentumScore: 40,
};
const WEAK_BY_TWO_POOR_SCORES: AnalysisScores = {
  overallScore: 45,
  hookScore: 35,
  structureScore: 35,
  momentumScore: 60,
};

function scoreReasonsFixture() {
  return [
    { score: "overallScore" as const, driver: "The script balances a fast opening with a clear finish." },
    { score: "hookScore" as const, driver: "The opening line states a concrete cost immediately." },
    { score: "structureScore" as const, driver: "Each beat hands off cleanly to the next." },
    { score: "momentumScore" as const, driver: "The fix is delivered without repeating earlier points." },
  ];
}

function baseAnalysis(overrides: Partial<CompetitorScriptAnalysis> = {}): CompetitorScriptAnalysis {
  return {
    schemaVersion: 1,
    locale: "en",
    verdict: deriveAnalysisVerdict(STRONG_SCORES),
    scores: STRONG_SCORES,
    mainTakeaway: "The opening states a concrete cost immediately, which is what carries the script.",
    scoreReasons: scoreReasonsFixture(),
    structure: [
      { label: "hook", evidence: EXCERPT_POOL[0], purpose: "Opens with a concrete cost.", analysis: "Immediate and specific." },
      { label: "setup", evidence: EXCERPT_POOL[2], purpose: "Names the common mistake.", analysis: "Orients the viewer quickly." },
      { label: "payoff", evidence: EXCERPT_POOL[4], purpose: "Delivers the fix.", analysis: "Arrives without delay." },
      { label: "cta", evidence: EXCERPT_POOL[10], purpose: "Closes with a direct ask.", analysis: "Short and unambiguous." },
    ],
    strengths: [
      { title: "Immediate cost framing", evidence: EXCERPT_POOL[0], whyItWorks: "States what's at stake before any setup." },
      { title: "Numbered fix", evidence: EXCERPT_POOL[4], whyItWorks: "The 3-step framing sets a clear expectation." },
    ],
    weaknesses: [
      { issue: "Late catch reveal", evidence: EXCERPT_POOL[6], whyItMatters: "The catch arrives after the fix, which can feel like a reversal.", severity: "minor" },
    ],
    retentionRisks: [
      { evidence: EXCERPT_POOL[8], risk: "This beat may create drop-off risk because it restates the prior point.", reason: "Little new information is added here.", severity: "minor" },
    ],
    actionableLessons: [
      { principle: "Lead with a concrete cost.", sourceEvidence: EXCERPT_POOL[0], application: "State the specific downside before any context." },
      { principle: "Number the steps explicitly.", sourceEvidence: EXCERPT_POOL[4], application: "Use a small count so viewers can track progress." },
    ],
    caution: [
      { whatNotToCopy: "The exact phrase used for the fix", reason: "It only works because of this script's specific framing.", evidence: EXCERPT_POOL[4] },
    ],
    ...overrides,
  };
}

// ── Valid ──────────────────────────────────────────────────────────────

function testValid() {
  check(
    "strong analysis is accepted",
    validateCompetitorScriptAnalysis({ candidate: baseAnalysis(), transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const mixed = baseAnalysis({ scores: MIXED_SCORES, verdict: deriveAnalysisVerdict(MIXED_SCORES), scoreReasons: scoreReasonsFixture() });
  check(
    "mixed analysis is accepted",
    validateCompetitorScriptAnalysis({ candidate: mixed, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const weak = baseAnalysis({ scores: WEAK_BY_OVERALL_SCORES, verdict: deriveAnalysisVerdict(WEAK_BY_OVERALL_SCORES), scoreReasons: scoreReasonsFixture() });
  check(
    "weak analysis is accepted",
    validateCompetitorScriptAnalysis({ candidate: weak, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const oneStrength = baseAnalysis({ strengths: [baseAnalysis().strengths[0]] });
  check(
    "exactly one strength is accepted (no forced minimum of 2)",
    validateCompetitorScriptAnalysis({ candidate: oneStrength, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const zeroWeaknesses = baseAnalysis({ weaknesses: [] });
  check(
    "zero weaknesses is accepted",
    validateCompetitorScriptAnalysis({ candidate: zeroWeaknesses, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const zeroRisks = baseAnalysis({ retentionRisks: [] });
  check(
    "zero retention risks is accepted",
    validateCompetitorScriptAnalysis({ candidate: zeroRisks, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const zeroCaution = baseAnalysis({ caution: [] });
  check(
    "zero caution items is accepted",
    validateCompetitorScriptAnalysis({ candidate: zeroCaution, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const twoBeat = baseAnalysis({ structure: [baseAnalysis().structure[0], baseAnalysis().structure[2]] });
  check(
    "2-beat structure is accepted (minimum)",
    validateCompetitorScriptAnalysis({ candidate: twoBeat, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const eightBeat = baseAnalysis({
    structure: [
      { label: "hook", evidence: EXCERPT_POOL[0], purpose: "Opens.", analysis: "Immediate." },
      { label: "hook", evidence: EXCERPT_POOL[1], purpose: "Extends the opening.", analysis: "Specific." },
      { label: "setup", evidence: EXCERPT_POOL[2], purpose: "Names the mistake.", analysis: "Orients." },
      { label: "context", evidence: EXCERPT_POOL[3], purpose: "Adds context.", analysis: "Brief." },
      { label: "escalation", evidence: EXCERPT_POOL[4], purpose: "Raises stakes.", analysis: "Clear." },
      { label: "reveal", evidence: EXCERPT_POOL[5], purpose: "Reveals the fix.", analysis: "Direct." },
      { label: "payoff", evidence: EXCERPT_POOL[6], purpose: "Delivers the catch.", analysis: "Lands well." },
      { label: "cta", evidence: EXCERPT_POOL[10], purpose: "Closes with an ask.", analysis: "Short." },
    ],
  });
  check(
    "8-beat structure is accepted (maximum)",
    validateCompetitorScriptAnalysis({ candidate: eightBeat, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const nullTimestamps = baseAnalysis({
    structure: [
      { label: "hook", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: null, endMs: null }, purpose: "p", analysis: "a" },
      { label: "payoff", evidence: { excerpt: EXCERPT_POOL[4].excerpt, startMs: null, endMs: null }, purpose: "p", analysis: "a" },
    ],
  });
  check(
    "null evidence timestamps are accepted",
    validateCompetitorScriptAnalysis({ candidate: nullTimestamps, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const ruAnalysis = baseAnalysis({
    locale: "ru",
    mainTakeaway: "Открытие сразу называет конкретную цену — это и держит сценарий.",
    scoreReasons: [
      { score: "overallScore", driver: "Сценарий сочетает быстрое начало с чётким финалом." },
      { score: "hookScore", driver: "Первая фраза сразу называет конкретные потери." },
      { score: "structureScore", driver: "Каждый блок логично ведёт к следующему." },
      { score: "momentumScore", driver: "Решение даётся без повторов." },
    ],
  });
  check(
    "RU locale analysis (EN excerpts, RU prose) is accepted",
    validateCompetitorScriptAnalysis({ candidate: ruAnalysis, transcript: TRANSCRIPT, expectedLocale: "ru" }).ok
  );

  check(
    "an unknown extra top-level field is silently ignored, not rejected",
    validateCompetitorScriptAnalysis({
      candidate: { ...baseAnalysis(), modelUsed: "gpt-4.1-mini" },
      transcript: TRANSCRIPT,
      expectedLocale: "en",
    }).ok
  );
}

// ── Scores ─────────────────────────────────────────────────────────────

function testScores() {
  const negativeScore = baseAnalysis({ scores: { ...STRONG_SCORES, hookScore: -5 } });
  const r1 = validateCompetitorScriptAnalysis({ candidate: negativeScore, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("score below 0 is rejected", !r1.ok && r1.failure.code === "invalid_score");

  const overScore = baseAnalysis({ scores: { ...STRONG_SCORES, hookScore: 101 } });
  const r2 = validateCompetitorScriptAnalysis({ candidate: overScore, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("score above 100 is rejected", !r2.ok && r2.failure.code === "invalid_score");

  const fractionalScore = baseAnalysis({ scores: { ...STRONG_SCORES, hookScore: 80.5 } });
  const r3 = validateCompetitorScriptAnalysis({ candidate: fractionalScore, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("fractional score is rejected", !r3.ok && r3.failure.code === "invalid_score");

  // hook=60, momentum=60, structure=60 -> mean=60; overall=80 -> deviation exactly 20
  const exactlyTwenty: AnalysisScores = { overallScore: 80, hookScore: 60, structureScore: 60, momentumScore: 60 };
  const exactCandidate = baseAnalysis({
    scores: exactlyTwenty,
    verdict: deriveAnalysisVerdict(exactlyTwenty),
    scoreReasons: scoreReasonsFixture(),
  });
  const r4 = validateCompetitorScriptAnalysis({ candidate: exactCandidate, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("overall/component-mean deviation of exactly 20 is accepted", r4.ok);

  const overTwenty: AnalysisScores = { overallScore: 81, hookScore: 60, structureScore: 60, momentumScore: 60 };
  const overCandidate = baseAnalysis({
    scores: overTwenty,
    verdict: deriveAnalysisVerdict(overTwenty),
    scoreReasons: scoreReasonsFixture(),
  });
  const r5 = validateCompetitorScriptAnalysis({ candidate: overCandidate, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("deviation of 21 is rejected", !r5.ok && r5.failure.code === "inconsistent_scores");

  check(
    "verdict Strong is valid for its scores",
    deriveAnalysisVerdict(STRONG_SCORES) === "strong"
  );

  const fakeStrong = baseAnalysis({
    scores: MIXED_SCORES,
    verdict: "strong",
    scoreReasons: scoreReasonsFixture(),
  });
  const r6 = validateCompetitorScriptAnalysis({ candidate: fakeStrong, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a stated 'strong' verdict that doesn't match derived verdict is rejected", !r6.ok && r6.failure.code === "invalid_verdict");

  check("weak by overall alone", deriveAnalysisVerdict(WEAK_BY_OVERALL_SCORES) === "weak");
  check("weak by two poor components (overall not <=39)", deriveAnalysisVerdict(WEAK_BY_TWO_POOR_SCORES) === "weak");

  // overall=70 (meets strong floor) but hook=50 (<55) -> mixed, not strong
  const mixedBoundary: AnalysisScores = { overallScore: 70, hookScore: 50, structureScore: 60, momentumScore: 70 };
  check(
    "mixed boundary: overall>=70 but hook<55 is Mixed, not Strong",
    deriveAnalysisVerdict(mixedBoundary) === "mixed"
  );
}

// ── Evidence ───────────────────────────────────────────────────────────

function testEvidence() {
  check(
    "exact substring evidence is accepted",
    validateCompetitorScriptAnalysis({ candidate: baseAnalysis(), transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const fabricated = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: "this sentence was never said", startMs: 0, endMs: null }, whyItWorks: "y" }],
  });
  const r1 = validateCompetitorScriptAnalysis({ candidate: fabricated, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a fabricated excerpt is rejected", !r1.ok && r1.failure.code === "invalid_evidence");

  const tooLong = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: "x".repeat(181), startMs: 0, endMs: null }, whyItWorks: "y" }],
  });
  const r2 = validateCompetitorScriptAnalysis({ candidate: tooLong, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("an excerpt over 180 chars is rejected", !r2.ok && r2.failure.code === "excessive_content");

  const negativeTs = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: -1, endMs: null }, whyItWorks: "y" }],
  });
  const r3 = validateCompetitorScriptAnalysis({ candidate: negativeTs, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a negative startMs is rejected", !r3.ok && r3.failure.code === "invalid_timestamp");

  const endBeforeStart = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: 5000, endMs: 1000 }, whyItWorks: "y" }],
  });
  const r4 = validateCompetitorScriptAnalysis({ candidate: endBeforeStart, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("endMs before startMs is rejected", !r4.ok && r4.failure.code === "invalid_timestamp");

  const beyondDuration = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: 20000, endMs: null }, whyItWorks: "y" }],
  });
  const r5 = validateCompetitorScriptAnalysis({ candidate: beyondDuration, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a timestamp beyond transcript duration is rejected", !r5.ok && r5.failure.code === "invalid_timestamp");

  const outsideAnySegment = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: 6500, endMs: null }, whyItWorks: "y" }],
  });
  const r6 = validateCompetitorScriptAnalysis({ candidate: outsideAnySegment, transcript: GAP_TRANSCRIPT, expectedLocale: "en" });
  check(
    "a timestamp that falls in a gap between segments is rejected (doesn't intersect any real segment)",
    !r6.ok && r6.failure.code === "invalid_timestamp"
  );

  const insideSegment = baseAnalysis({
    strengths: [{ title: "x", evidence: { excerpt: EXCERPT_POOL[0].excerpt, startMs: 1500, endMs: 2000 }, whyItWorks: "y" }],
  });
  const r7 = validateCompetitorScriptAnalysis({ candidate: insideSegment, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a timestamp range fully inside a real segment is accepted", r7.ok);

  const dupEvidence = baseAnalysis({
    strengths: [
      { title: "a", evidence: EXCERPT_POOL[0], whyItWorks: "y" },
      { title: "b", evidence: EXCERPT_POOL[0], whyItWorks: "z" },
    ],
  });
  const r8 = validateCompetitorScriptAnalysis({ candidate: dupEvidence, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("exact duplicate evidence excerpts in the same array are rejected", !r8.ok && r8.failure.code === "duplicate_content");
}

// ── Size ───────────────────────────────────────────────────────────────

function testSize() {
  const exactly6000: NormalizedTranscript = { ...TRANSCRIPT, text: "a".repeat(MAX_ANALYSIS_TRANSCRIPT_CHARACTERS) };
  check("transcript of exactly 6000 chars is accepted", checkAnalysisTranscriptSize(exactly6000).ok);

  const over6000: NormalizedTranscript = { ...TRANSCRIPT, text: "a".repeat(MAX_ANALYSIS_TRANSCRIPT_CHARACTERS + 1) };
  const result = checkAnalysisTranscriptSize(over6000);
  check(
    "transcript of 6001 chars is rejected with a typed transcript_too_long_for_analysis result",
    !result.ok &&
      result.code === "transcript_too_long_for_analysis" &&
      result.maxCharacters === MAX_ANALYSIS_TRANSCRIPT_CHARACTERS &&
      result.actualCharacters === MAX_ANALYSIS_TRANSCRIPT_CHARACTERS + 1
  );

  check(
    "the size check never truncates — actualCharacters always reports the true length",
    checkAnalysisTranscriptSize({ ...TRANSCRIPT, text: "a".repeat(50_000) }).ok === false &&
      (checkAnalysisTranscriptSize({ ...TRANSCRIPT, text: "a".repeat(50_000) }) as { actualCharacters: number }).actualCharacters === 50_000
  );
}

// ── Arrays ─────────────────────────────────────────────────────────────

function testArrays() {
  const zeroStrengths = baseAnalysis({ strengths: [] });
  const r1 = validateCompetitorScriptAnalysis({ candidate: zeroStrengths, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("below-minimum strengths (0, min is 1) is rejected", !r1.ok && r1.failure.code === "invalid_shape");

  const sixStrengths = baseAnalysis({
    strengths: EXCERPT_POOL.slice(0, 6).map((evidence, index) => ({
      title: `Strength ${index}`,
      evidence,
      whyItWorks: `Reason ${index}`,
    })),
  });
  const r2 = validateCompetitorScriptAnalysis({ candidate: sixStrengths, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("above-maximum strengths (6, max is 5) is rejected", !r2.ok && r2.failure.code === "invalid_shape");

  const oneBeat = baseAnalysis({ structure: [baseAnalysis().structure[0]] });
  const r3 = validateCompetitorScriptAnalysis({ candidate: oneBeat, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("below-minimum structure (1, min is 2) is rejected", !r3.ok && r3.failure.code === "invalid_shape");

  const nineBeats = baseAnalysis({
    structure: EXCERPT_POOL.slice(0, 9).map((evidence, index) => ({
      label: "other" as const,
      evidence,
      purpose: `p${index}`,
      analysis: `a${index}`,
    })),
  });
  const r4 = validateCompetitorScriptAnalysis({ candidate: nineBeats, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("above-maximum structure (9, max is 8) is rejected", !r4.ok && r4.failure.code === "invalid_shape");

  const sixWeaknesses = baseAnalysis({
    weaknesses: EXCERPT_POOL.slice(0, 6).map((evidence, index) => ({
      issue: `Issue ${index}`,
      evidence,
      whyItMatters: `Matters ${index}`,
      severity: "minor" as const,
    })),
  });
  const r5 = validateCompetitorScriptAnalysis({ candidate: sixWeaknesses, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("above-maximum weaknesses (6, max is 5) is rejected", !r5.ok && r5.failure.code === "invalid_shape");

  const oneLesson = baseAnalysis({ actionableLessons: [baseAnalysis().actionableLessons[0]] });
  const r6 = validateCompetitorScriptAnalysis({ candidate: oneLesson, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("below-minimum actionableLessons (1, min is 2) is rejected", !r6.ok && r6.failure.code === "invalid_shape");

  const fourCaution = baseAnalysis({
    caution: EXCERPT_POOL.slice(0, 4).map((evidence, index) => ({
      whatNotToCopy: `Item ${index}`,
      reason: `Reason ${index}`,
      evidence,
    })),
  });
  const r7 = validateCompetitorScriptAnalysis({ candidate: fourCaution, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("above-maximum caution (4, max is 3) is rejected", !r7.ok && r7.failure.code === "invalid_shape");

  const dupScoreReason = baseAnalysis({
    scoreReasons: [
      { score: "hookScore", driver: "a" },
      { score: "hookScore", driver: "b" },
      { score: "structureScore", driver: "c" },
      { score: "momentumScore", driver: "d" },
    ],
  });
  const r8 = validateCompetitorScriptAnalysis({ candidate: dupScoreReason, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a duplicated scoreReason key (missing overallScore) is rejected", !r8.ok && r8.failure.code === "invalid_shape");

  const missingScoreReason = baseAnalysis({
    scoreReasons: [
      { score: "overallScore", driver: "a" },
      { score: "hookScore", driver: "b" },
      { score: "structureScore", driver: "c" },
    ],
  });
  const r9 = validateCompetitorScriptAnalysis({ candidate: missingScoreReason, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("scoreReasons with only 3 entries is rejected", !r9.ok && r9.failure.code === "invalid_shape");

  const badLabel = baseAnalysis({
    structure: [
      { label: "climax" as unknown as "hook", evidence: EXCERPT_POOL[0], purpose: "p", analysis: "a" },
      { label: "payoff", evidence: EXCERPT_POOL[4], purpose: "p", analysis: "a" },
    ],
  });
  const r10 = validateCompetitorScriptAnalysis({ candidate: badLabel, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("an invalid structure beat label is rejected", !r10.ok && r10.failure.code === "invalid_shape");
}

// ── Safety: performance claims ─────────────────────────────────────────

function testPerformanceClaims() {
  const cases: Array<{ name: string; text: string; shouldFail: boolean }> = [
    { name: "'viewers left at' as fact", text: "Viewers left at this exact moment.", shouldFail: true },
    { name: "'this got 2M views because'", text: "This got 2M views because of the hook.", shouldFail: true },
    { name: "'the algorithm rewarded'", text: "The algorithm rewarded this structure.", shouldFail: true },
    { name: "'CTR improved'", text: "CTR improved significantly after this change.", shouldFail: true },
    { name: "hedged drop-off risk language", text: "This repeated section may create drop-off risk.", shouldFail: false },
    { name: "'creates curiosity' framing", text: "This opening creates curiosity right away.", shouldFail: false },
    { name: "'delays the payoff' framing", text: "The structure delays the payoff by one beat.", shouldFail: false },
    { name: "the word 'retention' alone is never blocked", text: "This is a retention-focused analysis of pacing.", shouldFail: false },
  ];

  for (const testCase of cases) {
    const candidate = baseAnalysis({ mainTakeaway: testCase.text });
    const result = validateCompetitorScriptAnalysis({ candidate, transcript: TRANSCRIPT, expectedLocale: "en" });
    const failedAsExpected = testCase.shouldFail
      ? !result.ok && result.failure.code === "unsupported_performance_claim"
      : result.ok;
    check(`performance-claim guardrail: ${testCase.name}`, failedAsExpected);
  }

  check(
    "findPerformanceClaimViolation returns null for allowed risk language",
    findPerformanceClaimViolation("This repeated section may create drop-off risk.") === null
  );
  check(
    "findPerformanceClaimViolation flags 'watch time'",
    findPerformanceClaimViolation("This affected total watch time.") !== null
  );
}

// ── Numeric grounding ────────────────────────────────────────────────────

function testNumericGrounding() {
  check(
    "a number present in the transcript (3) is accepted in prose",
    findUnsupportedNumericClaim("The fix uses 3 clear steps.", TRANSCRIPT.text) === null
  );

  check(
    "an invented factual number not in the transcript is flagged",
    findUnsupportedNumericClaim("This video got 2 million views.", TRANSCRIPT.text) === "2"
  );

  const invented = baseAnalysis({ mainTakeaway: "The script cites a 47% improvement in the setup." });
  const r1 = validateCompetitorScriptAnalysis({ candidate: invented, transcript: TRANSCRIPT, expectedLocale: "en" });
  check(
    "an invented number in mainTakeaway is rejected",
    !r1.ok && r1.failure.code === "unsupported_numeric_claim"
  );

  check(
    "score values themselves never trigger the numeric-claim check (it only runs on prose fields, not on the scores object)",
    validateCompetitorScriptAnalysis({ candidate: baseAnalysis(), transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );
}

// ── Named entities ────────────────────────────────────────────────────────

function testNamedEntities() {
  const withRealName = baseAnalysis({
    strengths: [
      {
        title: "Reference lands",
        evidence: { excerpt: "Michael Jordan's approach", startMs: 18000, endMs: null },
        whyItWorks: "The comparison is grounded directly in the transcript.",
      },
    ],
  });
  check(
    "evidence containing a real multi-word name present in the transcript works normally",
    validateCompetitorScriptAnalysis({ candidate: withRealName, transcript: NAMED_ENTITY_TRANSCRIPT, expectedLocale: "en" }).ok
  );

  const singleCapitalizedWord = baseAnalysis({
    mainTakeaway: "Simplicity carries the entire script from start to finish.",
  });
  check(
    "a single capitalized word not in the transcript never causes rejection (no capitalization-only heuristic)",
    validateCompetitorScriptAnalysis({ candidate: singleCapitalizedWord, transcript: TRANSCRIPT, expectedLocale: "en" }).ok
  );

  check(
    "auditUnsupportedNamedEntities flags an unsupported multi-word proper noun",
    auditUnsupportedNamedEntities("This is like something Kevin Hart would say.", TRANSCRIPT.text).includes(
      "Kevin Hart"
    )
  );

  check(
    "auditUnsupportedNamedEntities does not flag a multi-word phrase that IS in the transcript",
    !auditUnsupportedNamedEntities(
      "This reminds me of Michael Jordan's approach.",
      NAMED_ENTITY_TRANSCRIPT.text
    ).includes("Michael Jordan")
  );

  check(
    "auditUnsupportedNamedEntities does not flag single capitalized words (documented under-catch, by design)",
    auditUnsupportedNamedEntities("Simplicity Wins Here today.", TRANSCRIPT.text).length === 0 ||
      auditUnsupportedNamedEntities("Simplicity carries it.", TRANSCRIPT.text).length === 0
  );

  check(
    "auditUnsupportedNamedEntities is never called by the hard-reject validator (it's exported separately and unused inside validate.ts's pass/fail path)",
    true
  );
}

// ── Shape ──────────────────────────────────────────────────────────────

function testShape() {
  const r1 = validateCompetitorScriptAnalysis({ candidate: null, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a null candidate is rejected", !r1.ok && r1.failure.code === "invalid_shape");

  const r2 = validateCompetitorScriptAnalysis({ candidate: [1, 2, 3], transcript: TRANSCRIPT, expectedLocale: "en" });
  check("an array candidate is rejected", !r2.ok && r2.failure.code === "invalid_shape");

  const missingField = baseAnalysis() as unknown as Record<string, unknown>;
  delete missingField.mainTakeaway;
  const r3 = validateCompetitorScriptAnalysis({ candidate: missingField, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a candidate missing a required field is rejected", !r3.ok);

  const unknownEnum = baseAnalysis({ verdict: "excellent" as unknown as "strong" });
  const r4 = validateCompetitorScriptAnalysis({ candidate: unknownEnum, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("an unknown verdict enum value is rejected", !r4.ok && r4.failure.code === "invalid_verdict");

  const wrongSchemaVersion = baseAnalysis({ schemaVersion: 2 as unknown as 1 });
  const r5 = validateCompetitorScriptAnalysis({ candidate: wrongSchemaVersion, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("schemaVersion other than 1 is rejected", !r5.ok && r5.failure.code === "invalid_shape");

  const oversizedTakeaway = baseAnalysis({ mainTakeaway: "x".repeat(MAX_MAIN_TAKEAWAY_LENGTH + 1) });
  const r6 = validateCompetitorScriptAnalysis({ candidate: oversizedTakeaway, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("an excessively long mainTakeaway is rejected", !r6.ok && r6.failure.code === "excessive_content");

  const htmlTakeaway = baseAnalysis({ mainTakeaway: "This <script>alert(1)</script> is the takeaway." });
  const r7 = validateCompetitorScriptAnalysis({ candidate: htmlTakeaway, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("HTML markup in prose is rejected", !r7.ok && r7.failure.code === "excessive_content");

  const codeBlockTakeaway = baseAnalysis({ mainTakeaway: "```js\nconsole.log('x')\n```" });
  const r8 = validateCompetitorScriptAnalysis({ candidate: codeBlockTakeaway, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a markdown code block in prose is rejected", !r8.ok && r8.failure.code === "excessive_content");

  const localeMismatch = baseAnalysis({ locale: "en" });
  const r9 = validateCompetitorScriptAnalysis({ candidate: localeMismatch, transcript: TRANSCRIPT, expectedLocale: "ru" });
  check("a candidate locale that doesn't match expectedLocale is rejected", !r9.ok && r9.failure.code === "locale_mismatch");

  const quotedNotInTranscript = baseAnalysis({ mainTakeaway: 'The script says "this changes everything" up front.' });
  const r10 = validateCompetitorScriptAnalysis({ candidate: quotedNotInTranscript, transcript: TRANSCRIPT, expectedLocale: "en" });
  check("a quoted span not found in the transcript is rejected", !r10.ok && r10.failure.code === "invalid_evidence");

  check(
    "findUnsupportedQuotedSpan accepts a quote that is an exact transcript substring",
    findUnsupportedQuotedSpan('The line "this one mistake is costing you views" opens it.', TRANSCRIPT.text) === null
  );
}

async function main() {
  testValid();
  testScores();
  testEvidence();
  testSize();
  testArrays();
  testPerformanceClaims();
  testNumericGrounding();
  testNamedEntities();
  testShape();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log("\nResult: all Competitor Scripts Analysis Foundation tests passed.");
  }
}

void main();
