import { readFileSync } from "node:fs";

import type { NormalizedTranscript } from "../lib/competitor-scripts/transcript/types";
import type { ComparisonLocale } from "../lib/competitor-scripts/comparison/types";
import {
  checkComparisonInputSize,
  COMPETITOR_COMPARISON_MAX_OUTPUT_TOKENS,
  COMPETITOR_COMPARISON_MODEL,
  COMPETITOR_COMPARISON_REASONING_EFFORT,
  COMPETITOR_COMPARISON_TIMEOUT_MS,
  runCompetitorScriptComparison,
  type CompetitorComparisonModelCaller,
} from "../lib/competitor-scripts/comparison/provider";
import { buildSystemPrompt } from "../lib/competitor-scripts/comparison/prompt";
import { COMPARISON_JSON_SCHEMA } from "../lib/competitor-scripts/comparison/json-schema";
import {
  MAX_CAUTIONS,
  MAX_COMPARISON_COMPETITOR_TRANSCRIPT_CHARACTERS,
  MAX_COMPARISON_USER_SCRIPT_CHARACTERS,
  MAX_HEADLINE_LENGTH,
  MAX_MAIN_TAKEAWAY_LENGTH,
  MAX_PRIORITIES,
  MIN_CAUTIONS,
  MIN_PRIORITIES,
  REQUIRED_DIMENSION_COUNT,
} from "../lib/competitor-scripts/comparison/constants";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Compare Provider Tests\n");

// ── Fixture sources (same shape/style as the Compare foundation test's
// own fixture — this file intentionally builds its own self-contained
// copy rather than importing it, matching how
// tests/competitor-scripts-analysis-provider.ts also keeps its own
// fixture separate from tests/competitor-scripts-analysis-foundation.ts) ─

const USER_SCRIPT =
  "Everyone thinks a strong hook needs a shocking claim, but that is the mistake. " +
  "I open with a plain observation instead, then explain why it matters in 3 words. " +
  "Most creators rush straight to the payoff before earning it. " +
  "I reveal the answer almost immediately after the setup.";

const COMPETITOR_SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about hooks.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  {
    text: "I hold the tension for four extra lines before I answer the question.",
    startMs: 9000,
    durationMs: 3000,
  },
  { text: "Once you see it, you cannot unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];

const COMPETITOR_TRANSCRIPT: NormalizedTranscript = {
  videoId: "dQw4w9WgXcQ",
  languageCode: "en",
  isAutoGenerated: true,
  segments: COMPETITOR_SEGMENTS,
  text: COMPETITOR_SEGMENTS.map((segment) => segment.text).join(" "),
  durationMs: 18000,
};

function padUserScript(targetLength: number): string {
  return USER_SCRIPT.padEnd(targetLength, ".");
}

function padCompetitorTranscript(targetLength: number): NormalizedTranscript {
  return { ...COMPETITOR_TRANSCRIPT, text: COMPETITOR_TRANSCRIPT.text.padEnd(targetLength, ".") };
}

// ── Valid candidate builder ────────────────────────────────────────────────

function makeValidCandidate(
  locale: ComparisonLocale,
  cautionCount: 0 | 1 = 1
): Record<string, unknown> {
  const en = {
    headline: "Their opening names a concrete mistake; yours states the premise more gently.",
    mainTakeaway:
      "Adding one short beat before your answer would give your payoff the same clear landing point their script has.",
    hook: {
      conclusion: "Their hook names the mistake immediately, while yours states the premise more gently.",
      userObservation: "Your opening states the premise as a broad claim.",
      competitorObservation: "Their opening names the specific mistake right away.",
    },
    structure: {
      conclusion: "Both scripts move through a comparable number of story beats.",
      userObservation: "Your structure moves from premise to payoff in a few clear steps.",
      competitorObservation: "Their structure also moves through a short, numbered sequence.",
    },
    momentum: {
      conclusion: "Yours moves into the observation slightly faster after the premise.",
      userObservation: "Your script moves directly into the observation without a detour.",
      competitorObservation: "Their script holds an extra beat before moving forward.",
    },
    payoff: {
      conclusion: "Their payoff lands as a distinct beat, while yours arrives without a clear turn.",
      userObservation: "Your answer arrives immediately, without a signal that it has landed.",
      competitorObservation: "Their payoff is set apart by a short beat that signals the reveal.",
    },
    priority1: {
      problem: "Your payoff arrives without a distinct turn that signals it has landed.",
      competitorPrinciple: "Holding a short beat before answering gives the payoff more weight.",
      howToApply: "Add one short beat before your answer that signals the reveal is about to land.",
    },
    priority2: {
      problem: "Your hook states the premise gently instead of naming a concrete mistake up front.",
      competitorPrinciple:
        "Naming a specific mistake in the opening line gives viewers an immediate reason to keep watching.",
      howToApply: "Rewrite your opening line to name the specific mistake instead of describing the general topic.",
    },
    caution: {
      whatNotToCopy: "Copying their exact opening phrasing",
      reason:
        "Their phrasing fits their channel's established tone; using it word for word elsewhere could read as jarring.",
    },
  };

  const ru = {
    headline: "Их сценарий сразу называет конкретную ошибку; ваш мягче формулирует предпосылку.",
    mainTakeaway:
      "Одна короткая пауза перед ответом дала бы вашей развязке такую же чёткую точку, как в их сценарии.",
    hook: {
      conclusion: "Их крючок сразу называет ошибку, а ваш мягче формулирует предпосылку.",
      userObservation: "Ваше открытие формулирует предпосылку как общее утверждение.",
      competitorObservation: "Их открытие сразу называет конкретную ошибку.",
    },
    structure: {
      conclusion: "Оба сценария проходят через сопоставимое число сюжетных блоков.",
      userObservation: "Ваша структура движется от предпосылки к развязке за несколько чётких шагов.",
      competitorObservation: "Их структура тоже движется через короткую пронумерованную последовательность.",
    },
    momentum: {
      conclusion: "Ваш сценарий немного быстрее переходит к наблюдению после предпосылки.",
      userObservation: "Ваш сценарий сразу переходит к наблюдению без отступлений.",
      competitorObservation: "Их сценарий держит дополнительный такт перед тем как двигаться дальше.",
    },
    payoff: {
      conclusion: "Их развязка выделена отдельным тактом, а ваша приходит без чёткого поворота.",
      userObservation: "Ваш ответ приходит сразу, без сигнала о том, что он состоялся.",
      competitorObservation: "Их развязка выделена коротким тактом, который сигнализирует о развязке.",
    },
    priority1: {
      problem: "Ваша развязка приходит без отдельного поворота, который сигнализирует о том, что она состоялась.",
      competitorPrinciple: "Короткая пауза перед ответом придаёт развязке больше веса.",
      howToApply: "Добавьте один короткий такт перед ответом, который сигнализирует о приближении развязки.",
    },
    priority2: {
      problem: "Ваш крючок мягко формулирует предпосылку вместо того чтобы сразу назвать конкретную ошибку.",
      competitorPrinciple:
        "Называние конкретной ошибки в первой строке сразу даёт зрителю причину продолжать смотреть.",
      howToApply: "Перепишите первую строку так, чтобы назвать конкретную ошибку, а не описывать общую тему.",
    },
    caution: {
      whatNotToCopy: "Копирование их точной фразировки открытия",
      reason:
        "Их фразировка соответствует тону их канала; дословное использование в другом месте может звучать неуместно.",
    },
  };

  const copy = locale === "en" ? en : ru;

  const UE_HOOK = "a strong hook needs a shocking claim";
  const UE_STRUCTURE = "Most creators rush straight to the payoff before earning it.";
  const UE_MOMENTUM = "I open with a plain observation instead";
  const UE_PAYOFF = "I reveal the answer almost immediately after the setup.";

  const CE_HOOK = { excerpt: "Here's what everyone gets wrong about hooks.", startMs: 3000, endMs: 6000 };
  const CE_STRUCTURE = { excerpt: "So here is the fix in 3 steps.", startMs: 6000, endMs: 9000 };
  const CE_MOMENTUM = {
    excerpt: "I hold the tension for four extra lines before I answer the question.",
    startMs: 9000,
    endMs: 12000,
  };
  const CE_PAYOFF = { excerpt: "Once you see it, you cannot unsee it.", startMs: 12000, endMs: 15000 };

  function userEvidence(excerpt: string) {
    return { source: "user", excerpt };
  }

  function competitorEvidence(excerpt: string, startMs: number, endMs: number | null) {
    return { source: "competitor", excerpt, startMs, endMs };
  }

  const cautions =
    cautionCount === 0
      ? []
      : [
          {
            whatNotToCopy: copy.caution.whatNotToCopy,
            reason: copy.caution.reason,
            evidence: {
              competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
              user: null,
            },
          },
        ];

  return {
    schemaVersion: 1,
    locale,
    comparisonSummary: { headline: copy.headline, mainTakeaway: copy.mainTakeaway },
    dimensionFindings: [
      {
        dimension: "hook",
        strongerSide: "competitor",
        gap: "meaningful",
        conclusion: copy.hook.conclusion,
        userObservation: copy.hook.userObservation,
        competitorObservation: copy.hook.competitorObservation,
        evidence: {
          user: userEvidence(UE_HOOK),
          competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
        },
      },
      {
        dimension: "structure",
        strongerSide: "similar",
        gap: null,
        conclusion: copy.structure.conclusion,
        userObservation: copy.structure.userObservation,
        competitorObservation: copy.structure.competitorObservation,
        evidence: {
          user: userEvidence(UE_STRUCTURE),
          competitor: competitorEvidence(CE_STRUCTURE.excerpt, CE_STRUCTURE.startMs, CE_STRUCTURE.endMs),
        },
      },
      {
        dimension: "momentum",
        strongerSide: "user",
        gap: "small",
        conclusion: copy.momentum.conclusion,
        userObservation: copy.momentum.userObservation,
        competitorObservation: copy.momentum.competitorObservation,
        evidence: {
          user: userEvidence(UE_MOMENTUM),
          competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs),
        },
      },
      {
        dimension: "payoff_clarity",
        strongerSide: "competitor",
        gap: "large",
        conclusion: copy.payoff.conclusion,
        userObservation: copy.payoff.userObservation,
        competitorObservation: copy.payoff.competitorObservation,
        evidence: {
          user: userEvidence(UE_PAYOFF),
          competitor: competitorEvidence(CE_PAYOFF.excerpt, CE_PAYOFF.startMs, CE_PAYOFF.endMs),
        },
      },
    ],
    priorities: [
      {
        rank: 1,
        problem: copy.priority1.problem,
        competitorPrinciple: copy.priority1.competitorPrinciple,
        howToApply: copy.priority1.howToApply,
        evidence: {
          user: userEvidence(UE_PAYOFF),
          competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs),
        },
      },
      {
        rank: 2,
        problem: copy.priority2.problem,
        competitorPrinciple: copy.priority2.competitorPrinciple,
        howToApply: copy.priority2.howToApply,
        evidence: {
          user: userEvidence(UE_HOOK),
          competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs),
        },
      },
    ],
    cautions,
  };
}

function cloneCandidate(locale: ComparisonLocale = "en", cautionCount: 0 | 1 = 1): Record<string, unknown> {
  return JSON.parse(JSON.stringify(makeValidCandidate(locale, cautionCount)));
}

function validRaw(locale: ComparisonLocale = "en", cautionCount: 0 | 1 = 1): string {
  return JSON.stringify(makeValidCandidate(locale, cautionCount));
}

// ── Scripted fake model caller (zero real OpenAI calls) ───────────────────

type CallerStep = { kind: "transient" } | { kind: "raw"; raw: string };

function createStepCaller(steps: CallerStep[]): {
  caller: CompetitorComparisonModelCaller;
  calls: { systemPrompt: string; userPrompt: string }[];
} {
  const calls: { systemPrompt: string; userPrompt: string }[] = [];
  let index = 0;

  const caller: CompetitorComparisonModelCaller = async ({ systemPrompt, userPrompt }) => {
    calls.push({ systemPrompt, userPrompt });
    const step = steps[index];
    index += 1;

    if (!step) {
      throw new Error("Test caller invoked a third time — this must never happen.");
    }

    if (step.kind === "transient") {
      throw { status: 500 };
    }

    return { raw: step.raw, modelUsed: COMPETITOR_COMPARISON_MODEL };
  };

  return { caller, calls };
}

// ── Tests ────────────────────────────────────────────────────────────────

async function testValidFirstAttempt(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw() }]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check("valid first attempt succeeds with exactly 1 model call", calls.length === 1);
  check("valid first attempt returns ok:true", result.ok === true);
  check(
    "successful output passes the real merged validator (schemaVersion is 1)",
    result.ok === true && result.comparison.schemaVersion === 1
  );
}

async function testTransientThenSuccess(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "raw", raw: validRaw() }]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient failure then success uses exactly 2 calls", calls.length === 2);
  check("transient failure then success returns ok:true", result.ok === true);
}

async function testInvalidThenSuccess(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: "not valid json {{{" },
    { kind: "raw", raw: validRaw() },
  ]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("malformed JSON then success uses exactly 2 calls", calls.length === 2);
  check("malformed JSON then success returns ok:true", result.ok === true);
}

async function testValidatorRejectionThenSuccess(): Promise<void> {
  const bad = cloneCandidate();
  (bad.dimensionFindings as Array<Record<string, unknown>>)[0].strongerSide = "not-a-real-side";

  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify(bad) },
    { kind: "raw", raw: validRaw() },
  ]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("validator-rejected output then success uses exactly 2 calls", calls.length === 2);
  check("validator-rejected output then success returns ok:true", result.ok === true);
  check(
    "the retry's user prompt carries one corrective instruction referencing the failure",
    calls[1].userPrompt.includes("IMPORTANT CORRECTION FOR THIS ATTEMPT") &&
      calls[1].userPrompt.includes("invalid_stronger_side")
  );
}

async function testBothInvalidNeverThirdCall(): Promise<void> {
  const bad = cloneCandidate();
  (bad.dimensionFindings as Array<Record<string, unknown>>)[0].strongerSide = "not-a-real-side";

  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify(bad) },
    { kind: "raw", raw: JSON.stringify(bad) },
  ]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("invalid->invalid uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "invalid->invalid returns the typed comparison_invalid_response failure",
    result.ok === false && result.code === "comparison_invalid_response"
  );
  check(
    "the public failure result carries only { ok, code } — no reason/detail field that could leak the internal validator code or the model's rejected value",
    !result.ok && Object.keys(result).sort().join(",") === "code,ok"
  );
}

async function testTransientThenInvalid(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "transient" },
    { kind: "raw", raw: "still not json" },
  ]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient->invalid uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "transient->invalid returns comparison_invalid_response",
    result.ok === false && result.code === "comparison_invalid_response"
  );
}

async function testInvalidThenTransient(): Promise<void> {
  const { caller, calls } = createStepCaller([
    { kind: "raw", raw: "not json" },
    { kind: "transient" },
  ]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("invalid->transient uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "invalid->transient returns comparison_unavailable",
    result.ok === false && result.code === "comparison_unavailable"
  );
}

async function testTransientThenTransient(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "transient" }]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });
  check("transient->transient uses exactly 2 calls, never a 3rd", calls.length === 2);
  check(
    "transient->transient returns the typed comparison_unavailable failure",
    result.ok === false && result.code === "comparison_unavailable"
  );
}

async function testRetryPromptDiscipline(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "transient" }, { kind: "raw", raw: validRaw() }]);
  await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check(
    "system/instruction prompt is byte-identical across attempt 1 and attempt 2",
    calls[0].systemPrompt === calls[1].systemPrompt
  );
  check(
    "buildSystemPrompt() is a pure function of no arguments (identical output every call)",
    buildSystemPrompt() === buildSystemPrompt()
  );

  const bad = cloneCandidate();
  (bad.dimensionFindings as Array<Record<string, unknown>>)[0].strongerSide = "not-a-real-side";
  const { caller: rejectCaller, calls: rejectCalls } = createStepCaller([
    { kind: "raw", raw: JSON.stringify(bad) },
    { kind: "raw", raw: validRaw() },
  ]);
  await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: rejectCaller,
  });
  check(
    "on a validator-rejection retry, the base user prompt is unchanged and only a corrective instruction is appended",
    rejectCalls[1].userPrompt.startsWith(rejectCalls[0].userPrompt) &&
      rejectCalls[1].userPrompt.length > rejectCalls[0].userPrompt.length
  );
}

async function testConfigConstants(): Promise<void> {
  check("model constant is exactly gpt-5.6-luna", COMPETITOR_COMPARISON_MODEL === "gpt-5.6-luna");
  check("reasoning effort constant is exactly low", COMPETITOR_COMPARISON_REASONING_EFFORT === "low");
  check("timeout constant is exactly 30000ms", COMPETITOR_COMPARISON_TIMEOUT_MS === 30_000);
  check(
    "max output tokens is a positive, independently-derived Compare-specific budget",
    COMPETITOR_COMPARISON_MAX_OUTPUT_TOKENS === 10_000
  );

  const providerSource = readFileSync("lib/competitor-scripts/comparison/provider.ts", "utf8");
  check(
    "no fallback model (gpt-5.6-sol / gpt-5.6-terra) is referenced anywhere in provider.ts",
    !providerSource.includes("gpt-5.6-sol") && !providerSource.includes("gpt-5.6-terra")
  );
  check(
    "model is a single fixed module-level constant, not selected per attempt",
    providerSource.includes('COMPETITOR_COMPARISON_MODEL = "gpt-5.6-luna"')
  );
}

async function testOversizedUserScriptRejectedBeforeAnyModelCall(): Promise<void> {
  const oversized = padUserScript(MAX_COMPARISON_USER_SCRIPT_CHARACTERS + 1);
  const { caller, calls } = createStepCaller([]);
  const result = await runCompetitorScriptComparison({
    userScript: oversized,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check("oversized user script makes zero model calls", calls.length === 0);
  check(
    "oversized user script returns the typed user_script_too_long_for_comparison failure",
    !result.ok &&
      result.code === "user_script_too_long_for_comparison" &&
      result.maxCharacters === MAX_COMPARISON_USER_SCRIPT_CHARACTERS &&
      result.actualCharacters === MAX_COMPARISON_USER_SCRIPT_CHARACTERS + 1
  );
  check(
    "the too-long result is exactly checkComparisonInputSize's own shape (reused, not a competing duplicate)",
    !result.ok && Object.keys(result).sort().join(",") === "actualCharacters,code,maxCharacters,ok"
  );
}

async function testOversizedCompetitorTranscriptRejectedBeforeAnyModelCall(): Promise<void> {
  const oversized = padCompetitorTranscript(MAX_COMPARISON_COMPETITOR_TRANSCRIPT_CHARACTERS + 1);
  const { caller, calls } = createStepCaller([]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: oversized,
    locale: "en",
    modelCaller: caller,
  });

  check("oversized competitor transcript makes zero model calls", calls.length === 0);
  check(
    "oversized competitor transcript returns the typed competitor_transcript_too_long_for_comparison failure",
    !result.ok &&
      result.code === "competitor_transcript_too_long_for_comparison" &&
      result.maxCharacters === MAX_COMPARISON_COMPETITOR_TRANSCRIPT_CHARACTERS &&
      result.actualCharacters === MAX_COMPARISON_COMPETITOR_TRANSCRIPT_CHARACTERS + 1
  );
}

async function testExactlyMaxCharactersAllowedThrough(): Promise<void> {
  const boundaryUserScript = padUserScript(MAX_COMPARISON_USER_SCRIPT_CHARACTERS);
  const { caller: callerA, calls: callsA } = createStepCaller([{ kind: "raw", raw: validRaw() }]);
  const resultA = await runCompetitorScriptComparison({
    userScript: boundaryUserScript,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: callerA,
  });
  check(
    "a user script of exactly the max character count reaches the model (1 call)",
    callsA.length === 1
  );
  check("exactly-max-length user script can still succeed", resultA.ok === true);

  const boundaryTranscript = padCompetitorTranscript(MAX_COMPARISON_COMPETITOR_TRANSCRIPT_CHARACTERS);
  const { caller: callerB, calls: callsB } = createStepCaller([{ kind: "raw", raw: validRaw() }]);
  const resultB = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: boundaryTranscript,
    locale: "en",
    modelCaller: callerB,
  });
  check(
    "a competitor transcript of exactly the max character count reaches the model (1 call)",
    callsB.length === 1
  );
  check("exactly-max-length competitor transcript can still succeed", resultB.ok === true);
}

async function testRealValidatorRejections(): Promise<void> {
  const cases: { name: string; patch: (c: Record<string, unknown>) => void }[] = [
    {
      name: "wrong dimension order",
      patch: (c) => {
        const findings = c.dimensionFindings as Array<Record<string, unknown>>;
        [findings[0], findings[1]] = [findings[1], findings[0]];
      },
    },
    {
      name: "generic feedback (lazy, ungrounded priority problem)",
      patch: (c) => {
        (c.priorities as Array<Record<string, unknown>>)[0].problem = "Make it more engaging.";
      },
    },
    {
      name: "unsupported numeric claim (a number absent from either source)",
      patch: (c) => {
        (c.dimensionFindings as Array<Record<string, unknown>>)[0].conclusion =
          "This lands around the 47th second mark for viewers.";
      },
    },
    {
      name: "unsupported evidence (excerpt not an exact user-script substring)",
      patch: (c) => {
        const findings = c.dimensionFindings as Array<Record<string, unknown>>;
        const originalEvidence = findings[0].evidence as { competitor: unknown };
        findings[0].evidence = {
          user: { source: "user", excerpt: "This phrase does not appear anywhere in the user script." },
          competitor: originalEvidence.competitor,
        };
      },
    },
  ];

  for (const testCase of cases) {
    const candidate = cloneCandidate();
    testCase.patch(candidate);
    const raw = JSON.stringify(candidate);

    const { caller, calls } = createStepCaller([
      { kind: "raw", raw },
      { kind: "raw", raw },
    ]);
    const result = await runCompetitorScriptComparison({
      userScript: USER_SCRIPT,
      competitorTranscript: COMPETITOR_TRANSCRIPT,
      locale: "en",
      modelCaller: caller,
    });

    check(`real validator rejects: ${testCase.name} (exactly 2 calls, never a 3rd)`, calls.length === 2);
    check(
      `real validator rejects: ${testCase.name} (typed comparison_invalid_response)`,
      result.ok === false && result.code === "comparison_invalid_response"
    );
  }
}

async function testEndMsNullSucceeds(): Promise<void> {
  const candidate = cloneCandidate();
  (candidate.dimensionFindings as Array<Record<string, unknown>>)[0].evidence = {
    user: { source: "user", excerpt: "a strong hook needs a shocking claim" },
    competitor: {
      source: "competitor",
      excerpt: "Here's what everyone gets wrong about hooks.",
      startMs: 3000,
      endMs: null,
    },
  };

  const { caller, calls } = createStepCaller([{ kind: "raw", raw: JSON.stringify(candidate) }]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check(
    "competitor evidence with endMs: null succeeds on the first attempt",
    calls.length === 1 && result.ok === true
  );
  check(
    "the validated comparison preserves endMs: null",
    result.ok === true && result.comparison.dimensionFindings[0].evidence.competitor.endMs === null
  );
}

async function testZeroCautionsSucceeds(): Promise<void> {
  const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw("en", 0) }]);
  const result = await runCompetitorScriptComparison({
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    locale: "en",
    modelCaller: caller,
  });

  check("zero cautions succeeds on the first attempt", calls.length === 1 && result.ok === true);
  check(
    "the validated comparison keeps an empty cautions array, not a manufactured one",
    result.ok === true && result.comparison.cautions.length === 0
  );
}

async function testLocales(): Promise<void> {
  for (const locale of ["en", "ru"] as const) {
    const { caller, calls } = createStepCaller([{ kind: "raw", raw: validRaw(locale) }]);
    const result = await runCompetitorScriptComparison({
      userScript: USER_SCRIPT,
      competitorTranscript: COMPETITOR_TRANSCRIPT,
      locale,
      modelCaller: caller,
    });

    check(`locale="${locale}" succeeds`, calls.length === 1 && result.ok === true);
    check(
      `locale="${locale}" keeps competitor evidence excerpts in the original transcript language/wording`,
      result.ok === true &&
        result.comparison.dimensionFindings[0].evidence.competitor.excerpt ===
          "Here's what everyone gets wrong about hooks."
    );
    check(
      `locale="${locale}" keeps user evidence excerpts in the original user-script language/wording`,
      result.ok === true &&
        result.comparison.dimensionFindings[0].evidence.user.excerpt === "a strong hook needs a shocking claim"
    );
  }
}

async function testPromptContent(): Promise<void> {
  const prompt = buildSystemPrompt();

  check(
    "prompt restricts grounding to both real sources only",
    prompt.includes("the only source of truth")
  );
  check(
    "prompt prohibits unsupported performance/virality claims for either script",
    prompt.includes("actual views") && prompt.includes("virality")
  );
  check(
    "prompt states there is no winner",
    prompt.includes("no winner")
  );
  check(
    "prompt prohibits visual/production claims (text-only sources)",
    prompt.includes("camera work") && prompt.includes("text only")
  );
  check(
    "prompt prohibits causal 'why it worked' claims",
    prompt.includes("this is why the video worked")
  );
  check(
    "prompt encodes the excerpt-verbatim rule",
    prompt.includes("every excerpt is verbatim") && prompt.includes("copied exactly, character for character")
  );
  check(
    "prompt states user evidence never carries a timestamp",
    prompt.includes("never carries a timestamp")
  );
  check(
    "prompt states the exact four dimensions in exact order",
    prompt.includes("hook, structure, momentum, payoff_clarity")
  );
  check(
    "prompt states gap is null exactly when strongerSide is similar",
    prompt.includes('strongerSide is "similar", gap must be exactly null')
  );
  check(
    "prompt requires evidence from both sides for every dimension",
    prompt.includes("a dimension finding is never one-sided")
  );
  check(
    "prompt explicitly allows zero cautions",
    prompt.includes("Zero cautions is a valid, often correct answer")
  );
  check(
    "prompt forbids instructing the user to copy competitor wording",
    prompt.includes("must never instruct the user to copy the competitor's exact wording")
  );
  check(
    "prompt never asks the model to produce sourceMeta",
    prompt.includes("Do not include a sourceMeta field") && prompt.includes("never asked to produce one")
  );
}

async function testSchemaAlignsWithConstants(): Promise<void> {
  const schema = COMPARISON_JSON_SCHEMA as {
    properties: {
      comparisonSummary: { properties: { headline: { maxLength: number }; mainTakeaway: { maxLength: number } } };
      dimensionFindings: { minItems: number; maxItems: number };
      priorities: { minItems: number; maxItems: number };
      cautions: { minItems: number; maxItems: number };
    };
  };

  check(
    "schema headline/mainTakeaway maxLength match constants.ts (not duplicated numbers)",
    schema.properties.comparisonSummary.properties.headline.maxLength === MAX_HEADLINE_LENGTH &&
      schema.properties.comparisonSummary.properties.mainTakeaway.maxLength === MAX_MAIN_TAKEAWAY_LENGTH
  );
  check(
    "schema dimensionFindings array is fixed at exactly REQUIRED_DIMENSION_COUNT",
    schema.properties.dimensionFindings.minItems === REQUIRED_DIMENSION_COUNT &&
      schema.properties.dimensionFindings.maxItems === REQUIRED_DIMENSION_COUNT
  );
  check(
    "schema priorities array bounds match constants.ts",
    schema.properties.priorities.minItems === MIN_PRIORITIES &&
      schema.properties.priorities.maxItems === MAX_PRIORITIES
  );
  check(
    "schema cautions array bounds match constants.ts",
    schema.properties.cautions.minItems === MIN_CAUTIONS && schema.properties.cautions.maxItems === MAX_CAUTIONS
  );
}

async function testSchemaStrictShape(): Promise<void> {
  const schema = COMPARISON_JSON_SCHEMA as Record<string, unknown> & {
    additionalProperties: boolean;
    required: string[];
    properties: {
      schemaVersion: Record<string, unknown>;
      dimensionFindings: {
        items: {
          additionalProperties: boolean;
          required: string[];
          properties: {
            gap: { anyOf: Array<Record<string, unknown>> };
            evidence: {
              additionalProperties: boolean;
              required: string[];
              properties: {
                competitor: {
                  additionalProperties: boolean;
                  required: string[];
                  properties: { endMs: { type: string[] } };
                };
              };
            };
          };
        };
      };
      cautions: {
        items: {
          properties: {
            evidence: {
              properties: { user: { anyOf: Array<Record<string, unknown>> } };
            };
          };
        };
      };
    };
  };

  check("top-level schema forbids additional properties", schema.additionalProperties === false);
  check(
    "top-level required list has exactly the 6 approved fields, no sourceMeta",
    schema.required.sort().join(",") ===
      "comparisonSummary,cautions,dimensionFindings,locale,priorities,schemaVersion".split(",").sort().join(",")
  );
  check("schemaVersion is a fixed-1 enum, not a free integer", (schema.properties.schemaVersion as { enum: number[] }).enum.join(",") === "1");

  const dimensionSchema = schema.properties.dimensionFindings.items;
  check("dimension-finding object forbids additional properties", dimensionSchema.additionalProperties === false);
  check(
    "dimension-finding evidence object forbids additional properties and requires both sides",
    dimensionSchema.properties.evidence.additionalProperties === false &&
      dimensionSchema.properties.evidence.required.sort().join(",") === "competitor,user"
  );
  check(
    "gap is expressed as a required, nullable anyOf (not an untested type-array+null-enum combination)",
    Array.isArray(dimensionSchema.properties.gap.anyOf) && dimensionSchema.properties.gap.anyOf.length === 2
  );
  check(
    "competitor evidence endMs is a required, nullable integer (type array, matching Analyze's own nullableInteger())",
    dimensionSchema.properties.evidence.properties.competitor.properties.endMs.type.sort().join(",") ===
      "integer,null"
  );
  check(
    "competitor evidence object forbids additional properties",
    dimensionSchema.properties.evidence.properties.competitor.additionalProperties === false
  );

  const cautionSchema = schema.properties.cautions.items;
  check(
    "caution evidence.user is a required, nullable anyOf (mirrors Analyze's nullableEvidenceSchema)",
    Array.isArray(cautionSchema.properties.evidence.properties.user.anyOf) &&
      cautionSchema.properties.evidence.properties.user.anyOf.length === 2
  );
}

async function testNoUnsafeLogging(): Promise<void> {
  const providerSource = readFileSync("lib/competitor-scripts/comparison/provider.ts", "utf8");

  check(
    "provider.ts introduces no console logging at all (nothing to leak a secret/script/transcript/raw response through)",
    !providerSource.includes("console.log(") &&
      !providerSource.includes("console.error(") &&
      !providerSource.includes("console.warn(")
  );
  const providerCodeOnly = providerSource
    .split("\n")
    .filter((line) => !line.trim().startsWith("//"))
    .join("\n");
  check(
    "provider.ts never reads process.env directly in actual code (API key stays fully dependency-injected — comments mentioning it are fine)",
    !providerCodeOnly.includes("process.env")
  );
}

async function testSizeCheckHelperDirectly(): Promise<void> {
  const ok = checkComparisonInputSize({ userScript: USER_SCRIPT, competitorTranscript: COMPETITOR_TRANSCRIPT });
  check("checkComparisonInputSize accepts in-bounds inputs directly", ok.ok === true);
}

async function main() {
  await testValidFirstAttempt();
  await testTransientThenSuccess();
  await testInvalidThenSuccess();
  await testValidatorRejectionThenSuccess();
  await testBothInvalidNeverThirdCall();
  await testTransientThenInvalid();
  await testInvalidThenTransient();
  await testTransientThenTransient();
  await testRetryPromptDiscipline();
  await testConfigConstants();
  await testOversizedUserScriptRejectedBeforeAnyModelCall();
  await testOversizedCompetitorTranscriptRejectedBeforeAnyModelCall();
  await testExactlyMaxCharactersAllowedThrough();
  await testRealValidatorRejections();
  await testEndMsNullSucceeds();
  await testZeroCautionsSucceeds();
  await testLocales();
  await testPromptContent();
  await testSchemaAlignsWithConstants();
  await testSchemaStrictShape();
  await testNoUnsafeLogging();
  await testSizeCheckHelperDirectly();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log("\nResult: all Competitor Scripts Compare Provider tests passed.");
  }
}

void main();
