import { readFileSync } from "node:fs";
import { getMessages } from "../lib/messages";
import {
  ANALYZE_RESULT_STORAGE_KEY,
  validateStoredAnalyzeResult,
  type StoredAnalyzeResult,
} from "../lib/competitor-scripts/analyze-result-storage";
import {
  MAX_LANGUAGE_CODE_LENGTH,
  MAX_SEGMENT_TEXT_LENGTH,
  MAX_SEGMENTS,
  MAX_TRANSCRIPT_TEXT_LENGTH,
} from "../lib/competitor-scripts/transcript/normalize";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Analyze Frontend Tests\n");

// ── validateStoredAnalyzeResult: pure-function, untrusted-input tests ──────

const VALID_RESULT: StoredAnalyzeResult = {
  v: 1,
  createdAt: 1_700_000_000_000,
  input: {
    videoId: "dQw4w9WgXcQ",
    canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    sourceFormat: "watch",
  },
  transcript: {
    languageCode: "en",
    isAutoGenerated: true,
    segments: [
      { text: "Hello there.", startMs: 0, durationMs: 1200 },
      { text: "General Kenobi.", startMs: 1200, durationMs: null },
    ],
    text: "Hello there. General Kenobi.",
    durationMs: 2400,
  },
};

function testValidator() {
  check(
    "a valid, well-formed payload is accepted",
    validateStoredAnalyzeResult(VALID_RESULT) !== null
  );

  check(
    "a valid payload with languageCode/isAutoGenerated/durationMs all null is accepted",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        languageCode: null,
        isAutoGenerated: null,
        durationMs: null,
      },
    }) !== null
  );

  check(
    "a payload with an empty segments array is accepted",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, segments: [] },
    }) !== null
  );

  for (const notAnObject of [null, undefined, "a string", 42, [], true]) {
    check(
      `a non-object top-level value (${JSON.stringify(notAnObject)}) is rejected`,
      validateStoredAnalyzeResult(notAnObject) === null
    );
  }

  check(
    "a wrong storage version is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, v: 2 }) === null
  );

  check(
    "a non-numeric createdAt is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, createdAt: "yesterday" }) ===
      null
  );

  check(
    "a missing input object is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, input: undefined }) ===
      null
  );

  check(
    "a malformed videoId (wrong length/characters) is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: { ...VALID_RESULT.input, videoId: "not-a-real-id!" },
    }) === null
  );

  check(
    "a canonicalUrl that doesn't match videoId is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: {
        ...VALID_RESULT.input,
        canonicalUrl: "https://www.youtube.com/watch?v=differentId1",
      },
    }) === null
  );

  check(
    "a canonicalUrl that isn't a YouTube URL at all is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: {
        ...VALID_RESULT.input,
        canonicalUrl: "https://example.com/not-youtube",
      },
    }) === null
  );

  check(
    "an invalid sourceFormat is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      input: { ...VALID_RESULT.input, sourceFormat: "embed" },
    }) === null
  );

  check(
    "a missing transcript object is rejected",
    validateStoredAnalyzeResult({ ...VALID_RESULT, transcript: undefined }) ===
      null
  );

  check(
    "segments that are not an array are rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, segments: "not an array" },
    }) === null
  );

  check(
    "a segment missing required fields is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "no startMs here" }],
      },
    }) === null
  );

  check(
    "a segment with a negative startMs is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "bad", startMs: -1, durationMs: null }],
      },
    }) === null
  );

  check(
    "a segment with non-finite startMs (Infinity) is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [{ text: "bad", startMs: Infinity, durationMs: null }],
      },
    }) === null
  );

  check(
    "a segment with text longer than MAX_SEGMENT_TEXT_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: [
          {
            text: "x".repeat(MAX_SEGMENT_TEXT_LENGTH + 1),
            startMs: 0,
            durationMs: null,
          },
        ],
      },
    }) === null
  );

  check(
    "more segments than MAX_SEGMENTS is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        segments: Array.from({ length: MAX_SEGMENTS + 1 }, (_, index) => ({
          text: "x",
          startMs: index,
          durationMs: null,
        })),
      },
    }) === null
  );

  check(
    "transcript text longer than MAX_TRANSCRIPT_TEXT_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        text: "x".repeat(MAX_TRANSCRIPT_TEXT_LENGTH + 1),
      },
    }) === null
  );

  check(
    "a languageCode longer than MAX_LANGUAGE_CODE_LENGTH is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: {
        ...VALID_RESULT.transcript,
        languageCode: "x".repeat(MAX_LANGUAGE_CODE_LENGTH + 1),
      },
    }) === null
  );

  check(
    "a non-boolean, non-null isAutoGenerated is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, isAutoGenerated: "yes" },
    }) === null
  );

  check(
    "a negative durationMs is rejected",
    validateStoredAnalyzeResult({
      ...VALID_RESULT,
      transcript: { ...VALID_RESULT.transcript, durationMs: -100 },
    }) === null
  );

  const withExtraField = validateStoredAnalyzeResult({
    ...VALID_RESULT,
    somethingUnexpected: "should be dropped, not trusted",
  } as unknown);
  check(
    "an accepted payload with an unknown extra top-level field is validated by reconstruction — the extra field never survives into the returned object",
    withExtraField !== null &&
      !Object.prototype.hasOwnProperty.call(
        withExtraField,
        "somethingUnexpected"
      )
  );

  check(
    "an accepted payload never carries provider-only fields (apiKey/provider) even if injected",
    (() => {
      const tampered = {
        ...VALID_RESULT,
        transcript: {
          ...VALID_RESULT.transcript,
          apiKey: "sk-should-never-appear",
          provider: "supadata",
        },
      };
      const result = validateStoredAnalyzeResult(tampered);
      return (
        result !== null &&
        !JSON.stringify(result).toLowerCase().includes("apikey") &&
        !JSON.stringify(result).toLowerCase().includes("supadata")
      );
    })()
  );
}

// ── sessionStorage round-trip (read/write) with a fake browser storage ────

function testStorageRoundTrip() {
  class FakeSessionStorage {
    private store = new Map<string, string>();
    getItem(key: string): string | null {
      return this.store.has(key) ? this.store.get(key)! : null;
    }
    setItem(key: string, value: string): void {
      this.store.set(key, value);
    }
    removeItem(key: string): void {
      this.store.delete(key);
    }
    clear(): void {
      this.store.clear();
    }
  }

  return (async () => {
    const fakeStorage = new FakeSessionStorage();
    (globalThis as { sessionStorage?: unknown }).sessionStorage = fakeStorage;

    const { readStoredAnalyzeResult, writeStoredAnalyzeResult } =
      await import("../lib/competitor-scripts/analyze-result-storage");

    check(
      "reading with nothing stored returns null, never throws",
      readStoredAnalyzeResult() === null
    );

    fakeStorage.setItem(ANALYZE_RESULT_STORAGE_KEY, "{not valid json");
    check(
      "reading malformed JSON returns null, never throws",
      readStoredAnalyzeResult() === null
    );

    fakeStorage.setItem(
      ANALYZE_RESULT_STORAGE_KEY,
      JSON.stringify({ v: 1, tampered: true })
    );
    check(
      "reading a structurally-invalid-but-valid-JSON value returns null",
      readStoredAnalyzeResult() === null
    );

    writeStoredAnalyzeResult({
      input: VALID_RESULT.input,
      transcript: VALID_RESULT.transcript,
    });
    const roundTripped = readStoredAnalyzeResult();
    check(
      "a value written by writeStoredAnalyzeResult reads back as valid",
      roundTripped !== null &&
        roundTripped.input.videoId === VALID_RESULT.input.videoId &&
        roundTripped.transcript.text === VALID_RESULT.transcript.text
    );

    const otherResult: StoredAnalyzeResult["input"] = {
      videoId: "dQw4w9WgXcR",
      canonicalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcR",
      sourceFormat: "watch",
    };
    writeStoredAnalyzeResult({
      input: otherResult,
      transcript: { ...VALID_RESULT.transcript, text: "A second video." },
    });
    const overwritten = readStoredAnalyzeResult();
    check(
      "a new successful write overwrites the previous stored result rather than merging with it",
      overwritten !== null &&
        overwritten.input.videoId === "dQw4w9WgXcR" &&
        overwritten.transcript.text === "A second video."
    );
  })();
}

// ── structural checks: submission flow, storage usage, no leaked internals ─

function testStructural() {
  const analyzeFormSource = readFileSync(
    "app/competitor-scripts/analyze/analyze-input-form.tsx",
    "utf8"
  );
  const storageModuleSource = readFileSync(
    "lib/competitor-scripts/analyze-result-storage.ts",
    "utf8"
  );
  const resultsContentSource = readFileSync(
    "app/competitor-scripts/analyze/results/analyze-results-content.tsx",
    "utf8"
  );
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const compareFormSource = readFileSync(
    "app/competitor-scripts/compare/compare-input-form.tsx",
    "utf8"
  );

  check(
    "on a failed submission, the previously entered URL is never cleared (no setUrl call in the failure branch)",
    !/setError\([^)]*apiErrors[\s\S]{0,200}setUrl\(/.test(analyzeFormSource)
  );

  check(
    "writeStoredAnalyzeResult is only ever called from the validated-success branch, not from the failure branch",
    /isValidSuccessPayload\(payload\)\)\s*\{[\s\S]{0,400}writeStoredAnalyzeResult\(/.test(
      analyzeFormSource
    )
  );

  check(
    "the storage module never imports the server-only Supadata provider",
    !storageModuleSource.includes("supadata-provider")
  );

  check(
    "the storage module reuses the server transcript normalizer's bounds rather than redefining its own limits",
    storageModuleSource.includes(
      '"@/lib/competitor-scripts/transcript/normalize"'
    ) &&
      storageModuleSource.includes("MAX_SEGMENTS") &&
      storageModuleSource.includes("MAX_SEGMENT_TEXT_LENGTH") &&
      storageModuleSource.includes("MAX_TRANSCRIPT_TEXT_LENGTH")
  );

  check(
    "AnalyzeResultsContent starts in a loading state (avoids a server/client hydration mismatch, since sessionStorage is only readable after mount)",
    /useState<ContentState>\(\{\s*status:\s*"loading"\s*\}\)/.test(
      resultsContentSource
    )
  );

  check(
    "AnalyzeResultsContent reads sessionStorage inside a mount-only effect (empty dependency array), not during render",
    /useEffect\(\(\)\s*=>\s*\{[\s\S]{0,500}readStoredAnalyzeResult\(\)[\s\S]{0,300}\},\s*\[\]\)/.test(
      resultsContentSource
    )
  );

  check(
    "the sessionStorage read is deferred via a cleaned-up zero-delay timer (matching the repo's react-hooks/set-state-in-effect-safe convention), not a fake multi-stage delay",
    /window\.setTimeout\([\s\S]{0,300}\},\s*0\)/.test(resultsContentSource) &&
      /window\.clearTimeout\(timer\)/.test(resultsContentSource)
  );

  check(
    "the illustrative score/analysis report is only rendered in the 'ready' branch — the 'missing' branch renders none of ScoreOverview/MainTakeaway/ScriptBreakdown",
    (() => {
      const missingBranchMatch = resultsContentSource.match(
        /state\.status === "missing"\) \{([\s\S]*?)\n {2}\}/
      );
      if (!missingBranchMatch) return false;
      const missingBranch = missingBranchMatch[1];
      return (
        !missingBranch.includes("<ScoreOverview") &&
        !missingBranch.includes("<MainTakeaway") &&
        !missingBranch.includes("<ScriptBreakdown") &&
        !missingBranch.includes("<ResultsSummary")
      );
    })()
  );

  check(
    "the transcript section renders segment/full text via plain JSX expressions, never through a raw-HTML injection prop",
    /\{data\.text\}/.test(transcriptSectionSource) &&
      !transcriptSectionSource.includes("dangerouslySetInnerHTML")
  );

  check(
    "no OpenAI reference exists anywhere in the new/changed frontend wiring files",
    ![
      analyzeFormSource,
      storageModuleSource,
      resultsContentSource,
      transcriptSectionSource,
    ].some((source) => /openai/i.test(source))
  );

  check(
    "no Supabase reference exists anywhere in the new/changed frontend wiring files",
    ![
      analyzeFormSource,
      storageModuleSource,
      resultsContentSource,
      transcriptSectionSource,
    ].some((source) => /supabase/i.test(source))
  );

  check(
    "the Compare feature was not touched by this PR's storage/API wiring — it references neither the analyze API route nor the new storage module",
    !compareFormSource.includes("/api/competitor-scripts/analyze") &&
      !compareFormSource.includes("analyze-result-storage")
  );

  const packageJson = readFileSync("package.json", "utf8");
  check(
    "no new dependency was added to package.json for this frontend wiring (no zod/uuid/axios/swr/react-query introduced)",
    !/"zod"|"uuid"|"axios"|"swr"|"react-query"/.test(packageJson)
  );
}

// ── visual-polish round: real video embed, density, progressive disclosure ─

function testVisualPolishRound() {
  const embedSource = readFileSync(
    "app/competitor-scripts/analyze/results/youtube-embed.tsx",
    "utf8"
  );
  const resultsSummarySource = readFileSync(
    "app/competitor-scripts/analyze/results/results-summary.tsx",
    "utf8"
  );
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const analyzeApiRouteSource = readFileSync(
    "app/api/competitor-scripts/analyze/route.ts",
    "utf8"
  );
  const compareFormSource = readFileSync(
    "app/competitor-scripts/compare/compare-input-form.tsx",
    "utf8"
  );
  const enSummary = getMessages("en").competitorScripts.analyzeResults.summary;
  const ruSummary = getMessages("ru").competitorScripts.analyzeResults.summary;
  const enTranscript =
    getMessages("en").competitorScripts.analyzeResults.transcript;
  const ruTranscript =
    getMessages("ru").competitorScripts.analyzeResults.transcript;

  check(
    "the iframe src is built strictly from the videoId prop, never from canonicalUrl or any other field",
    /src=\{`https:\/\/www\.youtube\.com\/embed\/\$\{videoId\}`\}/.test(
      embedSource
    ) && !embedSource.includes("canonicalUrl")
  );

  check(
    "the embed re-validates videoId shape itself (defense in depth) before constructing the URL",
    embedSource.includes("isValidYouTubeVideoId(videoId)")
  );

  check(
    "the embed host and path are a fixed literal (youtube.com/embed/), not derived from any arbitrary/dynamic base",
    /https:\/\/www\.youtube\.com\/embed\//.test(embedSource)
  );

  check(
    "the embed URL carries no query string at all — no autoplay, no mute, no custom params (YouTube's own safe defaults apply)",
    !/embed\/\$\{videoId\}[^`]*\?/.test(embedSource) &&
      !/autoplay|[^a-z]mute[^a-z]/i.test(embedSource)
  );

  check(
    "the embed frame uses a 9:16 aspect ratio",
    /aspectRatio:\s*["']9 \/ 16["']/.test(embedSource)
  );

  check(
    "the embed allows fullscreen and has a meaningful (non-empty, localized) title prop wired through",
    embedSource.includes("allowFullScreen") &&
      embedSource.includes("title={title}") &&
      resultsSummarySource.includes("title={summary.embedTitle}") &&
      enSummary.embedTitle.length > 0 &&
      ruSummary.embedTitle.length > 0
  );

  check(
    "the embed is lazy-loaded",
    /loading="lazy"/.test(embedSource)
  );

  check(
    "ResultsSummary renders the real video via YouTubeEmbed, not a placeholder icon/thumbnail",
    resultsSummarySource.includes("<YouTubeEmbed") &&
      !resultsSummarySource.includes("PlayCircle")
  );

  check(
    "the submitted-video card's duration label reads 'transcript duration', never 'video duration', in both locales",
    /transcript duration/i.test(enSummary.durationLabel) &&
      !/video duration/i.test(enSummary.durationLabel) &&
      /транскрипта/i.test(ruSummary.durationLabel)
  );

  check(
    "the transcript section's duration label also reads 'transcript duration', consistent with the summary card",
    /transcript duration/i.test(enTranscript.durationLabel) &&
      /транскрипта/i.test(ruTranscript.durationLabel)
  );

  check(
    "the summary copy never introduces fabricated engagement/metadata keys (views/likes/comments/channel/subscribers/uploadDate/publishedAt)",
    !/views|likes|comments|channel|subscribers|uploadDate|publishedAt/i.test(
      Object.keys(enSummary).join(" ")
    )
  );

  check(
    "ResultsSummary links out to the real, already-validated canonical URL via a safe target=_blank + rel=noopener noreferrer anchor",
    /href=\{data\.canonicalUrl\}/.test(resultsSummarySource) &&
      resultsSummarySource.includes('target="_blank"') &&
      resultsSummarySource.includes('rel="noopener noreferrer"')
  );

  check(
    "the timestamped segment list is initially limited to a small preview count (5-8) rather than rendering everything at once",
    (() => {
      const match = transcriptSectionSource.match(
        /SEGMENT_PREVIEW_COUNT = (\d+)/
      );
      const count = match ? Number(match[1]) : NaN;
      return count >= 5 && count <= 8;
    })() &&
      transcriptSectionSource.includes(
        "data.segments.slice(0, SEGMENT_PREVIEW_COUNT)"
      )
  );

  check(
    "'Show all segments' expands the list and 'Show fewer' collapses it back, via real toggled state — not two separate static lists",
    /setShowAllSegments\(\(current\)\s*=>\s*!current\)/.test(
      transcriptSectionSource
    ) &&
      transcriptSectionSource.includes(
        "showAllSegments ? copy.showFewerSegments : copy.showAllSegments"
      )
  );

  check(
    "the segment expand/collapse control is a real, keyboard-accessible button with aria-expanded reflecting its state",
    /<button\s+type="button"[\s\S]{0,120}aria-expanded=\{showAllSegments\}/.test(
      transcriptSectionSource
    )
  );

  check(
    "the full transcript text is never gated behind the segment expand/collapse state (only the timestamped list is)",
    !/showAllSegments[\s\S]{0,80}data\.text/.test(transcriptSectionSource)
  );

  check(
    "EN/RU expose matching show-all/show-fewer segment copy, non-empty in both locales",
    enTranscript.showAllSegments.length > 0 &&
      enTranscript.showFewerSegments.length > 0 &&
      ruTranscript.showAllSegments.length > 0 &&
      ruTranscript.showFewerSegments.length > 0
  );

  check(
    "the real-data vs illustrative-preview section grouping labels exist and differ, in both locales",
    getMessages("en").competitorScripts.analyzeResults.sectionGroups.realData !==
      getMessages("en").competitorScripts.analyzeResults.sectionGroups
        .exampleAnalysis &&
      getMessages("ru").competitorScripts.analyzeResults.sectionGroups
        .realData.length > 0 &&
      getMessages("ru").competitorScripts.analyzeResults.sectionGroups
        .exampleAnalysis.length > 0
  );

  check(
    "no dangerouslySetInnerHTML was introduced by the visual-polish round (transcript/embed remain plain React text/attributes)",
    !embedSource.includes("dangerouslySetInnerHTML") &&
      !resultsSummarySource.includes("dangerouslySetInnerHTML") &&
      !transcriptSectionSource.includes("dangerouslySetInnerHTML")
  );

  check(
    "the illustrative 'real transcript' / 'from your submitted video' style labeling still exists on the transcript section",
    transcriptSectionSource.includes("{copy.realDataLabel}") &&
      /from your submitted video/i.test(enTranscript.sectionEyebrow)
  );

  check(
    "the analyze API route was not touched by this visual-polish round — it references none of the new results components",
    !analyzeApiRouteSource.includes("youtube-embed") &&
      !analyzeApiRouteSource.includes("results-summary") &&
      !analyzeApiRouteSource.includes("transcript-section")
  );

  check(
    "Compare still does not reference the YouTube embed or the results feature",
    !compareFormSource.includes("youtube-embed") &&
      !compareFormSource.includes("results-summary") &&
      !compareFormSource.includes("YouTubeEmbed")
  );
}

// ── final polish round: corrected top copy, no fake "Source: Unknown",  ──
// ── no visible raw URL, no redundant preview badge                     ──

function testFinalPolishRound() {
  const transcriptSectionSource = readFileSync(
    "app/competitor-scripts/analyze/results/transcript-section.tsx",
    "utf8"
  );
  const resultsSummarySource = readFileSync(
    "app/competitor-scripts/analyze/results/results-summary.tsx",
    "utf8"
  );
  const scriptBreakdownSource = readFileSync(
    "app/competitor-scripts/analyze/results/script-breakdown.tsx",
    "utf8"
  );
  const enResults = getMessages("en").competitorScripts.analyzeResults;
  const ruResults = getMessages("ru").competitorScripts.analyzeResults;

  check(
    "the top subtitle explicitly distinguishes the real video/transcript from preview scores, and never claims the transcript is illustrative",
    /preview/i.test(enResults.description) &&
      !/transcript.{0,40}(illustrative|preview|example)/i.test(
        enResults.description
      )
  );

  check(
    "the preview banner explicitly states the video/transcript are real and the scores/insights are the preview data, not the other way around",
    /video and transcript are real/i.test(enResults.previewNotice) &&
      /scores and insights are.{0,20}(preview|example)/i.test(
        enResults.previewNotice
      )
  );

  check(
    "the generation ('Source') transcript stat is only ever added to the stats array when isAutoGenerated is known — never a hardcoded 'Unknown' fallback entry",
    transcriptSectionSource.includes(
      "...(data.isAutoGenerated !== null"
    ) && !transcriptSectionSource.includes("unknownGenerationLabel")
  );

  check(
    "the transcript stats grid degrades to 3 columns when the generation stat is omitted, instead of leaving a visibly empty 4th slot",
    transcriptSectionSource.includes('stats.length >= 4 ? "sm:grid-cols-4"') &&
      transcriptSectionSource.includes('"sm:grid-cols-3"')
  );

  check(
    "the raw canonical URL is no longer rendered as visible text on the submitted-video card — only the 'Open on YouTube' action link remains, with the URL preserved for accessibility via aria-label",
    !/<p[^>]*>[\s\S]{0,80}canonicalUrl/.test(resultsSummarySource) &&
      resultsSummarySource.includes(
        "aria-label={`${summary.openOnYouTube}: ${data.canonicalUrl}`}"
      )
  );

  check(
    "canonicalUrl itself is still read from the stored result and used (for the link + accessible name) — it was only removed from permanent visible display, never dropped from the data flow",
    resultsSummarySource.includes("data.canonicalUrl")
  );

  check(
    "the metadata column next to the real video is width-capped rather than stretching to fill the whole card (flex-1 removed)",
    resultsSummarySource.includes("max-w-[300px]") &&
      !resultsSummarySource.includes("flex-1")
  );

  check(
    "the 9:16 video column width was not touched by this polish round",
    resultsSummarySource.includes("max-w-[200px] shrink-0 sm:w-[200px]")
  );

  check(
    "Script Structure no longer shows both a sectionEyebrow ending in '· Example analysis preview' and a separate duplicate preview badge — only the eyebrow remains",
    scriptBreakdownSource.includes("{timeline.sectionEyebrow}") &&
      !scriptBreakdownSource.includes("{timeline.illustrativeLabel}") &&
      !("illustrativeLabel" in enResults.timeline)
  );

  check(
    "the segment expand/collapse control remains a real, keyboard-accessible button with aria-expanded and the same 6-segment preview logic",
    transcriptSectionSource.includes('<button\n              type="button"') &&
      transcriptSectionSource.includes("aria-expanded={showAllSegments}") &&
      transcriptSectionSource.includes("SEGMENT_PREVIEW_COUNT = 6")
  );

  check(
    "EN/RU still expose matching, non-empty top subtitle and banner copy after the rewrite",
    enResults.description.length > 0 &&
      enResults.previewNotice.length > 0 &&
      ruResults.description.length > 0 &&
      ruResults.previewNotice.length > 0 &&
      enResults.description !== ruResults.description &&
      enResults.previewNotice !== ruResults.previewNotice
  );
}

async function main() {
  testValidator();
  await testStorageRoundTrip();
  testStructural();
  testVisualPolishRound();
  testFinalPolishRound();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log(
      "\nResult: all Competitor Scripts Analyze Frontend tests passed."
    );
  }
}

void main();
