import type { NormalizedTranscript } from "../lib/competitor-scripts/transcript/types";
import { validateCompetitorScriptComparison } from "../lib/competitor-scripts/comparison/validate";
import {
  findCausalClaimViolation,
  findRankingClaimViolation,
  findUnsupportedIntentClaim,
  findUnsupportedNumericClaimAcrossSources,
  findUnsupportedProductionClaim,
  findUnsupportedQuotedSpanAcrossSources,
  findVerbatimCompetitorCopy,
} from "../lib/competitor-scripts/comparison/grounding";
import type {
  Caution,
  CompetitorScriptComparison,
  CompetitorTranscriptEvidence,
  DimensionFinding,
  Priority,
  UserScriptEvidence,
} from "../lib/competitor-scripts/comparison/types";

let failures = 0;

function check(name: string, condition: boolean): void {
  if (condition) {
    console.log(`✅ PASS — ${name}`);
  } else {
    console.error(`❌ FAIL — ${name}`);
    failures += 1;
  }
}

console.log("\nCompetitor Scripts Compare Foundation Tests\n");

// ── Fixture sources ─────────────────────────────────────────────────────
// One short user script and one small competitor transcript, deliberately
// sharing the number "3" ("3 words" / "3 steps") so a supported-number
// test has something real to point to on both sides — any other digit is
// automatically unsupported by either source.

const USER_SCRIPT =
  "Everyone thinks a strong hook needs a shocking claim, but that is the mistake. " +
  "I open with a plain observation instead, then explain why it matters in 3 words. " +
  "Most creators rush straight to the payoff before earning it. " +
  "I reveal the answer almost immediately after the setup.";

const COMPETITOR_SEGMENTS = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about hooks.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 6000, durationMs: 3000 },
  { text: "I hold the tension for four extra lines before I answer the question.", startMs: 9000, durationMs: 3000 },
  { text: "Once you see it, you cannot unsee it.", startMs: 12000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 15000, durationMs: 3000 },
];

const COMPETITOR_TRANSCRIPT: NormalizedTranscript = {
  videoId: "dQw4w9WgXcQ",
  languageCode: "en",
  isAutoGenerated: true,
  segments: COMPETITOR_SEGMENTS,
  text: COMPETITOR_SEGMENTS.map((segment) => segment.text).join(" "),
  durationMs: 18000,
};

// A variant with a deliberate 1000ms gap between segment 2 and segment 3
// (segment 2 ends at 6000, segment 3 starts at 7000) — COMPETITOR_TRANSCRIPT's
// own segments are perfectly contiguous, so a real "falls in the gap"
// case needs its own fixture, same approach as the Analyze foundation test.
const COMPETITOR_SEGMENTS_WITH_GAP = [
  { text: "Wait, this one mistake is costing you views.", startMs: 0, durationMs: 3000 },
  { text: "Here's what everyone gets wrong about hooks.", startMs: 3000, durationMs: 3000 },
  { text: "So here is the fix in 3 steps.", startMs: 7000, durationMs: 3000 },
  { text: "I hold the tension for four extra lines before I answer the question.", startMs: 10000, durationMs: 3000 },
  { text: "Once you see it, you cannot unsee it.", startMs: 13000, durationMs: 3000 },
  { text: "Try this on your next video.", startMs: 16000, durationMs: 3000 },
];

const COMPETITOR_TRANSCRIPT_WITH_GAP: NormalizedTranscript = {
  ...COMPETITOR_TRANSCRIPT,
  segments: COMPETITOR_SEGMENTS_WITH_GAP,
  text: COMPETITOR_SEGMENTS_WITH_GAP.map((segment) => segment.text).join(" "),
  durationMs: 19000,
};

function userEvidence(excerpt: string): UserScriptEvidence {
  return { source: "user", excerpt };
}

function competitorEvidence(excerpt: string, startMs: number, endMs: number | null): CompetitorTranscriptEvidence {
  return { source: "competitor", excerpt, startMs, endMs };
}

const UE_HOOK = "a strong hook needs a shocking claim";
const UE_STRUCTURE = "Most creators rush straight to the payoff before earning it.";
const UE_MOMENTUM = "I open with a plain observation instead";
const UE_PAYOFF = "I reveal the answer almost immediately after the setup.";

const CE_HOOK = { excerpt: "Here's what everyone gets wrong about hooks.", startMs: 3000, endMs: 6000 };
const CE_STRUCTURE = { excerpt: "So here is the fix in 3 steps.", startMs: 6000, endMs: 9000 };
const CE_MOMENTUM = { excerpt: "I hold the tension for four extra lines before I answer the question.", startMs: 9000, endMs: 12000 };
const CE_PAYOFF = { excerpt: "Once you see it, you cannot unsee it.", startMs: 12000, endMs: 15000 };

function dimensionFindingsFixture(): DimensionFinding[] {
  return [
    {
      dimension: "hook",
      strongerSide: "competitor",
      gap: "meaningful",
      conclusion: "Their hook names the mistake immediately, while yours states the premise more gently.",
      userObservation: "Your opening states the premise as a broad claim.",
      competitorObservation: "Their opening names the specific mistake right away.",
      evidence: { user: userEvidence(UE_HOOK), competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs) },
    },
    {
      dimension: "structure",
      strongerSide: "similar",
      gap: null,
      conclusion: "Both scripts move through a comparable number of story beats.",
      userObservation: "Your structure moves from premise to payoff in a few clear steps.",
      competitorObservation: "Their structure also moves through a short, numbered sequence.",
      evidence: { user: userEvidence(UE_STRUCTURE), competitor: competitorEvidence(CE_STRUCTURE.excerpt, CE_STRUCTURE.startMs, CE_STRUCTURE.endMs) },
    },
    {
      dimension: "momentum",
      strongerSide: "user",
      gap: "small",
      conclusion: "Yours moves into the observation slightly faster after the premise.",
      userObservation: "Your script moves directly into the observation without a detour.",
      competitorObservation: "Their script holds an extra beat before moving forward.",
      evidence: { user: userEvidence(UE_MOMENTUM), competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs) },
    },
    {
      dimension: "payoff_clarity",
      strongerSide: "competitor",
      gap: "large",
      conclusion: "Their payoff lands as a distinct beat, while yours arrives without a clear turn.",
      userObservation: "Your answer arrives immediately, without a signal that it has landed.",
      competitorObservation: "Their payoff is set apart by a short beat that signals the reveal.",
      evidence: { user: userEvidence(UE_PAYOFF), competitor: competitorEvidence(CE_PAYOFF.excerpt, CE_PAYOFF.startMs, CE_PAYOFF.endMs) },
    },
  ];
}

function prioritiesFixture(): Priority[] {
  return [
    {
      rank: 1,
      problem: "Your payoff arrives without a distinct turn that signals it has landed.",
      competitorPrinciple: "Holding a short beat before answering gives the payoff more weight.",
      howToApply: "Add one short beat before your answer that signals the reveal is about to land.",
      evidence: { user: userEvidence(UE_PAYOFF), competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs) },
    },
    {
      rank: 2,
      problem: "Your hook states the premise gently instead of naming a concrete mistake up front.",
      competitorPrinciple: "Naming a specific mistake in the opening line gives viewers an immediate reason to keep watching.",
      howToApply: "Rewrite your opening line to name the specific mistake instead of describing the general topic.",
      evidence: { user: userEvidence(UE_HOOK), competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs) },
    },
  ];
}

function cautionsFixture(): Caution[] {
  return [
    {
      whatNotToCopy: "Copying their exact opening phrasing",
      reason: "Their phrasing fits their channel's established tone; using it word for word elsewhere could read as jarring.",
      evidence: { competitor: competitorEvidence(CE_HOOK.excerpt, CE_HOOK.startMs, CE_HOOK.endMs), user: null },
    },
  ];
}

function baseComparison(overrides: Partial<CompetitorScriptComparison> = {}): CompetitorScriptComparison {
  return {
    schemaVersion: 1,
    locale: "en",
    comparisonSummary: {
      headline: "Their opening names a concrete mistake; yours states the premise more gently.",
      mainTakeaway: "Adding one short beat before your answer would give your payoff the same clear landing point their script has.",
    },
    dimensionFindings: dimensionFindingsFixture(),
    priorities: prioritiesFixture(),
    cautions: cautionsFixture(),
    ...overrides,
  };
}

function validate(candidate: unknown, expectedLocale: "en" | "ru" = "en") {
  return validateCompetitorScriptComparison({
    candidate,
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    expectedLocale,
  });
}

// ── Valid ──────────────────────────────────────────────────────────────

function testValid() {
  check("a fully valid comparison is accepted", validate(baseComparison()).ok);

  const ru = baseComparison({ locale: "ru" });
  check("a valid RU comparison is accepted", validate(ru, "ru").ok);

  const zeroCautions = baseComparison({ cautions: [] });
  check("zero cautions is accepted", validate(zeroCautions).ok);

  const onePriority = baseComparison({ priorities: [prioritiesFixture()[0]] });
  check("exactly one priority is accepted (minimum)", validate(onePriority).ok);

  const threePriorities = baseComparison({
    priorities: [
      prioritiesFixture()[0],
      prioritiesFixture()[1],
      {
        rank: 3,
        problem: "Your script never restates the mistake before offering the fix.",
        competitorPrinciple: "Restating the mistake briefly before the fix reminds the viewer what is at stake.",
        howToApply: "Add a short line restating the mistake right before your reveal.",
        evidence: { user: userEvidence(UE_STRUCTURE), competitor: competitorEvidence(CE_STRUCTURE.excerpt, CE_STRUCTURE.startMs, CE_STRUCTURE.endMs) },
      },
    ],
  });
  check("three priorities is accepted (maximum)", validate(threePriorities).ok);

  const nullEndMs = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0
        ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, endMs: null } } }
        : finding
    ),
  });
  check("competitor evidence with endMs null is accepted", validate(nullEndMs).ok);
}

// ── Shape / structure ─────────────────────────────────────────────────

function testShape() {
  check("a non-object candidate is rejected", !validate("not an object").ok);
  check("null candidate is rejected", !validate(null).ok);

  const extraField = { ...baseComparison(), extra: "not allowed" };
  const r1 = validate(extraField);
  check("an unexpected top-level property is rejected", !r1.ok && r1.failure.code === "invalid_shape");

  const missingCautions = { ...baseComparison() } as Record<string, unknown>;
  delete missingCautions.cautions;
  const r2 = validate(missingCautions);
  check("a missing required field is rejected", !r2.ok);

  const wrongVersion = baseComparison({ schemaVersion: 2 as 1 });
  const r3 = validate(wrongVersion);
  check("wrong schemaVersion is rejected", !r3.ok && r3.failure.code === "invalid_schema_version");

  const badLocale = { ...baseComparison(), locale: "fr" };
  const r4 = validate(badLocale);
  check("an unsupported locale is rejected", !r4.ok && r4.failure.code === "invalid_locale");

  const mismatchedLocale = validateCompetitorScriptComparison({
    candidate: baseComparison({ locale: "en" }),
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT,
    expectedLocale: "ru",
  });
  check("a locale mismatch against expectedLocale is rejected", !mismatchedLocale.ok && mismatchedLocale.failure.code === "invalid_locale");
}

// ── Dimensions ─────────────────────────────────────────────────────────

function testDimensions() {
  const missing = baseComparison({ dimensionFindings: dimensionFindingsFixture().slice(0, 3) });
  const r1 = validate(missing);
  check("fewer than 4 dimensions is rejected", !r1.ok && r1.failure.code === "invalid_dimension_set");

  const duplicate = baseComparison({
    dimensionFindings: [dimensionFindingsFixture()[0], dimensionFindingsFixture()[0], dimensionFindingsFixture()[2], dimensionFindingsFixture()[3]],
  });
  const r2 = validate(duplicate);
  check("a duplicate dimension is rejected", !r2.ok && r2.failure.code === "invalid_dimension_set");

  const wrongOrder = baseComparison({
    dimensionFindings: [
      dimensionFindingsFixture()[1],
      dimensionFindingsFixture()[0],
      dimensionFindingsFixture()[2],
      dimensionFindingsFixture()[3],
    ],
  });
  const r3 = validate(wrongOrder);
  check("wrong dimension order is rejected", !r3.ok && r3.failure.code === "invalid_dimension_order");

  const badStrongerSide = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, strongerSide: "both" as "user" } : finding
    ),
  });
  const r4 = validate(badStrongerSide);
  check("an invalid strongerSide is rejected", !r4.ok && r4.failure.code === "invalid_stronger_side");

  const gapOnSimilar = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 1 ? { ...finding, gap: "small" as const } : finding
    ),
  });
  const r5 = validate(gapOnSimilar);
  check("gap present when strongerSide is similar is rejected", !r5.ok && r5.failure.code === "invalid_gap");

  const missingGap = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, gap: null } : finding
    ),
  });
  const r6 = validate(missingGap);
  check("gap missing when strongerSide is not similar is rejected", !r6.ok && r6.failure.code === "invalid_gap");

  const overstatedSimilar = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 1 ? { ...finding, conclusion: "Yours is far better here." } : finding
    ),
  });
  const r7 = validate(overstatedSimilar);
  check('a "similar" finding with strong-advantage language is rejected', !r7.ok && r7.failure.code === "invalid_stronger_side");
}

// ── Priorities ─────────────────────────────────────────────────────────

function testPriorities() {
  const zero = baseComparison({ priorities: [] });
  const r1 = validate(zero);
  check("zero priorities is rejected", !r1.ok && r1.failure.code === "invalid_priority_count");

  const four = baseComparison({
    priorities: [
      ...prioritiesFixture(),
      { rank: 3, problem: "Extra problem statement here for testing.", competitorPrinciple: "Extra principle for testing purposes here.", howToApply: "Extra instruction for testing purposes here.", evidence: { user: userEvidence(UE_MOMENTUM), competitor: competitorEvidence(CE_MOMENTUM.excerpt, CE_MOMENTUM.startMs, CE_MOMENTUM.endMs) } },
      { rank: 4, problem: "Fourth problem statement here for testing.", competitorPrinciple: "Fourth principle for testing purposes here.", howToApply: "Fourth instruction for testing purposes here.", evidence: { user: userEvidence(UE_STRUCTURE), competitor: competitorEvidence(CE_STRUCTURE.excerpt, CE_STRUCTURE.startMs, CE_STRUCTURE.endMs) } },
    ],
  });
  const r2 = validate(four);
  check("more than 3 priorities is rejected", !r2.ok && r2.failure.code === "invalid_priority_count");

  const nonSequential = baseComparison({
    priorities: [prioritiesFixture()[0], { ...prioritiesFixture()[1], rank: 3 }],
  });
  const r3 = validate(nonSequential);
  check("non-sequential ranks is rejected", !r3.ok && r3.failure.code === "invalid_priority_rank");

  const duplicateProblem = baseComparison({
    priorities: [prioritiesFixture()[0], { ...prioritiesFixture()[1], problem: prioritiesFixture()[0].problem }],
  });
  const r4 = validate(duplicateProblem);
  check("duplicate priority problem statements are rejected", !r4.ok && r4.failure.code === "duplicate_content");

  const genericProblem = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "Make it more engaging." }, prioritiesFixture()[1]],
  });
  const r5 = validate(genericProblem);
  check("a bare generic-feedback problem is rejected", !r5.ok && r5.failure.code === "generic_feedback");

  const copiedPrinciple = baseComparison({
    priorities: [
      { ...prioritiesFixture()[0], competitorPrinciple: "I hold the tension for four extra lines before I answer the question." },
      prioritiesFixture()[1],
    ],
  });
  const r6 = validate(copiedPrinciple);
  check("verbatim competitor wording reused as an instruction is rejected", !r6.ok && r6.failure.code === "copy_instruction");
}

// ── Cautions ───────────────────────────────────────────────────────────

function testCautions() {
  const four = baseComparison({
    cautions: [
      cautionsFixture()[0],
      { ...cautionsFixture()[0], whatNotToCopy: "Second caution item" },
      { ...cautionsFixture()[0], whatNotToCopy: "Third caution item" },
      { ...cautionsFixture()[0], whatNotToCopy: "Fourth caution item" },
    ],
  });
  const r1 = validate(four);
  check("more than 3 cautions is rejected", !r1.ok && r1.failure.code === "invalid_caution_count");

  const duplicateCaution = baseComparison({
    cautions: [cautionsFixture()[0], { ...cautionsFixture()[0] }],
  });
  const r2 = validate(duplicateCaution);
  check("duplicate caution whatNotToCopy is rejected", !r2.ok && r2.failure.code === "duplicate_content");

  const missingUserKey = baseComparison({
    cautions: [{ whatNotToCopy: cautionsFixture()[0].whatNotToCopy, reason: cautionsFixture()[0].reason, evidence: { competitor: cautionsFixture()[0].evidence.competitor } as never }],
  });
  const r3 = validate(missingUserKey);
  check("a caution missing the required (nullable) user evidence property is rejected", !r3.ok && r3.failure.code === "invalid_shape");
}

// ── Evidence ───────────────────────────────────────────────────────────

function testEvidence() {
  const wrongUserSource = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, user: { ...finding.evidence.user, source: "competitor" as "user" } } } : finding
    ),
  });
  const r1 = validate(wrongUserSource);
  check("user evidence with the wrong source discriminator is rejected", !r1.ok && r1.failure.code === "invalid_evidence_source");

  const wrongCompetitorSource = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, source: "user" as "competitor" } } } : finding
    ),
  });
  const r2 = validate(wrongCompetitorSource);
  check("competitor evidence with the wrong source discriminator is rejected", !r2.ok && r2.failure.code === "invalid_evidence_source");

  const userExcerptNotFound = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, user: userEvidence("this text is not in the user script") } } : finding
    ),
  });
  const r3 = validate(userExcerptNotFound);
  check("a user excerpt not found in the user script is rejected", !r3.ok && r3.failure.code === "user_excerpt_not_found");

  const competitorExcerptNotFound = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: competitorEvidence("this text is not in the transcript", 0, 1000) } } : finding
    ),
  });
  const r4 = validate(competitorExcerptNotFound);
  check("a competitor excerpt not found in the transcript is rejected", !r4.ok && r4.failure.code === "competitor_excerpt_not_found");

  const inventedUserTimestamp = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0
        ? { ...finding, evidence: { ...finding.evidence, user: { ...finding.evidence.user, startMs: 0 } as unknown as typeof finding.evidence.user } }
        : finding
    ),
  });
  const r5 = validate(inventedUserTimestamp);
  check("a user evidence object with an invented timestamp field is rejected (unexpected property)", !r5.ok && r5.failure.code === "invalid_shape");

  const negativeStart = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, startMs: -1 } } } : finding
    ),
  });
  const r6 = validate(negativeStart);
  check("a negative competitor startMs is rejected", !r6.ok && r6.failure.code === "invalid_competitor_timestamp");

  const endBeforeStart = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, endMs: finding.evidence.competitor.startMs - 500 } } } : finding
    ),
  });
  const r7 = validate(endBeforeStart);
  check("competitor endMs before startMs is rejected", !r7.ok && r7.failure.code === "invalid_competitor_timestamp");

  const outsideDuration = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, startMs: 999999, endMs: null } } } : finding
    ),
  });
  const r8 = validate(outsideDuration);
  check("a competitor timestamp outside the transcript duration is rejected", !r8.ok && r8.failure.code === "invalid_competitor_timestamp");

  const notSegmentGrounded = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, competitor: { ...finding.evidence.competitor, startMs: 6500, endMs: null } } } : finding
    ),
  });
  const r9 = validateCompetitorScriptComparison({
    candidate: notSegmentGrounded,
    userScript: USER_SCRIPT,
    competitorTranscript: COMPETITOR_TRANSCRIPT_WITH_GAP,
    expectedLocale: "en",
  });
  check(
    "a competitor timestamp not intersecting any real segment (falls in a real gap) is rejected",
    !r9.ok && r9.failure.code === "competitor_evidence_not_segment_grounded"
  );

  const overlongExcerpt = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 0 ? { ...finding, evidence: { ...finding.evidence, user: userEvidence(USER_SCRIPT) } } : finding
    ),
  });
  const r10 = validate(overlongExcerpt);
  check("an overlong evidence excerpt is rejected", !r10.ok && r10.failure.code === "field_too_long");
}

// ── Grounding (direct pure-function tests) ─────────────────────────────

function testGrounding() {
  check(
    "a quote found in the user script only is grounded",
    findUnsupportedQuotedSpanAcrossSources(`They said "${UE_STRUCTURE.replace(/\.$/, "")}" clearly.`, USER_SCRIPT, COMPETITOR_TRANSCRIPT) === null
  );

  check(
    "a quote found in the competitor transcript only is grounded",
    findUnsupportedQuotedSpanAcrossSources(`The line "So here is the fix in 3 steps" opens the payoff.`, USER_SCRIPT, COMPETITOR_TRANSCRIPT) === null
  );

  check(
    "a quote found in neither source is rejected",
    findUnsupportedQuotedSpanAcrossSources('They call this the "breakthrough moment" early on.', USER_SCRIPT, COMPETITOR_TRANSCRIPT) === "breakthrough moment"
  );

  check(
    "a number present in the user script is grounded",
    findUnsupportedNumericClaimAcrossSources("It matters in 3 words.", USER_SCRIPT, COMPETITOR_TRANSCRIPT) === null
  );

  check(
    "a number present in the competitor transcript is grounded",
    findUnsupportedNumericClaimAcrossSources("They lay it out in 3 steps.", USER_SCRIPT, COMPETITOR_TRANSCRIPT) === null
  );

  check(
    "a timing-derived competitor number is grounded",
    findUnsupportedNumericClaimAcrossSources("Their next beat starts at 9000ms.", USER_SCRIPT, COMPETITOR_TRANSCRIPT) === null
  );

  check(
    "a number present in neither source is rejected",
    findUnsupportedNumericClaimAcrossSources("This is covered in 42 words.", USER_SCRIPT, COMPETITOR_TRANSCRIPT) === "42"
  );

  check(
    'a "winner" ranking claim is rejected',
    findRankingClaimViolation("Their version is the clear winner here.") === "winner"
  );

  check(
    'an "outperforms" ranking claim is rejected',
    findRankingClaimViolation("Their script outperforms yours in this section.") !== null
  );

  check(
    "a causal claim is rejected",
    findCausalClaimViolation("This structure choice results in more engagement.") !== null
  );

  check(
    'a "this is why it worked" causal claim is rejected',
    findCausalClaimViolation("This is why it worked so well for them.") !== null
  );

  check(
    "an editing/production claim is rejected",
    findUnsupportedProductionClaim("The editing on their video keeps things fast.") === "editing"
  );

  check(
    "a music production claim is rejected",
    findUnsupportedProductionClaim("The music under their hook builds tension.") === "music"
  );

  check(
    "a creator-intent claim is rejected",
    findUnsupportedIntentClaim("They wanted to keep viewers guessing longer.") !== null
  );

  check(
    "legitimate craft reasoning about why a technique works is NOT flagged as an intent claim",
    findUnsupportedIntentClaim("Holding the reveal a beat longer creates curiosity.") === null
  );

  check(
    "a long verbatim competitor phrase reused as prose is flagged as copied",
    findVerbatimCompetitorCopy("I hold the tension for four extra lines before I answer the question.", COMPETITOR_TRANSCRIPT) !== null
  );

  check(
    "a short, non-qualifying overlap is not flagged as copied",
    findVerbatimCompetitorCopy("Hold the tension a little longer before you answer.", COMPETITOR_TRANSCRIPT) === null
  );
}

// ── Consistency ────────────────────────────────────────────────────────

function testConsistency() {
  const duplicateSummary = baseComparison({
    comparisonSummary: {
      headline: "Their opening names a concrete mistake right away.",
      mainTakeaway: "Their opening names a concrete mistake right away.",
    },
  });
  const r1 = validate(duplicateSummary);
  check("headline and mainTakeaway as normalized duplicates is rejected", !r1.ok && r1.failure.code === "duplicate_content");

  const duplicateConclusion = baseComparison({
    dimensionFindings: dimensionFindingsFixture().map((finding, index) =>
      index === 2 ? { ...finding, conclusion: dimensionFindingsFixture()[0].conclusion } : finding
    ),
  });
  const r2 = validate(duplicateConclusion);
  check("duplicate dimension conclusions are rejected", !r2.ok && r2.failure.code === "duplicate_content");

  check("an empty cautions array is accepted as valid, not manufactured", validate(baseComparison({ cautions: [] })).ok);
}

// ── End-to-end failure-code coverage ────────────────────────────────────
// Confirms the public validator itself (not just the standalone grounding
// helpers exercised in testGrounding above) returns the correct code when
// a violation is embedded in a real field of a real candidate — this
// checks the wiring inside validateProseField's code mapping, not just
// the detector functions in isolation.

function testEndToEndFailureCodes() {
  const empty = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "   " }, prioritiesFixture()[1]],
  });
  const rEmpty = validate(empty);
  check(
    "an empty (whitespace-only) prose field is rejected end-to-end as empty_field",
    !rEmpty.ok && rEmpty.failure.code === "empty_field"
  );

  const badQuote = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: 'They claim "the breakthrough moment" happens here.' }, prioritiesFixture()[1]],
  });
  const rQuote = validate(badQuote);
  check(
    "an unsupported quoted span is rejected end-to-end as unsupported_quote",
    !rQuote.ok && rQuote.failure.code === "unsupported_quote"
  );

  const badNumber = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "This section runs for about 42 seconds too long." }, prioritiesFixture()[1]],
  });
  const rNumber = validate(badNumber);
  check(
    "an unsupported numeric claim is rejected end-to-end as unsupported_numeric_claim",
    !rNumber.ok && rNumber.failure.code === "unsupported_numeric_claim"
  );

  const badPerformance = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "The algorithm boosted their video more than yours." }, prioritiesFixture()[1]],
  });
  const rPerformance = validate(badPerformance);
  check(
    "a prohibited performance claim is rejected end-to-end as unsupported_performance_claim",
    !rPerformance.ok && rPerformance.failure.code === "unsupported_performance_claim"
  );

  const badProduction = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "The editing on your version feels slower than theirs." }, prioritiesFixture()[1]],
  });
  const rProduction = validate(badProduction);
  check(
    "an unsupported production claim is rejected end-to-end as unsupported_production_claim",
    !rProduction.ok && rProduction.failure.code === "unsupported_production_claim"
  );

  const badIntent = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "They wanted to keep viewers guessing longer than you do." }, prioritiesFixture()[1]],
  });
  const rIntent = validate(badIntent);
  check(
    "an unsupported creator-intent claim is rejected end-to-end as unsupported_intent_claim",
    !rIntent.ok && rIntent.failure.code === "unsupported_intent_claim"
  );

  const badCausal = baseComparison({
    priorities: [{ ...prioritiesFixture()[0], problem: "This structure choice results in more engagement for their video." }, prioritiesFixture()[1]],
  });
  const rCausal = validate(badCausal);
  check(
    "a prohibited causal claim is rejected end-to-end as unsupported_causal_claim",
    !rCausal.ok && rCausal.failure.code === "unsupported_causal_claim"
  );
}

async function main() {
  testValid();
  testShape();
  testDimensions();
  testPriorities();
  testCautions();
  testEvidence();
  testGrounding();
  testEndToEndFailureCodes();
  testConsistency();

  if (failures > 0) {
    process.exitCode = 1;
    console.error(`\n${failures} check(s) failed.`);
  } else {
    console.log("\nResult: all Competitor Scripts Compare Foundation tests passed.");
  }
}

void main();
