import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { buildAnalysisV2SystemPrompt } from "../engine/analysis-v2-prompt";

// Root cause (confirmed): for a saved Analysis V2 result — the current
// production path — "Improved Hook" is NOT generated by app/api/improve's
// prompt at all. app/results/page.tsx's handleImproveHook() displays
// savedAnalysisV2.result.suggestedHook directly, which is generated by
// THIS prompt (engine/analysis-v2-prompt.ts), the same one that produces
// scores. Its old "Hook rewrite style" section literally listed "Here's
// why." as the FIRST suggested continuation phrase for a hook rewrite —
// which is exactly what produced the diagnosed regression. This file
// verifies the hardened prompt content; it deliberately does NOT touch
// score computation, hookDecision classification criteria, riskyParts, or
// any other Analysis V2 scoring machinery — only the "Hook rewrite style"
// / suggestedHook-quality subsection.

const prompt = buildAnalysisV2SystemPrompt();

// ── Regression fixture: the exact reported Ronaldo scenario ─────────────
const RONALDO_SCRIPT =
  "Today I want to tell you something very interesting about Cristiano Ronaldo’s 2018 bicycle kick against Juventus, where his foot reached about 2.38 meters. The goal happened in the Champions League, and he lifted his body almost horizontally before striking the ball. That unusual height is why the goal is still remembered as one of the most athletic finishes of his career.";

const WEAK_OBSERVED_HOOK =
  "Cristiano Ronaldo’s 2018 bicycle kick against Juventus reached an incredible height of about 2.38 meters. Here's why this goal is still remembered as one of the most athletic finishes of his career.";

// An equivalent natural formulation is acceptable — this is ONE example of
// a strong result, not the only valid one (see the "principles, not one
// exact sentence" tests below).
const STRONG_EXAMPLE_HOOK =
  "Cristiano Ronaldo's foot reached about 2.38 meters during his 2018 bicycle kick against Juventus.";

// ── Local, test-only principle checks — encode the specific regression's
// diagnostic criteria for THIS fixture; never shipped in production code
// (see Phase 4: prompt hardening is preferred over a runtime heuristic). ──

const GENERIC_HYPE_WORDS = /\b(incredible|amazing|unbelievable|shocking|legendary)\b/i;
const UNNECESSARY_BRIDGE_PHRASES =
  /\b(here'?s why|here'?s how|what happened next|here'?s what actually happens)\b/i;

function splitIntoSentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => sentence.trim())
    .filter(Boolean);
}

// The diagnosed distortion: "the bicycle kick ... reached ... meters"
// instead of "his foot ... reached ... meters" — the measurement assigned
// to the wrong grammatical subject.
function measurementAssignedToKickNotFoot(hook: string): boolean {
  return (
    /\bkick\b[^.!?]{0,40}\breached\b/i.test(hook) &&
    !/\bfoot\b[^.!?]{0,60}\breached\b/i.test(hook)
  );
}

type TestCase = {
  name: string;
  run: () => void;
};

const tests: TestCase[] = [
  // ── Fixture sanity: confirm the regression is real and detectable ─────
  {
    name: "The script grounds the measurement on the foot, not the bicycle kick itself",
    run: () => {
      assert.match(RONALDO_SCRIPT, /his foot reached about 2\.38 meters/i);
    },
  },
  {
    name: "The weak observed hook reassigns the measurement to the bicycle kick instead of the foot (the diagnosed grammatical-subject distortion)",
    run: () => {
      assert.equal(measurementAssignedToKickNotFoot(WEAK_OBSERVED_HOOK), true);
    },
  },
  {
    name: "The strong example hook keeps the foot as the grammatical subject of the measurement",
    run: () => {
      assert.equal(measurementAssignedToKickNotFoot(STRONG_EXAMPLE_HOOK), false);
      assert.match(STRONG_EXAMPLE_HOOK, /\bfoot\b[^.!?]{0,60}\breached\b/i);
    },
  },
  {
    name: "The weak observed hook contains the unnecessary 'Here's why' bridge the prompt now explicitly discourages",
    run: () => {
      assert.match(WEAK_OBSERVED_HOOK, UNNECESSARY_BRIDGE_PHRASES);
    },
  },
  {
    name: "The strong example hook needs no bridge phrase and is a single sentence",
    run: () => {
      assert.doesNotMatch(STRONG_EXAMPLE_HOOK, UNNECESSARY_BRIDGE_PHRASES);
      assert.equal(splitIntoSentences(STRONG_EXAMPLE_HOOK).length, 1);
    },
  },
  {
    name: "The weak observed hook uses generic hype (\"incredible\") in place of a stronger concrete detail",
    run: () => {
      assert.match(WEAK_OBSERVED_HOOK, GENERIC_HYPE_WORDS);
    },
  },
  {
    name: "The strong example hook needs no generic hype word — the concrete measurement alone carries the hook",
    run: () => {
      assert.doesNotMatch(STRONG_EXAMPLE_HOOK, GENERIC_HYPE_WORDS);
    },
  },
  {
    name: "Every grounded fact from the script (subject, 2018, Juventus, about 2.38 meters, foot) remains present in the strong example hook — no facts invented, none dropped",
    run: () => {
      assert.match(STRONG_EXAMPLE_HOOK, /Ronaldo/i);
      assert.match(STRONG_EXAMPLE_HOOK, /2018/);
      assert.match(STRONG_EXAMPLE_HOOK, /Juventus/);
      assert.match(STRONG_EXAMPLE_HOOK, /2\.38 meters/);
      assert.match(STRONG_EXAMPLE_HOOK, /\bfoot\b/i);
    },
  },
  {
    name: "The strong example hook adds no unsupported certainty beyond the script (no invented cause, guarantee, or outcome)",
    run: () => {
      assert.doesNotMatch(STRONG_EXAMPLE_HOOK, /\b(guarantee|always|proven|record-breaking|world record)\b/i);
    },
  },

  // ── Prompt-level regression coverage: the actual fix ───────────────────
  {
    name: "The prompt no longer suggests \"Here's why\" as a good continuation example — the old phrase bank is gone",
    run: () => {
      assert.doesNotMatch(
        prompt,
        /Good examples include.*"Here's why\."/
      );
      assert.doesNotMatch(
        prompt,
        /use a context-appropriate curiosity-driving continuation/i
      );
    },
  },
  {
    name: "The prompt requires preserving the exact grammatical subject/object of every action or measurement, using the foot/bicycle-kick distinction only as an illustrative principle (never hardcoded runtime behavior)",
    run: () => {
      assert.match(
        prompt,
        /Preserve the exact grammatical subject and object of every action, measurement, or claim exactly as the script states them\./
      );
      assert.match(
        prompt,
        /Never transfer an action or a measurement \(a height, distance, speed, weight, or similar\) to a different subject/
      );
      assert.match(
        prompt,
        /if the script says a body part reached a height during an action, the rewrite must keep that same body part, not the action or event itself, as the thing that reached it/
      );
    },
  },
  {
    name: "The prompt requires leading with a concrete fact already in the script rather than delaying behind a generic opener",
    run: () => {
      assert.match(
        prompt,
        /lead with that fact directly in the first sentence — do not delay it behind a generic opener/
      );
    },
  },
  {
    name: "The prompt explicitly discourages an automatic 'Here's why'/'Here's how' bridge sentence unless the script actually delivers that exact promise AND the first sentence alone is not already sufficient",
    run: () => {
      assert.match(
        prompt,
        /Do not automatically append a second sentence as a generic curiosity bridge\./
      );
      assert.match(
        prompt,
        /"Here's why", "Here's how", "What happened next", "Here's what actually happens", "The answer is surprising", or similar template continuations must only appear when the remaining script explicitly delivers that exact promise/
      );
    },
  },
  {
    name: "The prompt prefers the shortest hook containing the subject and concrete action, adding a second sentence only for a distinct necessary detail — never merely for suspense",
    run: () => {
      assert.match(
        prompt,
        /Prefer the shortest hook that already contains the named subject, the concrete action, and enough context to understand it\./
      );
      assert.match(
        prompt,
        /Add a second sentence only when it contributes a distinct, necessary, grounded detail the first sentence could not include — never merely to manufacture suspense or curiosity\./
      );
    },
  },
  {
    name: "The prompt discourages generic intensifiers when the concrete fact is already the strongest detail, WITHOUT banning every adjective globally",
    run: () => {
      assert.match(
        prompt,
        /Do not add a generic intensifier such as incredible, amazing, unbelievable, shocking, or legendary when the concrete fact itself is already the strongest available detail\./
      );
      assert.match(
        prompt,
        /This does not ban every adjective — a grounded one that adds meaning beyond the specific fact is still allowed\./
      );
    },
  },
  {
    name: "The prompt does not force a question or suspenseful bridge when a direct factual statement is already the strongest hook",
    run: () => {
      assert.match(
        prompt,
        /Do not force a question, a suspenseful bridge, or a "but then" contrast when a direct factual statement is already the strongest available hook for this script\./
      );
    },
  },
  {
    name: "The prompt requires a silent internal candidate audit before finalizing suggestedHook, and forbids exposing that reasoning to the user",
    run: () => {
      assert.match(
        prompt,
        /Before finalizing suggestedHook, silently audit the candidate against every item below and revise it internally if any item fails\. Never expose this reasoning, and never mention the audit itself in hookAssessment or any other field:/
      );
      assert.match(
        prompt,
        /Is the grammatical subject of every action and measurement exactly the one the script assigns it to, never transferred to a broader event, a different person, or a different body part or object\?/
      );
      assert.match(
        prompt,
        /Is a "Here's why" or other bridge phrase present without being strictly necessary, when the hook could already stand alone as one sentence\?/
      );
      assert.match(
        prompt,
        /Is the candidate meaningfully stronger than the original through at least one concrete editorial operation/
      );
    },
  },
  {
    name: "The 'suggestedHook must never' list explicitly forbids reassigning a measurement to the wrong grammatical subject",
    run: () => {
      assert.match(
        prompt,
        /assign an action, distance, height, speed, weight, or other measurement to a different grammatical subject than the one the script actually gives it/
      );
    },
  },
  {
    name: "The 'suggestedHook must never' list explicitly forbids promising a mystery/comparison/explanation/outcome the rest of the script does not deliver (full-script alignment)",
    run: () => {
      assert.match(
        prompt,
        /promise a mystery, comparison, explanation, or outcome that the rest of the submitted script does not actually deliver\./
      );
    },
  },
  {
    name: "hookAssessment must describe the real editorial change in plain terms, and must never claim guaranteed retention/views, perfection, or that changes were applied to the saved script",
    run: () => {
      assert.match(
        prompt,
        /hookAssessment must describe the actual editorial change in plain, concrete terms/
      );
      assert.match(
        prompt,
        /hookAssessment must never claim guaranteed higher retention, guaranteed views, that the suggestedHook is perfect, or that any change has already been applied to the creator's script/
      );
    },
  },

  // ── Regression guards: legitimate patterns must remain allowed ─────────
  {
    name: "A legitimate two-sentence hook remains allowed when the second sentence adds necessary grounded information — the rule requires a 'distinct, necessary, grounded detail', not a blanket one-sentence-only mandate",
    run: () => {
      assert.match(
        prompt,
        /Add a second sentence only when it contributes a distinct, necessary, grounded detail the first sentence could not include/
      );
      assert.doesNotMatch(prompt, /always use exactly one sentence/i);
      assert.doesNotMatch(prompt, /never use more than one sentence/i);
      assert.doesNotMatch(prompt, /never use two sentences/i);
    },
  },
  {
    name: "A legitimate 'Here's why' remains allowed when the script actually delivers it — the rule is conditional, not a blanket ban on the phrase",
    run: () => {
      assert.match(
        prompt,
        /must only appear when the remaining script explicitly delivers that exact promise/
      );
      assert.doesNotMatch(prompt, /never use "here's why"/i);
      assert.doesNotMatch(prompt, /always forbidden/i);
    },
  },
  {
    name: "Question hooks are not forced — the new rule explicitly disallows forcing a question, a suspenseful bridge, or a \"but then\" contrast",
    run: () => {
      assert.match(
        prompt,
        /Do not force a question, a suspenseful bridge, or a "but then" contrast when a direct factual statement is already the strongest available hook for this script\./
      );
    },
  },
  {
    name: "Named entities, numbers, units, causes, outcomes, and uncertainty still cannot be invented — the existing grounding rules are unchanged",
    run: () => {
      assert.match(
        prompt,
        /invent a number, name, mechanism, event, product claim, consequence, or level of certainty/
      );
      assert.match(
        prompt,
        /Is every name, number, unit, date, opponent, and action grounded exactly in the script, with nothing invented\?/
      );
    },
  },
  {
    name: "The model cannot transfer an action or measurement to a different subject — both the style rule and the 'must never' rule state this explicitly",
    run: () => {
      const styleRuleIndex = prompt.indexOf(
        "Never transfer an action or a measurement"
      );
      const mustNeverRuleIndex = prompt.indexOf(
        "assign an action, distance, height, speed, weight, or other measurement to a different grammatical subject"
      );
      assert.ok(styleRuleIndex >= 0 && mustNeverRuleIndex > styleRuleIndex);
    },
  },
  {
    name: "The existing 'preserve a strong original unless clearly better' guidance is unchanged after the audit was added",
    run: () => {
      assert.match(
        prompt,
        /Return keep unless the candidate is clearly better overall after that audit\./
      );
    },
  },
  {
    name: "The pre-existing 'must not state the explanation and then promise to explain that same explanation' rule (already in the codebase) is preserved verbatim",
    run: () => {
      assert.match(
        prompt,
        /A suggestedHook must not state the explanation and then promise to explain that same explanation\./
      );
    },
  },

  // ── No deterministic runtime validator was added (Phase 4 decision) ────
  {
    name: "No new deterministic hook-quality validator was added to Analysis V2 validation — this fix is prompt-only, per the explicit preference for prompt hardening over a risky heuristic",
    run: () => {
      const validationSource = readFileSync(
        "engine/analysis-v2-validation.ts",
        "utf8"
      );
      assert.doesNotMatch(validationSource, /suggestedHook.*(reject|invalid|guard)/i);
    },
  },
];

async function main(): Promise<void> {
  console.log("\nImprove Hook Editorial Quality Tests\n");

  let passed = 0;

  for (const test of tests) {
    try {
      test.run();
      passed += 1;
      console.log(`✅ PASS — ${test.name}`);
    } catch (error) {
      console.error(`❌ FAIL — ${test.name}`);
      console.error(error instanceof Error ? error.message : error);
      process.exitCode = 1;
    }
  }

  console.log(
    `\nImprove Hook editorial quality tests: ${passed}/${tests.length} passed`
  );
}

main();
