// Provider-agnostic transcript model, error taxonomy, and provider
// contract for Competitor Scripts. This module defines shapes only — no
// network access, no real provider, no persistence. See normalize.ts for
// the safe-validation implementation that produces these shapes.

export type TranscriptSegment = {
  text: string;
  startMs: number;
  durationMs: number | null;
};

export type NormalizedTranscript = {
  videoId: string;
  languageCode: string | null;
  isAutoGenerated: boolean | null;
  segments: TranscriptSegment[];
  text: string;
  durationMs: number | null;
};

// The smallest generic raw segment shape a normalizer needs to accept.
// Deliberately not modeled after any specific external transcript
// service's payload — every field is `unknown` and validated by
// normalize.ts before use.
export type RawTranscriptSegment = {
  text: unknown;
  startMs: unknown;
  durationMs?: unknown;
};

// Input to the normalizer. `segments` is intentionally `unknown` (not
// `RawTranscriptSegment[]`) — the normalizer must prove it is even an
// array before trusting its shape.
export type NormalizeTranscriptInput = {
  videoId: string;
  languageCode?: unknown;
  isAutoGenerated?: unknown;
  segments: unknown;
};

export type TranscriptErrorCode =
  | "transcript_not_found"
  | "transcript_disabled"
  | "transcript_unavailable"
  | "unsupported_language"
  | "video_unavailable"
  | "provider_rate_limited"
  | "provider_timeout"
  | "provider_unavailable"
  | "invalid_provider_response";

export type TranscriptError = {
  code: TranscriptErrorCode;
  message: string;
  retryable: boolean;
};

export type TranscriptProviderResult =
  | {
      ok: true;
      transcript: NormalizedTranscript;
    }
  | {
      ok: false;
      error: TranscriptError;
    };

// Server-side provider contract. Implementations receive only the
// already-validated canonical video id — never a raw URL, locale, AI
// instructions, user data, or score settings.
export interface TranscriptProvider {
  getTranscript(input: { videoId: string }): Promise<TranscriptProviderResult>;
}

// retryable is deterministic per code — never decided at the call site —
// so every caller and every test agrees on the same classification.
const TRANSCRIPT_ERROR_TABLE: Record<
  TranscriptErrorCode,
  { message: string; retryable: boolean }
> = {
  transcript_not_found: {
    message: "This video doesn't appear to have a transcript.",
    retryable: false,
  },
  transcript_disabled: {
    message: "Transcripts are turned off for this video.",
    retryable: false,
  },
  transcript_unavailable: {
    message: "The transcript isn't available right now.",
    retryable: true,
  },
  unsupported_language: {
    message: "This video's transcript language isn't supported yet.",
    retryable: false,
  },
  video_unavailable: {
    message: "This video isn't available.",
    retryable: false,
  },
  provider_rate_limited: {
    message: "Too many requests right now. Please try again shortly.",
    retryable: true,
  },
  provider_timeout: {
    message: "The transcript request took too long. Please try again.",
    retryable: true,
  },
  provider_unavailable: {
    message: "The transcript service is temporarily unavailable.",
    retryable: true,
  },
  invalid_provider_response: {
    message: "The transcript data returned was invalid.",
    retryable: false,
  },
};

// Every message here is a static, generic string from the table above —
// never provider response content, so this can never leak an HTML
// fragment, a stack trace, a URL, or a secret.
//
// The `code` parameter is typed as TranscriptErrorCode, but TypeScript
// types are erased at runtime — a caller passing a value that only
// *claims* to be a TranscriptErrorCode (e.g. an unvalidated string from
// a future real provider) could otherwise crash this lookup. Falling
// back to invalid_provider_response keeps this function itself in the
// same "never throw, always return a typed result" family as the rest
// of this module.
export function createTranscriptError(code: TranscriptErrorCode): TranscriptError {
  const entry = TRANSCRIPT_ERROR_TABLE[code];

  if (!entry) {
    const fallback = TRANSCRIPT_ERROR_TABLE.invalid_provider_response;
    return {
      code: "invalid_provider_response",
      message: fallback.message,
      retryable: fallback.retryable,
    };
  }

  return { code, message: entry.message, retryable: entry.retryable };
}
