"use client";

import { useId, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Link2, Loader2, Lock } from "lucide-react";
import type { Messages } from "../../../lib/messages";
import { isSupportedVideoUrl } from "../url-validation";
import { writeStoredAnalyzeResult } from "../../../lib/competitor-scripts/analyze-result-storage";
import type { TranscriptSegment } from "../../../lib/competitor-scripts/transcript/types";

type AnalyzeCopy = Messages["competitorScripts"]["analyze"];
type ApiErrorCode = keyof AnalyzeCopy["apiErrors"];

// Every code the API route can currently return, mapped to a safe,
// localized message. Codes the client's own local validation should
// already have caught (e.g. YouTube URL shape errors) still fall back
// here defensively — the server remains the source of truth. Never
// shows a raw backend message: only ever this table's copy.
const API_ERROR_CODE_MAP: Record<string, ApiErrorCode> = {
  rate_limited: "rateLimited",
  transcript_not_found: "transcriptNotFound",
  transcript_unavailable: "transcriptUnavailable",
  video_unavailable: "videoUnavailable",
  transcript_rate_limited: "transcriptRateLimited",
  transcript_timeout: "transcriptTimeout",
  transcript_service_unavailable: "transcriptServiceUnavailable",
  invalid_transcript_response: "invalidTranscriptResponse",
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const SOURCE_FORMATS = new Set(["watch", "shorts", "short"]);

function isValidSuccessPayload(payload: unknown): payload is {
  ok: true;
  input: { videoId: string; canonicalUrl: string; sourceFormat: string };
  transcript: {
    languageCode: string | null;
    isAutoGenerated: boolean | null;
    segments: unknown[];
    text: string;
    durationMs: number | null;
  };
} {
  if (!isPlainObject(payload) || payload.ok !== true) {
    return false;
  }

  const { input, transcript } = payload;

  if (!isPlainObject(input) || !isPlainObject(transcript)) {
    return false;
  }

  if (
    typeof input.videoId !== "string" ||
    typeof input.canonicalUrl !== "string" ||
    typeof input.sourceFormat !== "string" ||
    !SOURCE_FORMATS.has(input.sourceFormat)
  ) {
    return false;
  }

  const { languageCode, isAutoGenerated, segments, text, durationMs } =
    transcript;

  return (
    (languageCode === null || typeof languageCode === "string") &&
    (isAutoGenerated === null || typeof isAutoGenerated === "boolean") &&
    Array.isArray(segments) &&
    typeof text === "string" &&
    (durationMs === null || typeof durationMs === "number")
  );
}

// Local URL validation only navigates once the API call actually succeeds
// — no fetch used to mean an immediate, unconditional route push. Now it
// submits to POST /api/competitor-scripts/analyze, shows a real loading
// state, maps safe API errors to localized copy, and only writes the
// sessionStorage handoff payload (and navigates) on a verified success
// shape. The raw submitted URL never leaves this component's state or the
// request body — it is never placed in a query string or persisted.
export function AnalyzeInputForm({ copy }: { copy: AnalyzeCopy }) {
  const router = useRouter();
  const inputId = useId();
  const errorId = useId();
  const [url, setUrl] = useState("");
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const submissionInFlight = useRef(false);

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (submissionInFlight.current) {
      return;
    }

    const trimmed = url.trim();

    if (trimmed.length === 0) {
      setError(copy.errors.emptyUrl);
      return;
    }

    let isWellFormed = true;
    try {
      new URL(trimmed);
    } catch {
      isWellFormed = false;
    }

    if (!isWellFormed) {
      setError(copy.errors.invalidUrl);
      return;
    }

    if (!isSupportedVideoUrl(trimmed)) {
      setError(copy.errors.unsupportedUrl);
      return;
    }

    setError("");
    submissionInFlight.current = true;
    setIsSubmitting(true);

    void (async () => {
      let response: Response;

      try {
        response = await fetch("/api/competitor-scripts/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ url: trimmed }),
        });
      } catch {
        submissionInFlight.current = false;
        setIsSubmitting(false);
        setError(copy.apiErrors.networkError);
        return;
      }

      let payload: unknown;

      try {
        payload = await response.json();
      } catch {
        submissionInFlight.current = false;
        setIsSubmitting(false);
        setError(copy.apiErrors.unexpectedError);
        return;
      }

      if (response.ok && isValidSuccessPayload(payload)) {
        writeStoredAnalyzeResult({
          input: {
            videoId: payload.input.videoId,
            canonicalUrl: payload.input.canonicalUrl,
            sourceFormat: payload.input.sourceFormat as
              | "watch"
              | "shorts"
              | "short",
          },
          transcript: {
            languageCode: payload.transcript.languageCode,
            isAutoGenerated: payload.transcript.isAutoGenerated,
            segments: payload.transcript.segments as TranscriptSegment[],
            text: payload.transcript.text,
            durationMs: payload.transcript.durationMs,
          },
        });

        router.push("/competitor-scripts/analyze/results");
        return;
      }

      submissionInFlight.current = false;
      setIsSubmitting(false);

      const code =
        isPlainObject(payload) &&
        isPlainObject(payload.error) &&
        typeof payload.error.code === "string"
          ? payload.error.code
          : null;

      const mappedKey = code ? API_ERROR_CODE_MAP[code] : undefined;

      setError(
        mappedKey
          ? copy.apiErrors[mappedKey]
          : copy.apiErrors.requestInvalid
      );
    })();
  }

  return (
    <form
      onSubmit={handleSubmit}
      noValidate
      className="mt-4 rounded-[28px] border border-[#7C3AED]/25 bg-gradient-to-b from-[#7C3AED]/[0.06] to-transparent p-6 lg:p-8"
    >
      <label
        htmlFor={inputId}
        className="text-[13px] font-semibold text-[#F5F5F7]"
      >
        {copy.urlLabel}
      </label>

      <div
        className={`mt-2.5 flex h-[56px] items-center gap-3 rounded-[14px] border bg-white/[0.03] px-4 ${
          error ? "border-[#EF4444]/60" : "border-white/10"
        }`}
      >
        <Link2
          size={18}
          className="shrink-0 text-[#6B7280]"
          aria-hidden="true"
        />
        <input
          id={inputId}
          type="url"
          inputMode="url"
          value={url}
          disabled={isSubmitting}
          onChange={(event) => {
            setUrl(event.target.value);
            if (error) setError("");
          }}
          placeholder={copy.urlPlaceholder}
          aria-invalid={error ? true : undefined}
          aria-describedby={error ? errorId : undefined}
          className="h-full w-full bg-transparent text-[15px] text-[#F5F5F7] outline-none placeholder:text-[#6B7280] disabled:opacity-60"
        />
      </div>

      {error && (
        <p
          id={errorId}
          role="alert"
          className="mt-2.5 text-[13px] font-medium text-[#EF4444]"
        >
          {error}
        </p>
      )}

      <div className="mt-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div className="flex items-start gap-3 lg:max-w-[420px]">
          <Lock
            size={15}
            className="mt-0.5 shrink-0 text-[#9CA3AF]"
            aria-hidden="true"
          />
          <div>
            <p className="text-[12.5px] font-semibold text-[#F5F5F7]">
              {copy.privacyNote.heading}
            </p>
            <ul className="mt-1 flex flex-col gap-0.5">
              {copy.privacyNote.items.map((item) => (
                <li
                  key={item}
                  className="text-[12px] leading-[1.55] text-[#9CA3AF]"
                >
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <button
          type="submit"
          disabled={isSubmitting || url.trim().length === 0}
          className="inline-flex h-[52px] w-full shrink-0 items-center justify-center gap-2.5 rounded-[14px] bg-gradient-to-r from-[#6D28D9] to-[#7C3AED] px-7 text-[15px] font-semibold text-white transition hover:from-[#7C3AED] hover:to-[#8B5CF6] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#C4B5FD] disabled:cursor-not-allowed disabled:from-[#3D2A66] disabled:to-[#3D2A66] disabled:text-[#8B7BAE] lg:w-auto"
        >
          {isSubmitting ? (
            <>
              <Loader2
                size={17}
                className="animate-spin"
                aria-hidden="true"
              />
              {copy.submittingLabel}
            </>
          ) : (
            <>
              {copy.submitLabel}
              <ArrowRight size={17} aria-hidden="true" />
            </>
          )}
        </button>
      </div>
    </form>
  );
}
